import {loadSave} from '../engine.js';
import {ROADMAP,validatePack,validateProgress,recordAttempt,mergeProgress} from './model.js';
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,packs=[],records=new Map(),profile,profiles=[],pages=[],cards=[],chapter='All',search='',view='home',pageOffset=0,queue=[],cursor=0,revealed=false,answered=false,currentPage=null,options=[],busy=false,wordSearch='';
function announce(t){document.querySelector('#status').textContent=t;}
function readProfiles(){const s=loadSave(localStorage).save;profiles=s.profiles;profile=profiles.some(x=>x.id===profile)?profile:s.active;}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('linguistics-visual-library',1);r.onupgradeneeded=()=>{r.result.createObjectStore('packs',{keyPath:'id'});r.result.createObjectStore('progress',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Close other library tabs, then reload.'));});}
function all(store){return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function put(store,items){return new Promise((resolve,reject)=>{const t=db.transaction(store,'readwrite');for(const x of items)t.objectStore(store).put(x);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Save interrupted'));});}
function rebuild(){pages=packs.flatMap(p=>p.pages.map(x=>({...x,key:p.id+'::'+x.id,pack:p.id,book:p.title})));cards=packs.flatMap(p=>p.cards.map(c=>({...c,key:p.id+'::'+c.id,pageKey:p.id+'::'+c.pageId,parentKey:c.parentId?p.id+'::'+c.parentId:null,book:p.title})));}
const key=c=>profile+'::'+c.key;
const record=c=>records.get(key(c));
const selectedCards=()=>cards.filter(c=>chapter==='All'||c.chapter===chapter);
const due=c=>record(c)&&record(c).due<=Date.now();
function button(t,a,extra='',cls=''){return `<button data-action="${a}" ${extra} class="${cls}">${t}</button>`;}
function shell(body){app.innerHTML=`<header><a class="brand" href="../"><span class="brand-icon">▤</span><span>MY PERSONAL<b>VISUAL LIBRARY</b></span></a><div class="profile"><label for="profile">Learner</label><select id="profile">${profiles.map(p=>`<option value="${esc(p.id)}" ${p.id===profile?'selected':''}>${esc(p.name)}</option>`).join('')}</select><a href="../">Manage profiles ↗</a></div></header><nav class="library-nav" aria-label="Library navigation">${button('My library','home','',view==='home'?'active':'')}${button('Browse pages','browse','',view==='browse'?'active':'')}${button('Word lookup','lookup')}${button('Meaning cards','study')}${button('Due reviews','review')}<a href="../academy/">Common Word Academy ↗</a></nav><main id="main" tabindex="-1">${body}</main><footer><a href="../">← Linguistics Quest</a><span>Personal study • Imported books stay in this browser</span></footer>`;}
function home(){view='home';chapter='All';const seen=cards.filter(c=>record(c)?.seen).length;const upcoming=cards.filter(due).length;
 shell(`<section class="library-hero"><p class="eyebrow">A PICTURE. A WORD. A WORLD TO UNDERSTAND.</p><h1>Your books, made into a learning journey.</h1><p>Explore the pictures. Learn what each word means. Explain it in your own words, then check your understanding.</p></section><section class="import-box"><h2>${packs.length?'Your library is growing.':'Add your first study pack.'}</h2><p>Import the prepared JSON study pack from this conversation. It includes your scanned pages and meaning cards. More packs can be added here later; importing an updated pack keeps existing card progress.</p><div class="actions">${button('Import study pack','import','','primary')}${button('Back up progress','backup',!cards.length?'disabled':'')}${button('Restore progress','restore')}</div><p class="source-note">The app stores imports on this device using browser storage. It does not upload book pages. Keep your downloaded packs and progress backups; clearing browser data removes local copies. A raw PDF must first be prepared into a study pack.</p></section><div class="metrics"><div><b>${pages.length}</b><span>scanned pages</span></div><div><b>${cards.length}</b><span>prepared meaning cards</span></div><div><b>${seen} / ${cards.length}</b><span>cards attempted</span></div><div><b>${upcoming}</b><span>reviews due</span></div></div>${cards.length?`<div class="actions">${button('Look up a word','lookup','','primary')}${button('Continue learning →','study')}${button('Review due meanings','review')}</div>`:''}<h2>The book’s learning map</h2><p>Topics follow the table of contents. Page availability and prepared lessons are counted separately.</p><div class="tiles">${ROADMAP.map((ch,i)=>{let ps=pages.filter(p=>p.chapter===ch),cs=cards.filter(c=>c.chapter===ch);return `<article class="tile ${ps.length?'':'pending'}"><span class="tag">${String(i+1).padStart(2,'0')}</span><h2>${esc(ch)}</h2><p>${ps.length?`${ps.length} pages · ${cs.length} meaning cards`:'Waiting for a later upload'}</p>${ps.length?`<div class="actions">${button('Browse','chapter-pages',`data-chapter="${esc(ch)}"`)}${cs.length?button('Learn','chapter-study',`data-chapter="${esc(ch)}"`,'primary'):''}</div>`:''}</article>`;}).join('')}</div>${packs.length?`<h2 style="margin-top:32px">Imported volumes</h2>${packs.map(p=>`<p><strong>${esc(p.title)}</strong><br>${p.pages.length} pages · ${p.cards.length} cards · ${esc(p.note||'')}</p>`).join('')}`:''}`);
}
function lookup(){view='lookup';shell(`<p class="eyebrow">ONE ITEM. ITS PICTURE. ITS MEANING.</p><h1>Look up a word.</h1><p>Open a topic to find its parts and examples. Entries with an extracted picture show that item on its own; starter cards still use their full source page.</p><div class="toolbar"><label>Word, meaning, or topic<input id="word-search" type="search" value="${esc(wordSearch)}" placeholder="Try buckwheat or grain plants"></label>${button('Find word','word-search')}</div><div id="word-results"></div>`);lookupResults();}
function lookupResults(){const matches=cards.filter(c=>`${c.term} ${c.meaning} ${c.chapter}`.toLowerCase().includes(wordSearch.toLowerCase()));document.querySelector('#word-results').innerHTML=`<p>${matches.length} entries${matches.length>100?' · showing the first 100; narrow your search.':''}</p><div class="tiles">${matches.slice(0,100).map(c=>{const parent=cards.find(x=>x.key===c.parentKey);return `<button class="tile" data-action="card" data-key="${esc(c.key)}">${c.image?`<img class="entry-thumb" src="${c.image}" alt="${esc(c.term)}" loading="lazy">`:''}<strong>${esc(c.term)}</strong><p>${esc(parent?.term||c.chapter)}</p><span class="tag">${cards.some(x=>x.parentKey===c.key)?'Topic with linked entries':'Meaning card'}</span></button>`;}).join('')}</div>${matches.length?'':'<p class="empty-state">No prepared entry matches yet. Search Browse pages to find words in the scan text.</p>'}`;}
function browse(){view='browse';shell(`<p class="eyebrow">LOOK CLOSELY. FOLLOW THE LABELS.</p><h1>Browse your illustrated pages.</h1><div class="toolbar"><label>Chapter<select id="chapter"><option>All</option><option>Book guide</option>${ROADMAP.map(ch=>`<option ${ch===chapter?'selected':''}>${esc(ch)}</option>`).join('')}</select></label><label>Search titles and scanned text<input id="search" value="${esc(search)}" type="search" placeholder="Try Moon, leaf, or water"></label>${button('Search','search')}</div><div id="page-results"></div>`);if(chapter==='Book guide')document.querySelector('#chapter').value=chapter;pageResults();}
function pageResults(){const found=pages.filter(p=>(chapter==='All'||p.chapter===chapter)&&(!search||`${p.title} ${p.ocr}`.toLowerCase().includes(search.toLowerCase())));if(pageOffset>=found.length)pageOffset=0;document.querySelector('#page-results').innerHTML=`<p>${found.length} pages${search?' · OCR search may miss faint or distorted labels.':''}</p><div class="page-list">${found.slice(pageOffset,pageOffset+12).map(p=>`<button data-action="page" data-key="${esc(p.key)}"><img src="${p.image}" alt="Scanned page: ${esc(p.title)}" loading="lazy"><strong>${esc(p.title)}</strong><span>PDF page ${p.number} · ${esc(p.chapter)}</span></button>`).join('')}</div>${!found.length?'<p class="empty-state">No matching pages. Import a study pack or adjust your search.</p>':''}<div class="actions">${button('Previous pages','prev-pages',pageOffset===0?'disabled':'')}${button('Next pages','next-pages',pageOffset+12>=found.length?'disabled':'')}</div>`;}
function reader(p){view='reader';currentPage=p;shell(`<div class="lesson-top">${button('← Browse pages','browse')}<span>PDF page ${p.number} · ${esc(p.chapter)}</span></div><h1>${esc(p.title)}</h1><div class="reader"><div><div class="scan-zoom"><img src="${p.image}" alt="${esc(p.title)} — scanned dictionary page ${p.number}"></div><div class="actions">${button('Zoom page','zoom')}${button('Previous page','previous-page',pages.indexOf(p)===0?'disabled':'')}${button('Next page','next-page',pages.indexOf(p)===pages.length-1?'disabled':'')}</div></div><aside><p class="source-note">${esc(p.book)} · PDF page ${p.number}. The scan preserves the book’s original labels and definitions.</p><h2>Meaning cards on this page</h2>${cards.filter(c=>c.pageKey===p.key).map(c=>`<p>${button(esc(c.term),'card',`data-key="${esc(c.key)}"`)}</p>`).join('')||'<p>No prepared cards on this page yet. You can read the original page now.</p>'}<details><summary>Searchable scan text (OCR)</summary><p class="source-note">Machine-extracted text can contain mistakes. Use the scanned page to verify wording, numbers, and labels. The book reflects its publication date.</p><pre class="ocr">${esc(p.ocr||'No readable text detected.')}</pre></details></aside></div>`);}
function start(review=false){view='study';const set=selectedCards();queue=review?set.filter(due):[...set.filter(c=>!record(c)),...set.filter(due),...set.filter(c=>record(c)&&!due(c))];cursor=0;revealed=false;answered=false;if(!queue.length){shell(`<h1>${review?'You are caught up.':'No meaning cards here yet.'}</h1><p>${review?'There are no reviews due for this learner in the selected chapter.':'Import a prepared study pack to begin.'}</p>${button('Back to my library','home','','primary')}`);return;}study();}
function study(){const c=queue[cursor];if(!c){shell(`<section class="celebration"><p class="eyebrow">PRACTICE COMPLETE</p><h1>You reached the end of this set.</h1><p>Your answers are saved for ${esc(profiles.find(p=>p.id===profile)?.name)}. Come back for spaced reviews.</p>${button('My library','home','','primary')}</section>`);return;}view='study';const p=pages.find(p=>p.key===c.pageKey),parent=cards.find(x=>x.key===c.parentKey),children=cards.filter(x=>x.parentKey===c.key),picture=c.image||p.image;shell(`<div class="lesson-top">${button('← Save & return','home')}<span>Card ${cursor+1} of ${queue.length} · ${esc(c.chapter)}</span></div><article class="card-face"><p class="eyebrow">${revealed?'BUILD THE CONNECTION':'RECALL THE MEANING'}</p><p class="source-note">${parent?button(esc(parent.term)+' ↑','card',`data-key="${esc(parent.key)}"`):esc(c.chapter)}</p><h1>${esc(c.term)}</h1>${children.length?`<section class="child-entries"><h2>Explore inside this topic</h2><div class="actions">${children.map(x=>button(esc(x.term),'card',`data-key="${esc(x.key)}"`)).join('')}</div></section>`:''}${revealed?`<p class="definition">${esc(c.meaning)}</p><div class="notice"><b>Example</b><p>${esc(c.example)}</p></div><p style="margin-top:20px"><strong>Look at the picture:</strong> ${esc(c.notice)}</p><img class="study-image ${c.image?'item-image':''}" src="${picture}" alt="Source illustration for ${esc(c.term)}, PDF page ${p.number}">${c.sourceDefinition?`<details open><summary>Definition from the book</summary><p>${esc(c.sourceDefinition)}</p></details>`:''}${button('Open full source page','page',`data-key="${esc(p.key)}"`)}<p class="source-note">Study explanation is paraphrased. The scanned page above contains the book’s original definition and labels. PDF page ${p.number}.</p><div class="card-actions">${button('Read the explanation','speak')}${button('Check my understanding →','quiz','','primary')}</div>`:`<p>What does this word mean? Say it in your own words before turning the card over.</p><details><summary>Picture hint (includes the book’s labels)</summary><img class="study-image ${c.image?'item-image':''}" src="${picture}" alt="Labeled picture hint for ${esc(c.term)}"></details>${button('Show the meaning','reveal','','primary')}`}</article>`);}
function quiz(){view='quiz';answered=false;const c=queue[cursor],others=cards.filter(x=>x.chapter===c.chapter&&x.meaning!==c.meaning&&x.key!==c.key);options=[c,...others.sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell(`<article class="card-face"><p class="eyebrow">CHECK WITHOUT THE PICTURE</p><h1>What does “${esc(c.term)}” mean?</h1><p>Choose the explanation that fits.</p><div class="quiz-options">${options.map((x,i)=>button(esc(x.meaning),'answer',`data-index="${i}"`)).join('')}</div><div id="feedback" role="status"></div></article>`);}
async function answer(i){if(answered||busy||!options[i])return;busy=true;const c=queue[cursor],correct=options[i].key===c.key,id=key(c),value=recordAttempt(records.get(id),correct);try{await put('progress',[{id,value}]);records.set(id,value);answered=true;document.querySelectorAll('[data-action="answer"]').forEach(b=>{b.disabled=true;if(options[+b.dataset.index].key===c.key)b.classList.add('correct');});document.querySelector('#feedback').innerHTML=`<div class="feedback ${correct?'':'wrong'}"><strong>${correct?'That meaning fits.':'Let’s connect the meaning again.'}</strong><p>${esc(c.meaning)}</p><p>${esc(c.example)}</p>${correct?button('Next card →','next-card','','primary'):button('See the picture and try again','retry','','primary')}</div>`;}catch{announce('Your answer could not be saved. Free some browser storage and try again; existing progress is unchanged.');}finally{busy=false;}}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function importPack(file){if(!file||busy)return;busy=true;announce('Importing your study pack…');try{if(file.size>200000000)throw Error('This pack is too large. Use a pack smaller than 200 MB.');const p=validatePack(JSON.parse(await file.text()));await put('packs',[p]);packs=await all('packs');rebuild();home();announce(`Imported ${p.pages.length} pages and ${p.cards.length} meaning cards. Existing progress is preserved.`);}catch(e){announce(e instanceof SyntaxError?'Choose the prepared JSON study pack, not the PDF.':e.message||'Import failed. Existing data is unchanged.');}finally{busy=false;document.querySelector('#pack-file').value='';}}
async function restore(file){if(!file||busy)return;busy=true;try{if(file.size>20000000)throw Error('This progress file is too large.');const p=validateProgress(JSON.parse(await file.text())),merged=p.records.map(r=>({id:r.id,value:mergeProgress(records.get(r.id),r.value)}));await put('progress',merged);for(const r of merged)records.set(r.id,r.value);home();announce('Progress restored. More recent answers were preserved.');}catch(e){announce(e.message||'Could not restore progress.');}finally{busy=false;document.querySelector('#progress-file').value='';}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||busy)return;const a=b.dataset.action;
 if(a==='import')document.querySelector('#pack-file').click();
 else if(a==='restore')document.querySelector('#progress-file').click();
 else if(a==='backup')download('visual-library-progress.json',{format:'visual-library-progress',version:1,profiles:profiles.map(p=>({id:p.id,name:p.name})),records:[...records].map(([id,value])=>({id,value}))});
 else if(a==='home')home();
 else if(a==='browse')browse();
 else if(a==='lookup')lookup();
 else if(a==='word-search'){wordSearch=document.querySelector('#word-search').value.trim();lookupResults();}
 else if(a==='study')start();
 else if(a==='review')start(true);
 else if(a==='chapter-pages'){chapter=b.dataset.chapter;pageOffset=0;search='';browse();}
 else if(a==='chapter-study'){chapter=b.dataset.chapter;start();}
 else if(a==='search'){search=document.querySelector('#search').value.trim();pageOffset=0;pageResults();}
 else if(a==='next-pages'){pageOffset+=12;pageResults();}
 else if(a==='prev-pages'){pageOffset=Math.max(0,pageOffset-12);pageResults();}
 else if(a==='page'){const p=pages.find(p=>p.key===b.dataset.key);if(p)reader(p);}
 else if(a==='next-page'||a==='previous-page'){const p=pages[pages.indexOf(currentPage)+(a==='next-page'?1:-1)];if(p)reader(p);}
 else if(a==='zoom'){document.querySelector('.scan-zoom').classList.toggle('zoomed');b.textContent=b.textContent==='Zoom page'?'Fit page':'Zoom page';return;}
 else if(a==='card'){queue=[cards.find(c=>c.key===b.dataset.key)];cursor=0;revealed=false;study();}
 else if(a==='reveal'||a==='retry'){revealed=true;study();}
 else if(a==='quiz')quiz();
 else if(a==='answer'){await answer(+b.dataset.index);return;}
 else if(a==='next-card'){cursor++;revealed=false;answered=false;study();}
 else if(a==='speak'){if(!('speechSynthesis'in window)){announce('Read-aloud is unavailable in this browser.');return;}speechSynthesis.cancel();const c=queue[cursor],u=new SpeechSynthesisUtterance(`${c.term}. ${c.meaning} Example: ${c.example}`);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u);return;}
 else return;
 window.speechSynthesis?.cancel();if(!['import','restore','backup','search'].includes(a))window.scrollTo(0,0);
});
document.addEventListener('change',e=>{if(e.target.id==='pack-file')importPack(e.target.files[0]);else if(e.target.id==='progress-file')restore(e.target.files[0]);else if(e.target.id==='profile'){profile=e.target.value;home();}else if(e.target.id==='chapter'){chapter=e.target.value;pageOffset=0;pageResults();}});
document.addEventListener('keydown',e=>{if(e.target.id==='word-search'&&e.key==='Enter'){wordSearch=e.target.value.trim();lookupResults();}else if(e.target.id==='search'&&e.key==='Enter'){search=e.target.value.trim();pageOffset=0;pageResults();}});
window.addEventListener('storage',e=>{if(e.key==='linguistics-quest.family.v1'){readProfiles();home();}});
async function init(){try{readProfiles();db=await openDB();packs=await all('packs');records=new Map((await all('progress')).map(x=>[x.id,x.value]));rebuild();home();}catch(e){app.innerHTML=`<main><h1>Browser storage is unavailable.</h1><p>Your personal library needs browser storage. Open this page in a regular browser window with storage enabled, then reload.</p><p>${esc(e.message)}</p><a href="../">Return to Linguistics Quest</a></main>`;}}
init();
