import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {worlds,skillNames} from '../content.js';
import {fresh,question,rng} from '../engine.js';
import {decisions} from '../advanced-content.js';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../',import.meta.url));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const mime={'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json','.html':'text/html'};
const server=createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\/forex-quest\//,'');const file=path.resolve(root,name||'index.html');if(!file.startsWith(root)){res.writeHead(403).end();return;}const bytes=await readFile(file);res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(bytes);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}/forex-quest/`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const qa=process.env.QA_DIR||'/tmp/forex-qa';await mkdir(qa,{recursive:true});
try{
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.locator('#install-button').waitFor();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#install-button').click();await page.locator('#install-help[open]').waitFor();await page.getByRole('button',{name:'Got it'}).click();
await page.getByRole('button',{name:/Practice arcade/}).click();await page.locator('[data-skill="quote"]').click();await page.locator('#answer').fill('42');
await page.evaluate(()=>{window.calls=0;const event=new Event('beforeinstallprompt',{cancelable:true});event.prompt=async()=>{window.calls++;return {outcome:'accepted'};};event.userChoice=Promise.resolve({outcome:'accepted'});window.dispatchEvent(event);});
assert.equal(await page.locator('#answer').inputValue(),'42');
await page.getByRole('button',{name:'Install Forex Quest',exact:true}).click();await page.getByText(/Installation approved/).waitFor();assert.equal(await page.evaluate(()=>window.calls),1);
await page.locator('#install-button').click();assert.equal(await page.evaluate(()=>window.calls),1);await page.getByRole('button',{name:'Got it'}).click();
await page.evaluate(()=>{const e=new Event('beforeinstallprompt',{cancelable:true});e.prompt=async()=>({outcome:'dismissed'});window.dispatchEvent(e);});await page.locator('#install-button').click();await page.getByText(/Installation cancelled/).waitFor();
await page.evaluate(()=>{const e=new Event('beforeinstallprompt',{cancelable:true});e.prompt=async()=>{throw Error('test rejection');};window.dispatchEvent(e);});await page.locator('#install-button').click();await page.locator('#install-help[open]').waitFor();assert.ok(!(await page.locator('#install-button').isDisabled()));await page.getByRole('button',{name:'Got it'}).click();
await page.evaluate(()=>window.dispatchEvent(new Event('appinstalled')));assert.equal(await page.locator('#install-panel').count(),0);
await page.getByRole('button',{name:/Academy/}).click();assert.equal(await page.locator('#install-panel').count(),0);
const ios=await browser.newPage({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});
await ios.goto(base);await ios.getByRole('button',{name:'Add to Home Screen',exact:true}).click();await ios.getByText('Apple requires these steps;', {exact:false}).waitFor();await ios.screenshot({path:path.join(qa,'install-iphone.png'),fullPage:true});await ios.getByRole('button',{name:'Got it'}).click();await ios.screenshot({path:path.join(qa,'install-banner.png'),fullPage:false});
const installed=await browser.newPage();await installed.addInitScript(()=>Object.defineProperty(navigator,'standalone',{get:()=>true}));await installed.goto(base);assert.equal(await installed.locator('#install-panel').count(),0);
await ios.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener('controllerchange',r,{once:true}));});await ios.context().setOffline(true);await ios.reload();await ios.locator('#install-button').waitFor();await ios.locator('#install-button').click();await ios.locator('#install-help[open]').waitFor();
assert.deepEqual(errors,[]);console.log('PASS install UI: supported prompt invoked once, acceptance, dismissal, rejection, form preservation, installed detection, iPhone instructions, mobile layout and offline module. Native OS dialogs are simulated in this browser test.');
}finally{await browser.close();server.close();}
