import {readCloudState,writeCloudState} from './state-storage.js';
import {actOnRoom,roomView} from './rooms.js';
import {applyPush} from './protocol.js';
const allowed=new Set(['https://chiokebuckley-art.github.io','http://localhost:5187']);
const response=(status,body,origin)=>new Response(status===204?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,PUT,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,X-Player-Key'}});
export default {async fetch(request,env){const origin=request.headers.get('Origin')||'';if(origin&&!allowed.has(origin))return response(403,{error:'Origin not allowed.'},'');if(request.method==='OPTIONS')return response(204,null,origin);if(new URL(request.url).pathname==='/health')return response(200,{service:'science-quest-sync',version:1},origin);const isRoom=new URL(request.url).pathname==='/v1/room';if(!isRoom&&new URL(request.url).pathname!=='/v1/sync')return response(404,{error:'Not found.'},origin);const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token||''))return response(401,{error:'A private sync key is required.'},origin);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)),id=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');const binding=isRoom?env.ROOMS:env.SAVES;const object=binding.get(binding.idFromName(id));const forwarded=new Request(request);forwarded.headers.delete('Authorization');forwarded.headers.delete('X-Actor');if(isRoom){const playerKey=request.headers.get('X-Player-Key');if(!/^[a-f0-9]{64}$/.test(playerKey||''))return response(401,{error:'Private player key required.'},origin);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(playerKey));forwarded.headers.set('X-Actor',[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join(''));forwarded.headers.delete('X-Player-Key');}return object.fetch(forwarded);}};
export class ScienceSave {constructor(ctx){this.ctx=ctx;}async fetch(request){const origin=request.headers.get('Origin')||'';try{if(request.method==='GET'){const state=await this.ctx.storage.transaction(readCloudState);return response(200,state?{revision:state.revision,snapshot:state.snapshot,events:state.events,history:state.history}:{revision:0,snapshot:null,events:[],history:[]},origin);}if(request.method==='DELETE'){await this.ctx.storage.deleteAll();return response(200,{deleted:true},origin);}if(request.method!=='PUT')return response(405,{error:'Method not allowed.'},origin);const text=await request.text();if(new TextEncoder().encode(text).length>2*1024*1024)return response(413,{error:'Sync request exceeds 2 MB.'},origin);const body=JSON.parse(text);const result=await this.ctx.storage.transaction(async storage=>{const result=await applyPush(await readCloudState(storage),body);if(result.status===200&&!result.body.replayed)await writeCloudState(storage,result.state);return result;});return response(result.status,result.body,origin);}catch(error){return response(400,{error:error.message},origin);}}}

export class ScienceRoom {constructor(ctx){this.ctx=ctx;}async alarm(){await this.ctx.storage.deleteAll();}async fetch(request){const origin=request.headers.get('Origin')||'',actor=request.headers.get('X-Actor');try{if(request.method==='GET'){const room=await this.ctx.storage.get('room');if(!room||room.expiresAt<=Date.now())return response(404,{error:'Room missing or expired.'},origin);return response(200,roomView(room,actor),origin);}if(request.method==='DELETE'){const room=await this.ctx.storage.get('room');if(!room||room.players.find(p=>p.credential===actor)?.id!==room.host)return response(403,{error:'Only the host can close this room.'},origin);await this.ctx.storage.deleteAll();return response(200,{closed:true},origin);}if(request.method!=='POST')return response(405,{error:'Method not allowed.'},origin);const text=await request.text();if(new TextEncoder().encode(text).length>4096)return response(413,{error:'Room action too large.'},origin);const action=JSON.parse(text);const result=await this.ctx.storage.transaction(async storage=>{const result=actOnRoom(await storage.get('room'),actor,action);if(!result.replayed){await storage.put('room',result.room);await storage.setAlarm(result.room.expiresAt);}return result;});return response(200,result.view,origin);}catch(e){return response(400,{error:e.message},origin);}}}
