/**
 * Kit 01: ELEGOO "UNO R3 Super Starter Kit".
 * One card per printed tile on the lid's 7×5 component chart (rows A–E, columns 1–7).
 * Every identity comes from the printed lid label ('label-confirmed').
 * `simulated` parts are on the virtual circuit mat; `later` parts wait in the drawer for later lesson packs.
 */
import type { KitComponent } from './types';

const ALL_MISSIONS = ['m01', 'm02', 'm03', 'm04', 'm05', 'm06', 'm07', 'm08', 'm09', 'm10', 'boss'];

export const KIT01_COMPONENTS: KitComponent[] = [
  /* ---------------- row A ---------------- */
  {
    id: 'uno',
    tile: 'A1',
    printed: 'UNO R3 Controller Board 1PC',
    name: 'UNO R3 microcontroller board',
    aliases: ['Arduino Uno compatible', 'ATmega328P', 'microcontroller', 'the brain'],
    role: 'controller',
    count: '1',
    what: 'A tiny computer that reads sensors, runs your code and switches outputs on and off.',
    principle:
      'The ATmega328P chip runs your program one instruction at a time, millions of times per second. Each digital pin is either HIGH (5 V) or LOW (0 V). The analog pins A0–A5 measure a voltage from 0 to 5 V and turn it into a number from 0 to 1023. PWM pins (marked ~) flick on and off very fast, so an LED or motor gets an in-between average.',
    io: {
      input: 'Voltages on its input pins',
      change: 'Your code decides what to do',
      output: '5 V or 0 V on its output pins',
    },
    pins: [
      'D0 (RX)', 'D1 (TX)', 'D2', '~D3', 'D4', '~D5', '~D6', 'D7', 'D8', '~D9', '~D10', '~D11', 'D12', 'D13 (L LED)',
      'A0', 'A1', 'A2', 'A3', 'A4', 'A5',
      '5V', '3.3V', 'GND', 'VIN', 'RESET', 'AREF', 'IOREF',
    ],
    safety:
      'Keep each pin at about 20 mA or less, so always put a resistor in series with an LED. Never join 5V straight to GND, and unplug USB before changing wires; the USB fuse trips at about 500 mA.',
    uses: ['Home-made robots and alarms', 'Weather stations that log readings', 'Science-fair measuring gadgets'],
    missions: [...ALL_MISSIONS],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'lcd1602',
    tile: 'A2',
    printed: 'LCD1602 Module (with pin header) 1PC',
    name: '16×2 character LCD screen',
    aliases: ['LCD1602', 'HD44780 display', 'character LCD'],
    role: 'output',
    count: '1',
    what: 'A screen that shows two lines of 16 letters or numbers each.',
    principle:
      'Each character is a small grid of 5×8 dots filled with liquid crystal. A voltage across a dot twists the crystals so they block light, and the dot looks dark. A controller chip on the back remembers the text and drives every dot; the UNO just sends it letters over several data wires. A potentiometer on V0 sets the contrast.',
    io: {
      input: 'Letters sent from the UNO on data pins',
      change: 'Controller chip darkens the right dots',
      output: 'Text on two lines of 16 characters',
    },
    pins: ['VSS', 'VDD', 'V0', 'RS', 'RW', 'E', 'D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'A', 'K'],
    safety:
      'Hold it by the edges because the glass can crack, and power it from 5 V only. If the screen shows nothing or a row of blocks, turn the contrast potentiometer slowly.',
    uses: ['Microwave and printer displays', 'Showing sensor readings on a project', 'Simple menus on 3D printers'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'proto-shield',
    tile: 'A3',
    printed: 'Prototype Expansion Module 1PC',
    name: 'Prototype shield',
    aliases: ['proto shield', 'expansion board', 'mini breadboard shield'],
    role: 'support',
    count: '1',
    what: 'A board that stacks on top of the UNO and gives you a small breadboard right above it.',
    principle:
      'Its long header pins push into the UNO sockets, so every UNO pin is copied up to the top of the shield. Copper tracks carry each signal to rows of holes and a small breadboard where you can build. Nothing on it thinks; it just joins wires neatly.',
    io: {
      input: 'UNO pins through the stacking headers',
      change: 'Copper tracks carry each signal up',
      output: 'Same pins, ready beside the mini breadboard',
    },
    pins: ['Stacking headers (all UNO pins)', '5V', 'GND'],
    safety:
      'Unplug USB and line up every pin before pressing the shield down. Check that no bare wire underneath touches the metal USB socket on the UNO.',
    uses: ['Compact projects that fit in a box', 'Keeping a build together while you carry it', 'Quick test circuits'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'power-module',
    tile: 'A4',
    printed: 'Power Supply Module 1PC',
    name: 'Breadboard power supply module',
    aliases: ['MB102 power module', 'breadboard power supply'],
    role: 'power',
    count: '1',
    what: 'A small board that plugs onto the breadboard rails and feeds them 5 V or 3.3 V.',
    principle:
      'It takes power from a barrel jack or USB and uses voltage regulator chips to hold the output steady. A regulator works like an automatic valve: it drops the extra voltage as heat so the rails stay at 5 V or 3.3 V. Jumpers pick which voltage each rail gets.',
    io: {
      input: 'Power from a jack or USB',
      change: 'Regulators hold the voltage steady',
      output: '5 V or 3.3 V on the breadboard rails',
    },
    pins: ['DC jack', 'USB', 'ON/OFF switch', '5V / 3.3V jumpers', '+ rail pins', '− rail pins'],
    safety:
      'Set both jumpers before switching on, and never let it feed a rail that the UNO is also feeding. Its regulators get warm, so do not touch them while it runs.',
    uses: ['Powering motors separately from the UNO', 'Running 3.3 V parts', 'Stand-alone breadboard circuits'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'uln2003',
    tile: 'A5',
    printed: 'ULN2003 Stepper Motor Driver Module 1PC',
    name: 'Stepper motor driver board',
    aliases: ['ULN2003 driver', 'Darlington array board'],
    role: 'driver',
    count: '1',
    what: 'A driver board that lets four UNO pins switch the coils of the stepper motor.',
    principle:
      'The ULN2003 chip holds seven Darlington pairs: two transistors linked so a tiny input current controls a much bigger one. The UNO sends small signals to IN1–IN4, and the chip lets motor current flow through each coil in turn. Built-in diodes soak up the voltage spike when a coil switches off, and four LEDs show which coil is on.',
    io: {
      input: 'Small signals on IN1–IN4',
      change: 'Darlington transistors switch the coil current',
      output: 'Coils energised in turn, LEDs blink',
    },
    pins: ['IN1', 'IN2', 'IN3', 'IN4', '+ (5–12V)', '− (GND)', 'Motor socket'],
    safety:
      'Power the motor side from a separate 5 V supply that shares GND with the UNO, not from a UNO pin. Switch the power off before plugging in or removing the motor.',
    uses: ['Camera sliders', 'Automatic pet feeders', 'Small drawing machines'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'stepper',
    tile: 'A6',
    printed: 'Stepper Motor 1PC',
    name: 'Stepper motor',
    aliases: ['28BYJ-48', 'geared stepper motor'],
    role: 'output',
    count: '1',
    what: 'A motor that turns in small, exact steps instead of spinning freely.',
    principle:
      'Inside are four coils around a magnetic rotor. When a coil gets current it becomes an electromagnet and pulls the rotor a little way round. Switching the coils on in order pulls it round step by step, and gears make each step tiny. Reverse the order and it turns the other way.',
    io: {
      input: 'Coils switched on in order by the driver',
      change: 'Each coil pulls the magnet one step',
      output: 'Shaft turns an exact angle',
    },
    pins: ['Blue', 'Pink', 'Yellow', 'Orange', 'Red (+5V)'],
    safety:
      'Always drive it through the ULN2003 board, never straight from UNO pins. It gets warm if left powered while standing still, so turn the coils off when it is not moving.',
    uses: ['Air-conditioner vents', '3D printers and plotters', 'Clock hands and gauges'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'servo',
    tile: 'A7',
    printed: 'Servo Motor SG90 1PC',
    name: 'Micro servo motor',
    aliases: ['SG90', 'servo', 'hobby servo'],
    role: 'output',
    count: '1',
    what: 'A small motor that turns to an exact angle between 0° and 180° and holds it there.',
    principle:
      'Inside are a DC motor, gears and a potentiometer on the output shaft. The UNO sends a pulse every 20 ms: about 1 ms long means 0°, and about 2 ms long means 180°. A small circuit compares the pulse with the potentiometer reading and drives the motor until they match.',
    io: {
      input: 'A 1–2 ms pulse every 20 ms',
      change: 'Compares the pulse with the shaft position',
      output: 'Arm turns to the matching angle',
    },
    pins: ['Brown (GND)', 'Red (+5V)', 'Orange (signal)'],
    safety:
      'Red goes to 5V and brown to GND; only the orange wire goes to a signal pin, which can never power the motor. Do not twist the arm by hand because the plastic gears strip easily, and use a separate supply for bigger loads.',
    uses: ['Steering in model cars', 'Robot arms and grippers', 'Automatic door latches'],
    missions: ['m01', 'm09', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },

  /* ---------------- row B ---------------- */
  {
    id: 'relay',
    tile: 'B1',
    printed: '5V Relay 1PC',
    name: '5 V relay',
    aliases: ['relay', 'electromagnetic switch'],
    role: 'driver',
    count: '1',
    what: 'A switch worked by an electromagnet, so a small signal can turn a separate circuit on or off.',
    principle:
      'Current through the coil turns it into an electromagnet. The magnet pulls a metal lever that moves the COM contact from NC (normally closed) to NO (normally open), with a click. The coil circuit and the switched circuit never touch electrically. The coil needs more current than a pin can give, so a transistor drives it.',
    io: {
      input: '5 V across the coil',
      change: 'Electromagnet pulls the switch lever',
      output: 'COM connects to NO instead of NC',
    },
    pins: ['Coil', 'Coil', 'COM', 'NO', 'NC'],
    safety:
      'In this course switch only low-voltage loads, never mains power from a wall socket. Drive the coil through a transistor with a diode across it, not straight from a pin.',
    uses: ['Garden watering pumps', 'Car headlights and horns', 'Smart-home switches'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'ir-receiver',
    tile: 'B2',
    printed: 'IR Receiver Module 1PC',
    name: 'Infrared receiver',
    aliases: ['IR receiver', 'IR sensor', '38 kHz receiver'],
    role: 'input',
    count: '1',
    what: 'A sensor that picks up the invisible infrared flashes from a remote control.',
    principle:
      'A photodiode inside turns infrared light into a tiny current. A built-in filter only passes light that flickers at 38 kHz, so sunlight and lamps are mostly ignored. While it sees those bursts its signal pin goes LOW, so the UNO can time the pattern and read it as a code.',
    io: {
      input: '38 kHz infrared bursts',
      change: 'Photodiode and filter pick out the pattern',
      output: 'LOW and HIGH pulses on the signal pin',
    },
    pins: ['Signal', '+', '−'],
    safety:
      'Check the pin order printed on the module before powering it, because swapping + and − can damage it. Bright sunlight can swamp it, so test indoors.',
    uses: ['TV remotes', 'Air conditioners', 'Remote-controlled toys'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'joystick',
    tile: 'B3',
    printed: 'Joystick Module 1PC',
    name: 'Joystick module',
    aliases: ['thumb joystick', 'analog joystick', 'XY joystick'],
    role: 'input',
    count: '1',
    what: 'A thumb stick that tells the UNO how far it is pushed left–right and up–down, plus a click button.',
    principle:
      'Under the stick are two potentiometers, one for X and one for Y. Moving the stick turns their wipers, so VRx and VRy give voltages from 0 to 5 V, about 2.5 V when centred. Pressing the stick down closes a switch that joins SW to GND.',
    io: {
      input: 'Your thumb moves or presses the stick',
      change: 'Two potentiometers act as voltage dividers',
      output: 'VRx and VRy voltages, SW press',
    },
    pins: ['GND', '+5V', 'VRx', 'VRy', 'SW'],
    safety:
      'Use INPUT_PULLUP on the SW pin so the button does not float. Push the stick gently; it is plastic.',
    uses: ['Game controllers', 'Steering robots', 'Camera pan-and-tilt heads'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'dht11',
    tile: 'B4',
    printed: 'DHT11 Temperature and Humidity Module 1PC',
    name: 'Temperature and humidity sensor',
    aliases: ['DHT11', 'humidity sensor', 'weather sensor'],
    role: 'input',
    count: '1',
    what: 'A sensor that measures air temperature and how much water vapour is in the air.',
    principle:
      'A tiny thermistor senses temperature, and a layer between two electrodes changes its resistance as it soaks up water vapour. A small chip inside measures both and turns them into numbers: 0–50 °C (±2 °C) and 20–90 % humidity (±5 %). It sends them over one data wire with its own timing code, where the length of each HIGH pulse means 0 or 1.',
    io: {
      input: 'Air temperature and moisture',
      change: 'Chip measures and encodes both',
      output: 'Timed data pulses on the S pin',
    },
    pins: ['S (data)', '+ (VCC, middle)', '− (GND)'],
    safety:
      'Check the pin order before powering it; with + and − swapped it gets hot. Read it no faster than about once a second or it gives errors.',
    uses: ['Home weather stations', 'Greenhouse monitors', 'Room comfort displays'],
    missions: ['m07'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'ultrasonic',
    tile: 'B5',
    printed: 'Ultrasonic Sensor 1PC',
    name: 'Ultrasonic distance sensor',
    aliases: ['HC-SR04', 'sonar', 'distance sensor'],
    role: 'input',
    count: '1',
    what: 'A sensor that measures distance by timing how long a sound echo takes to come back.',
    principle:
      'A 10 µs pulse on Trig makes one side send 8 cycles of 40 kHz sound, too high for people to hear. The sound bounces off an object and the other side listens for the echo, while Echo stays HIGH for the round-trip time. Distance = 0.0343 (cm per microsecond) × time ÷ 2 (out and back), because sound travels about 343 m/s and goes there and back. It works from about 2 cm to 400 cm.',
    io: {
      input: 'Trig pulse from the UNO',
      change: 'Sends 8 bursts of 40 kHz sound, times the echo',
      output: 'Echo pin HIGH for the round-trip time',
    },
    pins: ['VCC', 'Trig', 'Echo', 'GND'],
    safety:
      'Power it from 5 V and check that VCC and GND are not swapped. Soft or slanted surfaces scatter the sound, so test with a flat object first.',
    uses: ['Car parking sensors', 'Robots that avoid obstacles', 'Water tank level gauges'],
    missions: ['m01', 'm10', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'fan-motor',
    tile: 'B6',
    printed: 'Fan Blade and 3-6V Motor 1PC',
    name: 'DC motor with fan blade',
    aliases: ['DC motor', 'hobby motor', '3-6V motor'],
    role: 'output',
    count: '1',
    what: 'A small motor that spins a fan blade when current flows through it.',
    principle:
      'Current in the coils inside makes electromagnets that push against permanent magnets, so the shaft turns. Brushes swap the current direction as it spins, to keep it turning the same way. Swap the two wires and it spins the other way. It needs far more current than a pin can give.',
    io: {
      input: 'Current through the motor wires',
      change: 'Coil magnetism pushes against fixed magnets',
      output: 'Shaft and fan blade spin',
    },
    pins: ['Terminal 1', 'Terminal 2'],
    safety:
      'Never power it from a UNO pin; use a transistor or the L293D, its own supply and a protection diode. Keep fingers and hair clear of the spinning blade.',
    uses: ['Cooling fans', 'Toy cars', 'Small water pumps'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'active-buzzer',
    tile: 'B7',
    printed: 'Active Buzzer 1PC',
    name: 'Active buzzer',
    aliases: ['beeper', 'self-oscillating buzzer'],
    role: 'output',
    count: '1',
    what: 'A buzzer that beeps on its own as soon as it gets steady power.',
    principle:
      'Inside is a tiny oscillator circuit that switches itself on and off thousands of times a second. That drives a thin disc that flexes back and forth and pushes the air, making one fixed tone. So a plain steady HIGH of about 3.5–5.5 V is all it needs.',
    io: {
      input: 'Steady HIGH (about 5 V)',
      change: 'Built-in oscillator shakes the disc',
      output: 'One fixed beep',
    },
    pins: ['+ (long leg)', '− (short leg)'],
    safety:
      'The longer leg, or the side marked +, goes to the positive side. Peel off the sticker on top before use.',
    uses: ['Alarm clocks', 'Microwave and washing-machine beeps', 'Warning signals on machines'],
    missions: ['m08', 'm10', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },

  /* ---------------- row C ---------------- */
  {
    id: 'passive-buzzer',
    tile: 'C1',
    printed: 'Passive Buzzer 1PC',
    name: 'Passive buzzer',
    aliases: ['piezo speaker', 'sounder'],
    role: 'output',
    count: '1',
    what: 'A buzzer that plays whatever pitch you choose, as long as you send it a changing signal.',
    principle:
      'It has no oscillator inside, just a disc that flexes each time the voltage changes. Your code switches the pin on and off; tone(pin, 440) does it 440 times a second, which is the note A. Faster switching gives a higher pitch, while steady DC alone only makes a click.',
    io: {
      input: 'A square wave from tone()',
      change: 'Disc flexes each time the voltage changes',
      output: 'A note whose pitch matches the frequency',
    },
    pins: ['+', '−'],
    safety:
      'It looks like the active buzzer, so check which one you have: the passive one usually shows a green circuit board underneath. Do not hold it right next to your ear while it plays.',
    uses: ['Music-box tunes', 'Game sound effects', 'Doorbells that play a melody'],
    missions: ['m08'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'shift-register',
    tile: 'C2',
    printed: '74HC595 IC 1PC',
    name: 'Shift register chip',
    aliases: ['74HC595', 'serial-to-parallel chip'],
    role: 'driver',
    count: '1',
    what: 'A chip that turns 3 UNO pins into 8 outputs.',
    principle:
      'The UNO sends 8 bits one at a time on the data pin, with a clock pulse for each bit. Every clock pulse shifts the bits one place along a row of 8 memory cells. A pulse on the latch pin then copies all 8 to the outputs Q0–Q7 at once.',
    io: {
      input: 'Bits on DS, one clock pulse each',
      change: 'Bits shift along 8 cells, then latch',
      output: 'Outputs Q0–Q7 all set at once',
    },
    pins: [
      'Q0', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q7′ (serial out)',
      'DS (data)', 'SHCP (clock)', 'STCP (latch)', 'OE', 'MR', 'VCC', 'GND',
    ],
    safety:
      'The notch or dot marks pin 1, so line the chip up before pushing it across the breadboard gap. Each output still needs its own resistor when it drives an LED.',
    uses: ['LED light bars', 'Driving 7-segment displays', 'Saving pins on busy projects'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'l293d',
    tile: 'C3',
    printed: 'L293D 1PC',
    name: 'Motor driver chip',
    aliases: ['L293D', 'H-bridge', 'dual H-bridge'],
    role: 'driver',
    count: '1',
    what: 'A chip that lets the UNO drive two DC motors, forwards and backwards.',
    principle:
      'Inside are two H-bridges: four switches arranged like the letter H around each motor. Closing one diagonal pair sends current one way through the motor, and closing the other pair sends it the other way. The UNO only sends small logic signals, while the motor current comes from a separate supply on VCC2. The enable pins turn each side on, and PWM on them sets the speed.',
    io: {
      input: 'Logic signals on the IN and EN pins',
      change: 'H-bridge switches steer the current',
      output: 'Motor spins forwards, backwards or stops',
    },
    pins: [
      'EN1,2', 'IN1', 'IN2', 'OUT1', 'OUT2', 'IN3', 'IN4', 'OUT3', 'OUT4', 'EN3,4',
      'VCC1 (logic 5V)', 'VCC2 (motor)', 'GND',
    ],
    safety:
      'Line up the notch before inserting it, and give the motors their own supply with a shared GND. The chip gets hot under load, so let it cool before touching it.',
    uses: ['Two-wheeled robot cars', 'Motorised model doors', 'Conveyor belt models'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'button',
    tile: 'C4',
    printed: 'Button 5PCS',
    name: 'Push button',
    aliases: ['tactile switch', 'momentary switch', 'push switch'],
    role: 'input',
    count: '5',
    what: 'A small switch that connects a circuit only while you press it.',
    principle:
      'It has four legs, and the two legs on each side of the long axis are always joined inside. Pressing pushes a springy metal dome down so the two sides join. An input pin needs a pull-up or pull-down resistor, or INPUT_PULLUP, so it reads a clear HIGH or LOW instead of floating.',
    io: {
      input: 'Your finger presses the button',
      change: 'Metal dome joins the two sides',
      output: 'Input pin reads HIGH or LOW',
    },
    pins: ['Leg 1 (side A)', 'Leg 2 (side A)', 'Leg 3 (side B)', 'Leg 4 (side B)'],
    safety:
      'Place it across the middle gap of the breadboard so its sides are not joined by accident. Never wire a button straight between 5V and GND; add a resistor or use INPUT_PULLUP.',
    uses: ['Keyboards and game controllers', 'Doorbells', 'Start buttons on machines'],
    missions: ['m01', 'm04', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'potentiometer',
    tile: 'C5',
    printed: 'Potentiometer 10k 1PC',
    name: 'Potentiometer (turning knob)',
    aliases: ['pot', '10k pot', 'variable resistor'],
    role: 'input',
    count: '1',
    what: 'A knob whose middle leg gives any voltage between 0 V and 5 V as you turn it.',
    principle:
      'Inside is a curved strip of resistive material, 10 kΩ from end to end. The two outer legs connect to the ends, and the middle leg is a wiper that slides along the strip. With 5V and GND on the ends, the wiper acts as a voltage divider, so analogRead gives 0 to 1023.',
    io: {
      input: 'You turn the knob',
      change: 'Wiper slides along the resistive track',
      output: 'Middle leg voltage from 0 to 5 V',
    },
    pins: ['End 1', 'Wiper (middle)', 'End 2'],
    safety:
      'Put 5V and GND on the two outer legs only; with 5V on the wiper, turning to one end would short the supply. Turn it gently at its end stops.',
    uses: ['Volume knobs', 'Light dimmers', 'Joystick axes'],
    missions: ['m05'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'seg1',
    tile: 'C6',
    printed: '1 Digit 7-Segment Display 1PC',
    name: 'Single-digit 7-segment display',
    aliases: ['7-segment LED', 'digit display'],
    role: 'output',
    count: '1',
    what: 'A display that shows one number from 0 to 9 using seven light bars and a dot.',
    principle:
      'Each bar, a to g, is its own LED, and dp is the decimal point. On this kit all the cathodes are joined to a common pin that goes to GND. Lighting the right mix of bars draws a digit; for example, every bar except g makes 0.',
    io: {
      input: 'HIGH on chosen segment pins',
      change: 'Those LED segments conduct and glow',
      output: 'A digit 0–9 appears',
    },
    pins: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'dp', 'COM (−)', 'COM (−)'],
    safety:
      'Each segment is an LED, so each needs its own current-limiting resistor, such as 220 Ω. The common pins go to GND on this common-cathode display.',
    uses: ['Kitchen timers', 'Scoreboards', 'Lift floor indicators'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'seg4',
    tile: 'C7',
    printed: '4 Digit 7-Segment Display 1PC',
    name: '4-digit 7-segment display',
    aliases: ['4-digit LED display', 'clock display'],
    role: 'output',
    count: '1',
    what: 'A display that shows four digits, like a clock or a timer.',
    principle:
      'The four digits share the same a–g and dp wires. Each digit has its own common-cathode pin, D1–D4, that switches it on. The UNO lights one digit at a time, very fast, and your eyes blend them together; this trick is called multiplexing.',
    io: {
      input: 'Segment pattern plus one digit pin LOW',
      change: 'Digits light one after another, very fast',
      output: 'Four digits seem lit at once',
    },
    pins: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'dp', 'D1', 'D2', 'D3', 'D4'],
    safety:
      'Use a current-limiting resistor on each segment line, a–g and dp. Keep your code refreshing it, or only one digit stays lit.',
    uses: ['Microwave clocks', 'Stopwatches', 'Scoreboards'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },

  /* ---------------- row D ---------------- */
  {
    id: 'tilt-switch',
    tile: 'D1',
    printed: 'Tilt Ball Switch 1PC',
    name: 'Tilt ball switch',
    aliases: ['tilt sensor', 'ball switch'],
    role: 'input',
    count: '1',
    what: 'A switch that is closed when it stands upright and opens when you tip it over.',
    principle:
      'Inside a small metal can is a loose metal ball. When the switch stands upright, gravity rolls the ball onto the two contacts and joins them. Tilt it and the ball rolls away, breaking the connection.',
    io: {
      input: 'You tilt or shake it',
      change: 'Metal ball rolls on or off the contacts',
      output: 'Circuit closed or open',
    },
    pins: ['Lead 1', 'Lead 2'],
    safety:
      'Use INPUT_PULLUP or a resistor so the pin does not float when the switch is open. The ball bounces, so read it a few times before trusting a change.',
    uses: ['Alarms that notice when something is moved', 'Toys that react when tipped', 'Heaters that switch off if knocked over'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'remote',
    tile: 'D2',
    printed: 'Remote Control 1PC',
    name: 'Infrared remote control',
    aliases: ['IR remote', 'remote'],
    role: 'input',
    count: '1',
    what: 'A handheld remote that sends a different invisible code for each button.',
    principle:
      'Pressing a button makes a chip flash the infrared LED at the front. The light flickers 38,000 times a second in bursts, and the pattern of long and short gaps spells out a code for that button. The IR receiver on your breadboard picks it up and the UNO decodes it.',
    io: {
      input: 'You press a button',
      change: 'Chip flashes the IR LED in a coded pattern',
      output: 'Coded 38 kHz infrared bursts',
    },
    pins: [],
    safety:
      'It runs on a coin cell; pull out the plastic tab before first use. Keep coin cells away from small children, because swallowing one is very dangerous.',
    uses: ['TV and music remotes', 'Remote-controlled robots', 'Presentation clickers'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'breadboard',
    tile: 'D3',
    printed: '830 Tie-Points Breadboard 1PC',
    name: 'Solderless breadboard',
    aliases: ['breadboard', 'protoboard', '830-point board'],
    role: 'support',
    count: '1',
    what: 'A board full of holes that lets you build circuits without soldering.',
    principle:
      'Under the holes are metal spring clips that grip a wire. In each numbered column, holes a–e are joined, and holes f–j are joined; the middle gap keeps the two halves apart. The long rails along the edges, + (red) and − (blue), run the length of the board for power and ground.',
    io: {
      input: 'Leads pushed into the holes',
      change: 'Spring clips join the holes in each strip',
      output: 'Parts connected with no soldering',
    },
    pins: ['Columns 1–63, holes a–e', 'Columns 1–63, holes f–j', '+ rails (red)', '− rails (blue)'],
    safety:
      'Push leads in straight and gently so the clips do not bend. Check that no two leads share a strip by accident, because that can make a short circuit.',
    uses: ['Testing a circuit before soldering it', 'School and lab experiments', 'Trying out a design idea quickly'],
    missions: [...ALL_MISSIONS],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'usb-cable',
    tile: 'D4',
    printed: 'USB Cable 1PC',
    name: 'USB cable (A to B)',
    aliases: ['USB A-B cable', 'printer cable', 'programming cable'],
    role: 'power',
    count: '1',
    what: 'The cable that connects the UNO to a computer for power and for uploading code.',
    principle:
      'Two of its wires carry 5 V and ground from the computer, which powers the UNO. The other two carry data, so your code travels to the board and messages come back to the Serial Monitor. A resettable fuse on the UNO cuts the power if more than about 500 mA flows.',
    io: {
      input: 'Computer USB port',
      change: 'Carries 5 V power and data',
      output: 'UNO powered and ready for code',
    },
    pins: [],
    safety:
      'In this course every build is powered only by this cable, at 5 V. Unplug it before changing wires, and if the board goes dead when you plug in, unplug at once and look for a short.',
    uses: ['Uploading programs', 'Powering the UNO from a laptop', 'Sending readings to the Serial Monitor'],
    missions: ['m02', 'm03'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'fm-wires',
    tile: 'D5',
    printed: 'Female-to-Male Dupont Wire 10PCS',
    name: 'Female-to-male jumper wires',
    aliases: ['Dupont wires', 'F-M jumpers'],
    role: 'support',
    count: '10',
    what: 'Wires with a socket on one end and a pin on the other, for joining module pins to the breadboard.',
    principle:
      'Each is a copper wire inside plastic insulation. The female end slides over a pin on a module, and the male end pushes into the breadboard or the UNO header. Copper conducts very easily, so the voltage is almost the same at both ends.',
    io: {
      input: 'Signal or power at a module pin',
      change: 'Copper carries it along the wire',
      output: 'Same signal at the breadboard',
    },
    pins: ['Female socket end', 'Male pin end'],
    safety:
      'Pull on the plastic housing, not the wire, when unplugging. Use colours sensibly, such as red for 5V and black for GND, so mistakes are easy to spot.',
    uses: ['Connecting sensor modules', 'Extending a servo lead', 'Linking a module to the UNO header'],
    missions: ['m07', 'm09', 'm10'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'jumpers',
    tile: 'D6',
    printed: 'Breadboard Jumper Wire 65PCS',
    name: 'Breadboard jumper wires',
    aliases: ['male-to-male jumpers', 'jumper wires', 'hook-up wires'],
    role: 'support',
    count: '65',
    what: 'Short wires with a pin on both ends that link holes on the breadboard and the UNO.',
    principle:
      'Each wire is copper inside plastic insulation, with a stiff pin at each end. Copper has very low resistance, so it joins two points almost as if they were one. Different lengths and colours help keep a build tidy.',
    io: {
      input: 'Voltage at one end',
      change: 'Low-resistance copper carries the current',
      output: 'Same voltage at the other end',
    },
    pins: ['Male pin end', 'Male pin end'],
    safety:
      'Unplug USB before adding wires, and trace each one when you finish. A wire from 5V straight to GND is a short circuit.',
    uses: ['Linking UNO pins to the breadboard', 'Connecting the power rails', 'Joining parts in a prototype'],
    missions: ['m02', 'm03', 'm04', 'm05', 'm06', 'm07', 'm08', 'm09', 'm10'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'battery-9v',
    tile: 'D7',
    printed: '9V Battery with Snap-on Connector Clip 1PC',
    name: '9 V battery and snap clip',
    aliases: ['9V battery', 'battery snap', 'PP3 battery'],
    role: 'power',
    count: '1',
    what: 'A battery and clip that can power the UNO through its barrel jack, away from a computer.',
    principle:
      'A battery turns stored chemical energy into electrical energy, with about 9 V between its terminals. The snap-on clip has a red wire for + and a black wire for −. Through the barrel jack, the UNO regulator lowers the 9 V to a steady 5 V.',
    io: {
      input: 'Chemical energy in the battery',
      change: 'A chemical reaction pushes current',
      output: 'About 9 V for the UNO barrel jack',
    },
    pins: ['Red (+)', 'Black (−)'],
    safety:
      'Never connect 9 V to the breadboard 5V rail or to any UNO pin; it can destroy parts. Keep the battery away from coins and keys, because a short makes it hot.',
    uses: ['Running projects away from a computer', 'Smoke alarms', 'Portable gadgets'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },

  /* ---------------- row E ---------------- */
  {
    id: 'resistor',
    tile: 'E1',
    printed: 'Resistor 120PCS',
    name: 'Resistors',
    aliases: ['resistor pack', 'current limiter'],
    role: 'support',
    count: '120',
    what: 'Parts that limit how much current flows, so LEDs and pins stay safe.',
    principle:
      'A resistor makes it harder for current to flow and turns the energy it takes into a little heat. Current = voltage ÷ resistance, so a bigger resistance means a smaller current. The coloured bands give the value, and a resistor has no polarity. This pack has 10 Ω, 100 Ω, 220 Ω, 330 Ω, 1 kΩ, 2 kΩ, 5.1 kΩ, 10 kΩ, 100 kΩ and 1 MΩ.',
    io: {
      input: 'Voltage across it',
      change: 'Resists the flow, makes a little heat',
      output: 'A smaller, safer current',
    },
    pins: ['Lead 1', 'Lead 2'],
    safety:
      'Check the colour bands before you use one; 10 Ω instead of 220 Ω lets far too much current through an LED. A resistor that gets hot is a sign something is wrong.',
    uses: ['Protecting LEDs', 'Pull-up and pull-down resistors', 'Voltage dividers for sensors'],
    missions: ['m01', 'm03', 'm04', 'm06', 'm07'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'led',
    tile: 'E2',
    printed: 'LED 25PCS',
    name: 'Light-emitting diodes',
    aliases: ['LEDs', 'LED lights'],
    role: 'output',
    count: '25',
    what: 'Tiny lights that glow when current flows through them the right way.',
    principle:
      'An LED is a diode: current flows from the long leg (anode, +) to the short leg (cathode, −), and not the other way. As current crosses the junction inside, energy is given off as light of one colour. Red, yellow and green need about 1.8–2.2 V, blue and white about 3 V. A series resistor, such as 220 Ω from 5 V, keeps the current near 10–20 mA.',
    io: {
      input: 'Current from anode to cathode',
      change: 'Energy released as light at the junction',
      output: 'A coloured glow',
    },
    pins: ['Anode (+, long leg)', 'Cathode (−, short leg, flat edge)'],
    safety:
      'Always put a resistor in series; without one the LED and the pin can burn out. If it stays dark, check whether it is in backwards.',
    uses: ['Indicator lights', 'Traffic lights', 'Screens and lamps'],
    missions: ['m01', 'm03', 'm04', 'm05', 'm06', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'rgb-led',
    tile: 'E3',
    printed: 'RGB LED 2PCS',
    name: 'RGB LED',
    aliases: ['tricolour LED', 'colour-mixing LED'],
    role: 'output',
    count: '2',
    what: 'One LED package with red, green and blue inside, so it can mix many colours.',
    principle:
      'Three tiny LEDs share one clear case and one common cathode, the longest leg. PWM sets how bright each colour is, and your eye blends them into one colour. Red plus green looks yellow, and all three together look white.',
    io: {
      input: 'PWM on the R, G and B legs',
      change: 'Three LEDs glow at different strengths',
      output: 'One mixed colour',
    },
    pins: ['R', 'Common cathode (−, longest leg)', 'G', 'B'],
    safety:
      'Each colour leg needs its own resistor, such as 220 Ω. The longest leg is the common cathode and goes to GND.',
    uses: ['Mood lamps', 'Status lights on chargers and routers', 'Colour-changing decorations'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
  {
    id: 'thermistor',
    tile: 'E4',
    printed: 'Thermistor 1PC',
    name: 'Thermistor',
    aliases: ['NTC thermistor', 'temperature resistor', '10k NTC'],
    role: 'input',
    count: '1',
    what: 'A resistor whose resistance changes with temperature, so it can work as a thermometer.',
    principle:
      'It is made of a material whose resistance falls as it warms up; this is called NTC, a negative temperature coefficient. At 25 °C it measures 10 kΩ. In a voltage divider with a fixed 10 kΩ resistor, the middle voltage changes with temperature, and analogRead can measure it.',
    io: {
      input: 'Heat from the air or your fingers',
      change: 'Resistance falls as temperature rises',
      output: 'Changing voltage at the divider middle',
    },
    pins: ['Lead 1', 'Lead 2'],
    safety:
      'It has no polarity, but always use it with a fixed resistor in a divider, never straight across 5V and GND. Warm it with your fingers, never a flame or a hot drink.',
    uses: ['Digital thermometers', 'Battery chargers that watch for overheating', '3D printer temperature sensors'],
    missions: ['m07'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'diode',
    tile: 'E5',
    printed: 'Diode Rectifier 2PCS',
    name: 'Rectifier diode',
    aliases: ['1N4007', 'diode', 'one-way valve'],
    role: 'support',
    count: '2',
    what: 'A one-way valve for electric current.',
    principle:
      'A diode lets current flow from its anode to its cathode, the end with the stripe, but blocks it the other way. While it conducts, it uses up about 0.7 V. That makes it useful for stopping reversed power and for soaking up the voltage spike a motor or relay coil makes when it switches off.',
    io: {
      input: 'Current arriving at either end',
      change: 'Conducts one way, blocks the other',
      output: 'Current flows only anode to cathode',
    },
    pins: ['Anode', 'Cathode (stripe)'],
    safety:
      'The stripe marks the cathode, so check its direction before plugging it in. Across a motor or relay coil, the stripe faces the positive supply.',
    uses: ['Reverse-power protection', 'Protecting transistors from motor spikes', 'Turning AC into DC in power adapters'],
    missions: ['m01'],
    review: 'label-confirmed',
  },
  {
    id: 'photoresistor',
    tile: 'E6',
    printed: 'Photoresistor (Photocell) 2PCS',
    name: 'Light sensor (photoresistor)',
    aliases: ['LDR', 'photocell', 'light-dependent resistor'],
    role: 'input',
    count: '2',
    what: 'A resistor whose resistance drops when more light shines on it.',
    principle:
      'Its wavy track is made of cadmium sulfide (CdS), which frees more charges to carry current when light hits it. In dim light it measures tens of kΩ, and in bright light it can fall to around 1 kΩ. In a divider with a 10 kΩ resistor, the middle voltage changes with the light, and analogRead measures it.',
    io: {
      input: 'Light falling on the sensor',
      change: 'More light frees more charges, resistance drops',
      output: 'Changing voltage at the divider middle',
    },
    pins: ['Lead 1', 'Lead 2'],
    safety:
      'It has no polarity, but always use it with a fixed resistor in a divider. It contains cadmium, so wash your hands after handling it and recycle it as electronic waste.',
    uses: ['Street lights that switch on at dusk', 'Night lights', 'Light meters'],
    missions: ['m06', 'boss'],
    review: 'label-confirmed',
    simulated: true,
  },
  {
    id: 'npn',
    tile: 'E7',
    printed: 'NPN Transistor PN2222 2PCS',
    name: 'NPN transistor',
    aliases: ['PN2222', 'transistor', 'electronic switch'],
    role: 'driver',
    count: '2',
    what: 'An electronic switch that lets a small current control a much bigger one.',
    principle:
      'It has three legs: emitter, base and collector. A small current into the base lets a much larger current flow from collector to emitter, up to about 600 mA. With no base current it stays off. That is how a UNO pin can switch a motor or a relay coil.',
    io: {
      input: 'Small current into the base',
      change: 'Base current opens the collector–emitter path',
      output: 'Large current flows through the load',
    },
    pins: ['E (emitter)', 'B (base)', 'C (collector)'],
    safety:
      'Always put a resistor, such as 1 kΩ, between the UNO pin and the base. With the flat face toward you, the legs are E, B and C from left to right.',
    uses: ['Switching motors and relays', 'Amplifiers in radios', 'Driving LED strips'],
    missions: [],
    review: 'label-confirmed',
    later: true,
  },
];
