import type { Difficulty, Question } from '../types';
import type { Rng } from '../rng';
import type { Generator } from './context';
import { pictureQuestion, approx, num } from './picture';
import { lab, labn } from '../label';

/**
 * Probability lab: from ratios to your own predictive model, in nine stages.
 *  algebra     — odds ↔ probability, proportions, rearranging p = wins ÷ games
 *  count       — counting principle, permutations, combinations
 *  sample      — sample spaces (dice, coins, cards), complements
 *  events      — independent × , mutually exclusive +, dependent draws
 *  conditional — P(A | B) from a two-way table
 *  bayes       — Bayes with natural frequencies (a tree of 1000 cases)
 *  center      — mean, variance, standard deviation
 *  sampling    — law of large numbers, standard error, margin of error
 *  hypothesis  — z-test for a proportion, significance at 1.96
 *  binomial    — exactly k of n
 *  poisson     — k events when the average is λ
 *  normal      — z-scores and the normal table; t when the sample is small
 *  regress     — linear prediction, slope from two points, logistic p = 1 / (1 + e^-z)
 *  vectors     — dot products and ratings; Elo expected score and update
 *  markov      — two-state chains, random walks, Monte Carlo estimates
 *  decision    — expected value, Kelly stake, risk of ruin
 */
export type ProbKind = 'algebra' | 'count' | 'sample' | 'events' | 'conditional' | 'bayes' | 'center' | 'sampling' | 'hypothesis' | 'binomial' | 'poisson' | 'normal' | 'regress' | 'vectors' | 'markov' | 'decision' | 'all';
export const PROB_KINDS: { id: ProbKind; label: string; short: string; desc: string; stage: number }[] = [
  { id: 'all', label: 'Mixed probability', short: 'Mixed', desc: 'Every stage, shuffled.', stage: 0 },
  { id: 'algebra', label: '1 · Odds and ratios', short: 'Odds', desc: 'Odds a:b against → p = b ÷ (a + b). Solve proportions. Rearrange p = wins ÷ games.', stage: 1 },
  { id: 'count', label: '2 · Counting', short: 'Counting', desc: 'Multiply choices. nPr when order matters, nCr when it does not.', stage: 2 },
  { id: 'sample', label: '3 · Sample spaces', short: 'Sample space', desc: 'List every equally likely outcome; count the ones you want.', stage: 3 },
  { id: 'events', label: '3 · Combining events', short: 'Events', desc: 'Independent: multiply. Mutually exclusive: add. Without replacement: the pool shrinks.', stage: 3 },
  { id: 'conditional', label: '3 · Conditional', short: 'Conditional', desc: 'P(A | B) = P(A and B) ÷ P(B): read it off the table row.', stage: 3 },
  { id: 'bayes', label: '3 · Bayes', short: 'Bayes', desc: 'Start with 1000 cases, split by the base rate, then by the test. Posterior = true hits ÷ all hits.', stage: 3 },
  { id: 'center', label: '4 · Mean and spread', short: 'Mean/SD', desc: 'Mean, variance (average squared gap), standard deviation (its root).', stage: 4 },
  { id: 'sampling', label: '4 · Sampling error', short: 'Sampling', desc: 'More trials, less noise: standard error = √(p(1−p) ÷ n).', stage: 4 },
  { id: 'hypothesis', label: '4 · Hypothesis test', short: 'z-test', desc: 'z = (p̂ − p₀) ÷ SE. Beyond ±1.96 is significant at 5 %.', stage: 4 },
  { id: 'binomial', label: '5 · Binomial', short: 'Binomial', desc: 'P(k of n) = C(n,k) pᵏ (1−p)ⁿ⁻ᵏ.', stage: 5 },
  { id: 'poisson', label: '5 · Poisson', short: 'Poisson', desc: 'P(k) = e^−λ λᵏ ÷ k!. Goals, arrivals, faults.', stage: 5 },
  { id: 'normal', label: '5 · Normal and t', short: 'Normal', desc: 'z = (x − μ) ÷ σ, then the table. Small samples use t.', stage: 5 },
  { id: 'regress', label: '6 · Regression', short: 'Regression', desc: 'ŷ = a + b x. Logistic turns a score into a win probability.', stage: 6 },
  { id: 'vectors', label: '7 · Vectors and Elo', short: 'Elo', desc: 'Rating = weights · features. Elo: E = 1 ÷ (1 + 10^((R_b − R_a) ÷ 400)).', stage: 7 },
  { id: 'markov', label: '8 · Chains and Monte Carlo', short: 'Markov', desc: 'Next state depends only on this one. Simulate many times and count.', stage: 8 },
  { id: 'decision', label: '9 · EV, Kelly, ruin', short: 'Decision', desc: 'EV = Σ p × payoff. Kelly f = (bp − q) ÷ b. Ruin = (q ÷ p)^bankroll.', stage: 9 },
];

const T = 'Probability';
const mk = (skill: string, sub: string, o: Parameters<typeof pictureQuestion>[4]) => pictureQuestion('prob', T, skill, sub, o);
const fact = (n: number): number => (n <= 1 ? 1 : n * fact(n - 1));
export const nCr = (n: number, r: number) => Math.round(fact(n) / (fact(r) * fact(n - r)));
export const nPr = (n: number, r: number) => Math.round(fact(n) / fact(n - r));
const pct = (p: number) => Math.round(p * 1000) / 10;
/** A percent with its label: lp(12.5, 'chance') = '12.5% (chance)'. */
const lp = (v: number, label: string, places = 1) => lab(`${num(v, places)}%`, label);
/** A probability shown as a labelled percent: lpc(0.25, 'draw') = '25% (draw)'. */
const lpc = (p: number, label: string) => lab(`${pct(p)}%`, label);
const PLACES = ['first', 'second', 'third', 'fourth', 'fifth'];
/** 8 (first place choices) × 7 (second place choices) × … */
const placeChoices = (n: number, r: number) => Array.from({ length: r }, (_, i) => lab(n - i, `${PLACES[i] ?? 'next'} place choices`)).join(' × ');
/** Standard normal CDF (Abramowitz–Stegun 7.1.26). */
export function phi(z: number): number { const t = 1 / (1 + 0.2316419 * Math.abs(z)); const d = 0.3989423 * Math.exp((-z * z) / 2); const p = 1 - d * t * (0.3193815 + t * (-0.3565638 + t * (1.781478 + t * (-1.821256 + t * 1.330274)))); return z >= 0 ? p : 1 - p; }
export const elo = (ra: number, rb: number) => 1 / (1 + 10 ** ((rb - ra) / 400));
export const logistic = (z: number) => 1 / (1 + Math.exp(-z));

/* ---------- 1 algebra ---------- */
export function algebraQuestion(mode: 'oddsToP' | 'pToOdds' | 'proportion' | 'rearrange', a: number, b: number, d: Difficulty, rng: Rng, skill = 'prob.algebra'): Question {
  const thing = rng.pick(['the home team', 'the favourite', 'your horse', 'the challenger']);
  if (mode === 'oddsToP') { const p = b / (a + b); const ans = approx(p * 100, 1); return mk(skill, '1 · Odds and ratios', { prompt: `Odds of ${a}:${b} against ${thing} winning. What is the probability of a win, as a percent?`, expression: `${b} ÷ (${a} + ${b}) × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Odds against a:b means b wins for every a losses. Probability = wins ÷ all outcomes.', steps: [`Odds ${a}:${b} against: ${a} losses for every ${b} wins, ${a + b} outcomes in all.`, `p = ${labn(b, 'win', 'wins')} ÷ ${lab(a + b, 'outcomes')} = ${lab(num(p, 3), 'probability of a win')} = ${lp(p * 100, 'chance of a win')}.`, `Odds compare wins to losses; probability compares wins to everything.`], visual: { type: 'oddsbar', a, b } }); }
  if (mode === 'pToOdds') { const p = b / (a + b); return mk(skill, '1 · Odds and ratios', { prompt: `${thing[0].toUpperCase() + thing.slice(1)} wins with probability ${num(p * 100, 1)} %. Written as odds against, N:${b}, what is N?`, expression: `losses : wins = ? : ${b}`, answer: a, unit: '', difficulty: d, hint: 'Out of a + b outcomes, b are wins; the rest are losses.', steps: [`${lp(p * 100, 'chance of a win')} = ${labn(b, 'win', 'wins')} ÷ ${lab(a + b, 'outcomes')}, so ${b} wins in ${a + b} outcomes.`, `Losses = ${lab(a + b, 'outcomes')} − ${labn(b, 'win', 'wins')} = ${labn(a, 'loss', 'losses')}. Odds against = ${a}:${b}.`], visual: { type: 'oddsbar', a, b } }); }
  if (mode === 'proportion') { const k = rng.int(2, 6); return mk(skill, '1 · Odds and ratios', { prompt: `A team scores ${a} goals in ${b} matches at a steady rate. At that rate, how many goals in ${b * k} matches?`, expression: `${a} ÷ ${b} × ${b * k} = ?`, answer: a * k, unit: 'goals', difficulty: d, hint: 'Set up goals ÷ matches = goals ÷ matches and cross-multiply.', steps: [`Rate = ${lab(a, 'goals')} ÷ ${lab(b, 'matches')} = ${lab(num(a / b, 3), 'goals per match')}.`, `${lab(num(a / b, 3), 'goals per match')} × ${lab(b * k, 'matches')} = ${lab(a * k, 'goals')}. Or: ${b * k} ÷ ${b} = ${lab(k, 'times the matches')}, so ${k} times the goals.`], visual: { type: 'card', title: 'Proportion', lines: [`${a} goals / ${b} matches`, `? goals / ${b * k} matches`] } }); }
  const p = a / 100; const games = b; const wins = Math.round(p * games);
  return mk(skill, '1 · Odds and ratios', { prompt: `Win rate p = wins ÷ games. A player has p = ${num(p, 2)} over ${games} games. Rearrange for wins: how many did they win?`, expression: `wins = p × games = ?`, answer: wins, unit: 'wins', difficulty: d, hint: 'Multiply both sides by games.', steps: [`p = wins ÷ games. Multiply both sides by games: wins = p × games.`, `${lab(num(p, 2), 'win rate')} × ${lab(games, 'games')} = ${lab(wins, 'wins')}.`, `Every formula in this lab can be rearranged the same way: undo what was done to the unknown.`], visual: { type: 'card', title: 'Rearrange', lines: ['p = wins ÷ games', 'wins = p × games', `p = ${num(p, 2)}, games = ${games}`] } });
}

/* ---------- 2 counting ---------- */
export function countQuestion(mode: 'multiply' | 'perm' | 'comb', n: number, r: number, d: Difficulty, rng: Rng, skill = 'prob.count'): Question {
  if (mode === 'multiply') { const things = rng.pick([['shirts', 'trousers', 'hats'], ['starters', 'mains', 'desserts'], ['openings', 'midgames', 'endings']]); const c = [n, r, rng.int(2, 4)]; return mk(skill, '2 · Counting', { prompt: `${c[0]} ${things[0]}, ${c[1]} ${things[1]} and ${c[2]} ${things[2]}. How many different combinations of one of each?`, expression: `${c[0]} × ${c[1]} × ${c[2]} = ?`, answer: c[0] * c[1] * c[2], unit: '', difficulty: d, hint: 'Independent choices multiply.', steps: [`Each ${things[0].slice(0, -1)} can go with every ${things[1].slice(0, -1)}: ${lab(c[0], things[0])} × ${lab(c[1], things[1])} = ${lab(c[0] * c[1], 'pairs')}.`, `Each pair with every ${things[2].slice(0, -1)}: ${lab(c[0] * c[1], 'pairs')} × ${lab(c[2], things[2])} = ${lab(c[0] * c[1] * c[2], 'combinations')}.`, `The counting principle: multiply the number of options at each step.`], visual: { type: 'counttree', levels: c } }); }
  if (mode === 'perm') return mk(skill, '2 · Counting', { prompt: `${n} runners. How many different ways can gold, silver and bronze be awarded? (order matters)`.replace('gold, silver and bronze', r === 3 ? 'gold, silver and bronze' : `the first ${r} places`), expression: `${n}P${r} = ${Array.from({ length: r }, (_, i) => n - i).join(' × ')} = ?`, answer: nPr(n, r), unit: '', difficulty: d, hint: 'Fill the places one at a time; each place has one fewer runner to choose from.', steps: [`First place: ${n} choices. Second: ${n - 1}. ${r > 2 ? `Third: ${n - 2}.` : ''}`, `${placeChoices(n, r)} = ${lab(nPr(n, r), 'orderings')}.`, `Permutation: order matters, so every different order counts separately.`], visual: { type: 'card', title: 'Permutation', lines: [`${n} runners, ${r} places`, `${Array.from({ length: r }, (_, i) => n - i).join(' × ')}`] } });
  return mk(skill, '2 · Counting', { prompt: `Choose ${r} players from a squad of ${n} to start. Order does not matter. How many different line-ups?`, expression: `${n}C${r} = ${n}P${r} ÷ ${r}! = ?`, answer: nCr(n, r), unit: '', difficulty: d, hint: 'Count the orderings, then divide out the orders of the chosen group.', steps: [`Orderings: ${placeChoices(n, r)} = ${lab(nPr(n, r), 'orderings')}.`, `Each group of ${r} was counted ${r}! = ${fact(r)} times, once for each of its own orders. ${lab(nPr(n, r), 'orderings')} ÷ ${lab(fact(r), 'orders of one group')} = ${lab(nCr(n, r), 'line-ups')}.`, `Combination: order does not matter, so divide by r!.`], visual: { type: 'card', title: 'Combination', lines: [`${n} choose ${r}`, `${nPr(n, r)} orderings ÷ ${fact(r)}`] } });
}

/* ---------- 3 sample spaces ---------- */
export function sampleQuestion(mode: 'dice' | 'coins' | 'complement', k: number, d: Difficulty, rng: Rng, skill = 'prob.sample'): Question {
  if (mode === 'dice') { let ways = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === k) ways++; const ans = approx((ways / 36) * 100, 1); return mk(skill, '3 · Sample spaces', { prompt: `Two dice are rolled. What is the probability the total is ${k}, as a percent?`, expression: `ways ÷ 36 × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'The grid shows all 36 equally likely rolls; count the cells that add to the total.', steps: [`Sample space: 6 (faces on die one) × 6 (faces on die two) = 36 (equally likely pairs).`, `Pairs adding to ${k}: ${labn(ways, 'way', 'ways')}.`, `${labn(ways, 'way', 'ways')} ÷ ${lab(36, 'possible pairs')} = ${lab(num(ways / 36, 3), 'probability')} = ${lp((ways / 36) * 100, 'chance')}.`], visual: { type: 'dicegrid', total: k } }); }
  if (mode === 'coins') { const n = k; const ways = nCr(n, Math.floor(n / 2)); const total = 2 ** n; const heads = Math.floor(n / 2); const ans = approx((ways / total) * 100, 1); return mk(skill, '3 · Sample spaces', { prompt: `${n} coins are tossed. What is the probability of exactly ${heads} heads, as a percent?`, expression: `C(${n},${heads}) ÷ 2^${n} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Count outcomes: 2 per coin, multiplied. Count the ones with the right number of heads.', steps: [`Each coin has 2 (faces), so the outcomes multiply: 2^${n} = ${lab(total, 'equally likely outcomes')}.`, `Ways to pick which ${heads} coins show heads: C(${n},${heads}) = ${lab(ways, 'ways')}.`, `${lab(ways, 'ways')} ÷ ${lab(total, 'outcomes')} = ${lp((ways / total) * 100, 'chance')}.`], visual: { type: 'counttree', levels: Array(Math.min(n, 4)).fill(2) } }); }
  const p = k / 100; const ans = approx((1 - p) * 100, 1); const thing = rng.pick(['rain', 'a delay', 'a fault', 'an upset']);
  return mk(skill, '3 · Sample spaces', { prompt: `The chance of ${thing} is ${k} %. What is the chance of no ${thing}?`, expression: `100 − ${k} = ? %`, ...ans, unit: '%', difficulty: d, hint: 'Something either happens or it does not: the two add to 100 %.', steps: [`The complement of an event is everything else. P(not A) = 1 − P(A).`, `100% (certain) − ${lab(`${k}%`, `chance of ${thing}`)} = ${lab(`${100 - k}%`, `chance of no ${thing.replace(/^an? /, '')}`)}.`, `"At least one" problems are usually easiest through the complement: 1 − P(none).`], visual: { type: 'oddsbar', a: 100 - k, b: k } });
}

/* ---------- 3 events ---------- */
export function eventsQuestion(mode: 'independent' | 'exclusive' | 'dependent' | 'atleast', p1: number, p2: number, d: Difficulty, _rng: Rng, skill = 'prob.events'): Question {
  if (mode === 'independent') { const ans = approx(p1 * p2 * 100, 1); return mk(skill, '3 · Combining events', { prompt: `Two independent matches. Team A wins theirs with probability ${pct(p1)} %, Team B theirs with ${pct(p2)} %. Probability both win, as a percent?`, expression: `${num(p1, 2)} × ${num(p2, 2)} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Independent events: multiply.', steps: [`Independent means one result does not change the other's chances.`, `P(both) = ${lab(num(p1, 2), 'chance A wins')} × ${lab(num(p2, 2), 'chance B wins')} = ${num(p1 * p2, 4)} = ${lp(p1 * p2 * 100, 'chance both win')}.`, `Both is always less likely than either alone.`], visual: { type: 'tree', root: 'A', branches: [{ label: 'A wins', p: p1, children: [{ label: 'B wins', p: p2 }, { label: 'B loses', p: 1 - p2 }] }, { label: 'A loses', p: 1 - p1 }] } }); }
  if (mode === 'exclusive') { const ans = approx((p1 + p2) * 100, 1); return mk(skill, '3 · Combining events', { prompt: `A match ends in a home win with probability ${pct(p1)} % or a draw with ${pct(p2)} %. Probability the away side does not win (home win or draw)?`, expression: `${num(p1, 2)} + ${num(p2, 2)} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Outcomes that cannot both happen: add.', steps: [`Home win and draw are mutually exclusive: the match has one result.`, `P(home or draw) = ${lpc(p1, 'home win')} + ${lpc(p2, 'draw')} = ${lp((p1 + p2) * 100, 'away side does not win')}.`, `If events could overlap you would subtract the overlap: P(A) + P(B) − P(A and B).`], visual: { type: 'oddsbar', a: Math.round((1 - p1 - p2) * 100), b: Math.round((p1 + p2) * 100) } }); }
  if (mode === 'dependent') { const red = Math.round(p1 * 10); const total = 10; const p = (red / total) * ((red - 1) / (total - 1)); const ans = approx(p * 100, 1); return mk(skill, '3 · Combining events', { prompt: `A bag has ${red} red and ${total - red} blue tokens. Two are drawn without replacement. Probability both are red?`, expression: `${red}/${total} × ${red - 1}/${total - 1} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'After the first draw there is one fewer token, and one fewer red.', steps: [`First red: ${lab(red, 'red tokens')} ÷ ${lab(total, 'tokens')}.`, `Second red, given the first was red: ${lab(red - 1, 'red tokens left')} ÷ ${lab(total - 1, 'tokens left')}. The pool shrank.`, `${lab(`${red}/${total}`, 'first red')} × ${lab(`${red - 1}/${total - 1}`, 'second red')} = ${num(p, 4)} = ${lp(p * 100, 'chance both red')}.`], visual: { type: 'tree', root: 'draw', branches: [{ label: `red ${red}/${total}`, p: red / total, children: [{ label: `red ${red - 1}/${total - 1}`, p: (red - 1) / (total - 1) }, { label: `blue ${total - red}/${total - 1}`, p: (total - red) / (total - 1) }] }, { label: `blue ${total - red}/${total}`, p: (total - red) / total }] } }); }
  const n = Math.round(p2); const p = 1 - (1 - p1) ** n; const ans = approx(p * 100, 1);
  return mk(skill, '3 · Combining events', { prompt: `Each shot scores with probability ${pct(p1)} %, independently. In ${n} shots, what is the probability of at least one goal?`, expression: `1 − (1 − ${num(p1, 2)})^${n} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'At least one = 1 − none.', steps: [`P(miss) = 1 (certain) − ${lab(num(p1, 2), 'chance to score')} = ${lab(num(1 - p1, 2), 'chance to miss')}.`, `All ${n} miss: ${num(1 - p1, 2)}^${n} = ${lab(num((1 - p1) ** n, 4), 'chance all miss')}.`, `P(at least one) = 1 − ${lab(num((1 - p1) ** n, 4), 'chance all miss')} = ${lp(p * 100, 'chance of at least one goal')}.`], visual: { type: 'bars', title: `P(at least one) as shots increase, p = ${num(p1, 2)}`, values: Array.from({ length: Math.min(8, n + 2) }, (_, i) => ({ label: String(i + 1), v: 1 - (1 - p1) ** (i + 1) })), highlight: n - 1 } });
}

/* ---------- 3 conditional ---------- */
export function conditionalQuestion(table: { rows: [string, string]; cols: [string, string]; n: [[number, number], [number, number]] }, ask: 'given' | 'joint' | 'marginal', d: Difficulty, skill = 'prob.conditional'): Question {
  const [[a, b], [c, e]] = table.n; const total = a + b + c + e;
  if (ask === 'given') { const p = a / (a + b); const ans = approx(p * 100, 1); return mk(skill, '3 · Conditional', { prompt: `From the table: given ${table.rows[0]}, what is the probability of ${table.cols[0]}? (P(${table.cols[0]} | ${table.rows[0]}))`, expression: `${a} ÷ (${a} + ${b}) × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: '"Given" narrows the world to one row. Divide within that row.', steps: [`Given ${table.rows[0]}: look only at that row: ${lab(a + b, `${table.rows[0]} games`)}.`, `Of those, ${table.cols[0]}: ${lab(a, `${table.rows[0]} and ${table.cols[0]}`)}. ${lab(a, `${table.rows[0]} and ${table.cols[0]}`)} ÷ ${lab(a + b, `${table.rows[0]} games`)} = ${lp(p * 100, `chance of ${table.cols[0]} given ${table.rows[0]}`)}.`, `P(A | B) = P(A and B) ÷ P(B) = (${a}/${total}) ÷ (${a + b}/${total}), the same thing.`], visual: { type: 'table2', ...table, highlightRow: 0 } }); }
  if (ask === 'joint') { const p = a / total; const ans = approx(p * 100, 1); return mk(skill, '3 · Conditional', { prompt: `From the table: probability of ${table.rows[0]} AND ${table.cols[0]}, out of everyone?`, expression: `${a} ÷ ${total} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Joint probability: one cell over the grand total.', steps: [`The cell for ${table.rows[0]} and ${table.cols[0]} holds ${lab(a, `${table.rows[0]} and ${table.cols[0]}`)}.`, `${lab(a, `${table.rows[0]} and ${table.cols[0]}`)} ÷ ${lab(total, 'everyone')} = ${lp(p * 100, `chance of ${table.rows[0]} and ${table.cols[0]}`)}.`, `Compare with the conditional: same cell, different denominator.`], visual: { type: 'table2', ...table } }); }
  const p = (a + c) / total; const ans = approx(p * 100, 1);
  return mk(skill, '3 · Conditional', { prompt: `From the table: probability of ${table.cols[0]} overall (any row)?`, expression: `(${a} + ${c}) ÷ ${total} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Marginal probability: a column total over the grand total.', steps: [`${table.cols[0]} column total: ${a} + ${c} = ${lab(a + c, 'column total')}.`, `${lab(a + c, 'column total')} ÷ ${lab(total, 'everyone')} = ${lp(p * 100, `chance of ${table.cols[0]}`)}.`], visual: { type: 'table2', ...table, highlightCol: 0 } });
}

/* ---------- 3 bayes ---------- */
export function bayesQuestion(base: number, sens: number, spec: number, d: Difficulty, rng: Rng, skill = 'prob.bayes'): Question {
  const thing = rng.pick([['a fault', 'the sensor flags it'], ['an injury', 'the scan is positive'], ['a fake', 'the checker flags it']]);
  const N = 1000; const have = Math.round(N * base); const tp = Math.round(have * sens); const fp = Math.round((N - have) * (1 - spec));
  const post = tp / (tp + fp); const ans = approx(post * 100, 1);
  return mk(skill, '3 · Bayes', { prompt: `${thing[0][0].toUpperCase() + thing[0].slice(1)} is present in ${pct(base)} % of cases. When it is present, ${thing[1]} ${pct(sens)} % of the time; when it is absent, it still flags ${pct(1 - spec)} % of the time. ${thing[1][0].toUpperCase() + thing[1].slice(1)}. Probability ${thing[0]} is really present?`, expression: 'true flags ÷ all flags = ? %', ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Imagine 1000 cases. How many truly have it and flag? How many do not have it but flag anyway?', steps: [`Of 1000 cases, ${lab(have, `with ${thing[0]}`)} and ${lab(N - have, `without ${thing[0]}`)}.`, `Flags: ${lpc(sens, 'flag rate when present')} of ${have} = ${lab(tp, 'true flags')}. ${lpc(1 - spec, 'flag rate when absent')} of ${N - have} = ${lab(fp, 'false flags')}.`, `All flags: ${tp} + ${fp} = ${lab(tp + fp, 'all flags')}. ${lab(tp, 'true flags')} ÷ ${lab(tp + fp, 'all flags')} = ${lp(post * 100, `chance of ${thing[0]}`)}.`, `Bayes: posterior = P(flag | present) P(present) ÷ P(flag). The tree is the same arithmetic with counts.`], visual: { type: 'tree', root: '1000 cases', branches: [{ label: `present ${have}`, p: base, children: [{ label: `flag ${tp}`, p: sens }, { label: `no flag ${have - tp}`, p: 1 - sens }] }, { label: `absent ${N - have}`, p: 1 - base, children: [{ label: `flag ${fp}`, p: 1 - spec }, { label: `no flag ${N - have - fp}`, p: spec }] }] } });
}

/* ---------- 4 center ---------- */
export function centerQuestion(data: number[], ask: 'mean' | 'variance' | 'sd', d: Difficulty, rng: Rng, skill = 'prob.center'): Question {
  const n = data.length; const mean = data.reduce((a, b) => a + b, 0) / n; const varP = data.reduce((a, x) => a + (x - mean) ** 2, 0) / n; const sd = Math.sqrt(varP);
  const thing = rng.pick(['points per game', 'goals per match', 'minutes per lap', 'faults per shift']);
  const list = data.join(', ');
  if (ask === 'mean') { const ans = approx(mean, 2); const sum = data.reduce((a, b) => a + b, 0); return mk(skill, '4 · Mean and spread', { prompt: `${thing[0].toUpperCase() + thing.slice(1)}: ${list}. What is the mean?`, expression: `sum ÷ ${n} = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Add them, divide by how many.', steps: [`Sum = ${lab(sum, 'sum of the values')}.`, `Mean = ${lab(sum, 'sum')} ÷ ${lab(n, 'values')} = ${lab(num(mean, 2), `mean ${thing}`)}.`], visual: { type: 'dots', values: data, mean } }); }
  if (ask === 'variance') { const ans = approx(varP, 2); const ss = data.reduce((a, x) => a + (x - mean) ** 2, 0); return mk(skill, '4 · Mean and spread', { prompt: `${thing[0].toUpperCase() + thing.slice(1)}: ${list}. Mean = ${num(mean, 2)}. What is the variance (average squared distance from the mean)?`, expression: `Σ(x − mean)² ÷ ${n} = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Gap from the mean, squared, averaged.', steps: [`Gaps from the mean: ${data.map((x) => num(x - mean, 2)).join(', ')}.`, `Squared: ${data.map((x) => num((x - mean) ** 2, 2)).join(', ')}. Sum ${lab(num(ss, 2), 'sum of squared gaps')}.`, `${lab(num(ss, 2), 'sum of squared gaps')} ÷ ${lab(n, 'values')} = ${lab(num(varP, 2), 'variance')}. Population variance: a sample estimate divides by n − 1.`], visual: { type: 'dots', values: data, mean } }); }
  const ans = approx(sd, 2);
  return mk(skill, '4 · Mean and spread', { prompt: `${thing[0].toUpperCase() + thing.slice(1)}: ${list}. Variance = ${num(varP, 2)}. What is the standard deviation?`, expression: `√${num(varP, 2)} = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Square-root the variance to get back to the original units.', steps: [`SD = √variance = √${num(varP, 2)} = ${lab(num(sd, 2), 'standard deviation')}.`, `About two thirds of typical data sits within one SD of the mean: ${lab(num(mean - sd, 2), 'mean minus one SD')} to ${lab(num(mean + sd, 2), 'mean plus one SD')}.`], visual: { type: 'dots', values: data, mean, sd } });
}

/* ---------- 4 sampling ---------- */
export function samplingQuestion(mode: 'expected' | 'se' | 'margin', p: number, n: number, d: Difficulty, skill = 'prob.sampling'): Question {
  const se = Math.sqrt((p * (1 - p)) / n);
  if (mode === 'expected') return mk(skill, '4 · Sampling error', { prompt: `A true win rate of ${pct(p)} %. Over ${n} games, how many wins do you expect on average?`, expression: `${num(p, 2)} × ${n} = ?`, answer: Math.round(p * n * 10) / 10, unit: 'wins', difficulty: d, decimal: true, hint: 'Expected count = p × n.', steps: [`Expected wins = ${lab(num(p, 2), 'win rate')} × ${lab(n, 'games')} = ${lab(num(p * n, 1), 'expected wins')}.`, `The law of large numbers: the observed rate settles toward ${pct(p)} % as n grows, but any single stretch can wander.`], visual: { type: 'lln', p, n } });
  if (mode === 'se') { const ans = approx(se * 100, 2); return mk(skill, '4 · Sampling error', { prompt: `True rate ${pct(p)} %, sample of ${n}. What is the standard error of the sample proportion, in percentage points?`, expression: `√(p(1−p) ÷ n) × 100 = ?`, ...ans, unit: 'pts', difficulty: d, decimal: true, hint: 'SE = √(p(1 − p) ÷ n).', steps: [`p(1 − p) = ${lab(num(p, 2), 'true rate')} × ${lab(num(1 - p, 2), 'one minus the rate')} = ${num(p * (1 - p), 4)}.`, `${num(p * (1 - p), 4)} ÷ ${lab(n, 'sample size')} = ${num((p * (1 - p)) / n, 6)}; √ = ${lab(num(se, 4), 'standard error')} = ${num(se * 100, 2)} points.`, `Four times the sample halves the error.`], visual: { type: 'lln', p, n } }); }
  const m = 1.96 * se; const ans = approx(m * 100, 1);
  return mk(skill, '4 · Sampling error', { prompt: `A poll of ${n} finds ${pct(p)} %. What is the 95 % margin of error, in percentage points? (1.96 × SE)`, expression: `1.96 × √(p(1−p) ÷ n) × 100 = ?`, ...ans, unit: 'pts', difficulty: d, decimal: true, hint: 'Margin = 1.96 standard errors.', steps: [`SE = √(${num(p, 2)} × ${num(1 - p, 2)} ÷ ${n}) = ${lab(num(se, 4), 'standard error')}.`, `1.96 (z for ninety-five percent) × ${lab(num(se, 4), 'standard error')} = ${lab(num(m, 4), 'margin of error')} = ±${num(m * 100, 1)} points.`, `So the true rate is probably between ${num((p - m) * 100, 1)} % and ${num((p + m) * 100, 1)} %.`], visual: { type: 'lln', p, n } });
}

/* ---------- 4 hypothesis ---------- */
export function hypothesisQuestion(p0: number, n: number, wins: number, ask: 'z' | 'sig', d: Difficulty, skill = 'prob.hypothesis'): Question {
  const phat = wins / n; const se = Math.sqrt((p0 * (1 - p0)) / n); const z = (phat - p0) / se;
  if (ask === 'z') { const ans = approx(z, 2); return mk(skill, '4 · Hypothesis test', { prompt: `Claim: the coin (or the team) is fair at ${pct(p0)} %. Observed: ${wins} wins in ${n}. Compute the z-score.`, expression: `(p̂ − p₀) ÷ √(p₀(1−p₀) ÷ n) = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'How many standard errors is the observation from the claim?', steps: [`p̂ = ${lab(wins, 'wins')} ÷ ${lab(n, 'games')} = ${lab(num(phat, 3), 'observed rate')}.`, `SE under the claim = √(${num(p0, 2)} × ${num(1 - p0, 2)} ÷ ${n}) = ${lab(num(se, 4), 'standard error')}.`, `z = (${lab(num(phat, 3), 'observed rate')} − ${lab(num(p0, 2), 'claimed rate')}) ÷ ${lab(num(se, 4), 'standard error')} = ${lab(num(z, 2), 'z-score')}.`, `Beyond ±1.96 the result would happen less than 5 % of the time if the claim were true.`], visual: { type: 'bell', z, shade: 'tails' } }); }
  const sig = Math.abs(z) > 1.96 ? 1 : 0;
  return mk(skill, '4 · Hypothesis test', { prompt: `Claim ${pct(p0)} %; observed ${wins} in ${n}, z = ${num(z, 2)}. Is that significant at the 5 % level? Answer 1 for yes, 0 for no.`, expression: '|z| > 1.96 ?', answer: sig, unit: '', difficulty: d, hint: 'Compare |z| with 1.96.', steps: [`|z| = ${lab(num(Math.abs(z), 2), 'size of z')} ${sig ? '>' : '≤'} 1.96 (cut-off).`, sig ? `Significant: the data would be surprising if the claim were true (p < 0.05). Reject the claim.` : `Not significant: this much wobble is normal with ${n} trials. The claim survives, which is not the same as being proved.`], visual: { type: 'bell', z, shade: 'tails' } });
}

/* ---------- 5 binomial ---------- */
export function binomialQuestion(n: number, k: number, p: number, mode: 'exact' | 'atleast', d: Difficulty, rng: Rng, skill = 'prob.binomial'): Question {
  const thing = rng.pick(['free throws', 'penalties', 'coin flips', 'serves']);
  const pk = (j: number) => nCr(n, j) * p ** j * (1 - p) ** (n - j);
  const dist = Array.from({ length: n + 1 }, (_, j) => ({ label: String(j), v: pk(j) }));
  if (mode === 'exact') { const v = pk(k); const ans = approx(v * 100, 1); return mk(skill, '5 · Binomial', { prompt: `${n} ${thing}, each scoring with probability ${pct(p)} %, independently. Probability of exactly ${k} scores?`, expression: `C(${n},${k}) × ${num(p, 2)}^${k} × ${num(1 - p, 2)}^${n - k} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Ways to choose which k succeed, times p^k, times (1−p)^(n−k).', steps: [`Ways to choose the ${k} successes: C(${n},${k}) = ${lab(nCr(n, k), 'patterns')}.`, `Each such pattern has probability ${num(p, 2)}^${k} × ${num(1 - p, 2)}^${n - k} = ${lab(num(p ** k * (1 - p) ** (n - k), 5), 'chance of one pattern')}.`, `${lab(nCr(n, k), 'patterns')} × ${lab(num(p ** k * (1 - p) ** (n - k), 5), 'chance of one pattern')} = ${num(v, 4)} = ${lp(v * 100, 'chance')}.`], visual: { type: 'bars', title: `Binomial n = ${n}, p = ${num(p, 2)}`, values: dist, highlight: k } }); }
  const v = dist.slice(k).reduce((a, b) => a + b.v, 0); const ans = approx(v * 100, 1);
  return mk(skill, '5 · Binomial', { prompt: `${n} ${thing} at ${pct(p)} % each. Probability of at least ${k} scores?`, expression: `Σ P(j) for j = ${k}…${n} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Add the bars from k upward (or 1 − the bars below k).', steps: [`P(j) = C(${n},j) p^j (1−p)^(n−j) for each j.`, `Bars from ${k} to ${n}: ${dist.slice(k).map((x) => num(x.v * 100, 1)).join(' + ')} = ${lp(v * 100, 'chance of at least that many')}.`], visual: { type: 'bars', title: `Binomial n = ${n}, p = ${num(p, 2)}`, values: dist, highlightFrom: k } });
}

/* ---------- 5 poisson ---------- */
export function poissonQuestion(lambda: number, k: number, mode: 'exact' | 'atmost', d: Difficulty, rng: Rng, skill = 'prob.poisson'): Question {
  const thing = rng.pick(['goals in a match', 'breakdowns in a shift', 'customers in a minute', 'aces in a set']);
  const pk = (j: number) => (Math.exp(-lambda) * lambda ** j) / fact(j);
  const dist = Array.from({ length: 9 }, (_, j) => ({ label: String(j), v: pk(j) }));
  if (mode === 'exact') { const v = pk(k); const ans = approx(v * 100, 1); return mk(skill, '5 · Poisson', { prompt: `${thing[0].toUpperCase() + thing.slice(1)} average ${lambda}. Probability of exactly ${k}? (e^−${lambda} ≈ ${num(Math.exp(-lambda), 4)})`, expression: `e^−λ λ^k ÷ k! = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Poisson counts events at a steady average rate.', steps: [`λ = ${lab(lambda, `average ${thing}`)} and k = ${lab(k, 'count we want')}.`, `λ^k = ${lambda}^${k} = ${num(lambda ** k, 3)}; k! = ${fact(k)}.`, `e^−λ = ${num(Math.exp(-lambda), 4)}.`, `${num(Math.exp(-lambda), 4)} × ${num(lambda ** k, 3)} ÷ ${fact(k)} = ${num(v, 4)} = ${lp(v * 100, 'chance')}.`], visual: { type: 'bars', title: `Poisson λ = ${lambda}`, values: dist, highlight: k } }); }
  const v = dist.slice(0, k + 1).reduce((a, b) => a + b.v, 0); const ans = approx(v * 100, 1);
  return mk(skill, '5 · Poisson', { prompt: `${thing[0].toUpperCase() + thing.slice(1)} average ${lambda}. Probability of ${k} or fewer? (e^−${lambda} ≈ ${num(Math.exp(-lambda), 4)})`, expression: `Σ P(j) for j = 0…${k} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Add the bars from 0 up to k.', steps: [`P(j) = e^−λ λ^j ÷ j!, with λ = ${lab(lambda, `average ${thing}`)}.`, `${dist.slice(0, k + 1).map((x) => num(x.v * 100, 1)).join(' + ')} = ${lp(v * 100, 'chance of that many or fewer')}.`, `"More than ${k}" would be 1 − this.`], visual: { type: 'bars', title: `Poisson λ = ${lambda}`, values: dist, highlightTo: k } });
}

/* ---------- 5 normal & t ---------- */
export const T_CRIT: Record<number, number> = { 3: 3.182, 5: 2.571, 8: 2.306, 10: 2.228, 15: 2.131, 20: 2.086, 30: 2.042 };
export function normalQuestion(mode: 'z' | 'below' | 'above' | 'tcrit', mu: number, sigma: number, x: number, d: Difficulty, rng: Rng, skill = 'prob.normal'): Question {
  const z = (x - mu) / sigma; const thing = rng.pick(['lap times', 'daily sales', 'bolt lengths', 'points scored']);
  if (mode === 'z') { const ans = approx(z, 2); return mk(skill, '5 · Normal and t', { prompt: `${thing[0].toUpperCase() + thing.slice(1)} are roughly normal: mean ${mu}, SD ${sigma}. What is the z-score of ${x}?`, expression: `(x − μ) ÷ σ = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'How many standard deviations from the mean?', steps: [`z = (${lab(x, 'value')} − ${lab(mu, 'mean')}) ÷ ${lab(sigma, 'SD')} = ${lab(num(z, 2), 'z-score')}.`, `z says how unusual a value is in SD units, whatever the original units were.`], visual: { type: 'bell', z, shade: 'none', mu, sigma } }); }
  if (mode === 'tcrit') { const df = x; return mk(skill, '5 · Normal and t', { prompt: `A sample of ${df + 1} measurements (small!). For a 95 % interval you must use the t distribution, not 1.96. With ${df} degrees of freedom, what is the critical t? (table: ${Object.entries(T_CRIT).map(([k, v]) => `df ${k}: ${v}`).join(', ')})`, expression: `t₀.₀₂₅, df = ${df} = ?`, answer: T_CRIT[df], unit: '', difficulty: d, decimal: true, hint: 'Degrees of freedom = n − 1; read the table.', steps: [`df = n − 1 = ${lab(df + 1, 'measurements')} − 1 = ${lab(df, 'degrees of freedom')}.`, `From the table, t = ${lab(T_CRIT[df], 'critical t')}, wider than 1.96 (normal cut-off) because a small sample estimates σ badly.`, `As df grows, t sinks toward 1.96 (the normal).`], visual: { type: 'bell', z: T_CRIT[df], shade: 'tails' } }); }
  const below = phi(z); const v = mode === 'below' ? below : 1 - below; const ans = approx(v * 100, 1);
  return mk(skill, '5 · Normal and t', { prompt: `${thing[0].toUpperCase() + thing.slice(1)}: mean ${mu}, SD ${sigma}. Probability a value is ${mode === 'below' ? 'below' : 'above'} ${x}? (Φ table: z 0.5 → 69.1 %, 1 → 84.1 %, 1.5 → 93.3 %, 2 → 97.7 %, 2.5 → 99.4 %; negatives mirror)`, expression: `${mode === 'below' ? 'Φ(z)' : '1 − Φ(z)'} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'z first, then the table; above = 1 − below.', steps: [`z = (${lab(x, 'value')} − ${lab(mu, 'mean')}) ÷ ${lab(sigma, 'SD')} = ${lab(num(z, 2), 'z-score')}.`, `Φ(${num(z, 2)}) = ${lp(below * 100, 'share of values below')}.`, mode === 'below' ? `So P(below ${x}) = ${lp(v * 100, 'chance below')}.` : `Above = 100% (all values) − ${lp(below * 100, 'share below')} = ${lp(v * 100, 'chance above')}.`], visual: { type: 'bell', z, shade: mode === 'below' ? 'below' : 'above', mu, sigma } });
}

/* ---------- 6 regression ---------- */
export function regressQuestion(mode: 'predict' | 'slope' | 'logistic' | 'multi', a: number, b: number, x: number, d: Difficulty, rng: Rng, skill = 'prob.regress'): Question {
  if (mode === 'predict') { const y = a + b * x; const ans = approx(y, 1); return mk(skill, '6 · Regression', { prompt: `A fitted line predicts points from shots: points = ${a} + ${num(b, 2)} × shots. A team takes ${x} shots. Predicted points?`, expression: `${a} + ${num(b, 2)} × ${x} = ?`, ...ans, unit: 'points', difficulty: d, decimal: true, hint: 'Intercept plus slope times x.', steps: [`ŷ = a + b x = ${lab(a, 'baseline points')} + ${lab(num(b, 2), 'points per shot')} × ${lab(x, 'shots')} = ${lab(num(y, 1), 'predicted points')}.`, `The slope says each extra shot is worth ${num(b, 2)} points on average; the intercept is the baseline.`], visual: { type: 'scatter', a, b, x } }); }
  if (mode === 'slope') { const x2 = x + rng.int(3, 8); const y1 = a + b * x; const y2 = a + b * x2; const ans = approx(b, 2); return mk(skill, '6 · Regression', { prompt: `Two points on the line: (${x}, ${num(y1, 1)}) and (${x2}, ${num(y2, 1)}). What is the slope?`, expression: `Δy ÷ Δx = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Rise over run.', steps: [`Δy = ${num(y2, 1)} − ${num(y1, 1)} = ${lab(num(y2 - y1, 1), 'rise')}; Δx = ${x2} − ${x} = ${lab(x2 - x, 'run')}.`, `slope = ${lab(num(y2 - y1, 1), 'rise')} ÷ ${lab(x2 - x, 'run')} = ${lab(num(b, 2), 'slope')}.`, `Least squares finds the slope and intercept that make the total squared miss smallest.`], visual: { type: 'scatter', a, b, x, x2 } }); }
  if (mode === 'logistic') { const z = b; const p = logistic(z); const ans = approx(p * 100, 1); return mk(skill, '6 · Regression', { prompt: `Logistic model: win probability p = 1 ÷ (1 + e^−z), where z is the team's score. z = ${num(z, 1)}. (e^−z ≈ ${num(Math.exp(-z), 3)}) What is p, as a percent?`, expression: `1 ÷ (1 + ${num(Math.exp(-z), 3)}) × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'z = 0 gives 50 %; positive z above, negative below.', steps: [`e^−${num(z, 1)} = ${num(Math.exp(-z), 3)}.`, `p = 1 ÷ (1 + ${num(Math.exp(-z), 3)}) = ${lab(num(p, 3), 'win probability')} = ${lp(p * 100, 'win chance')}.`, `The logistic curve squashes any score into 0…1, which is why it models win/loss.`], visual: { type: 'logistic', z } }); }
  const w = [a, b]; const f = [x, rng.int(1, 9)]; const z = w[0] * f[0] + w[1] * f[1] - 5; const ans = approx(z, 1);
  return mk(skill, '6 · Regression', { prompt: `Multiple regression score: z = ${w[0]} × form + ${w[1]} × rest − 5. Form = ${f[0]}, rest = ${f[1]}. What is z?`, expression: `${w[0]} × ${f[0]} + ${w[1]} × ${f[1]} − 5 = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Each factor times its weight, added, then the intercept.', steps: [`${lab(w[0], 'form weight')} × ${lab(f[0], 'form')} = ${w[0] * f[0]}; ${lab(w[1], 'rest weight')} × ${lab(f[1], 'rest')} = ${w[1] * f[1]}.`, `${w[0] * f[0]} + ${w[1] * f[1]} − 5 (intercept) = ${lab(num(z, 1), 'score')}.`, `Feed z into the logistic curve to get a win probability.`], visual: { type: 'card', title: 'Multiple regression', lines: [`z = ${w[0]}·form + ${w[1]}·rest − 5`, `form = ${f[0]}, rest = ${f[1]}`] } });
}

/* ---------- 7 vectors & elo ---------- */
export function vectorsQuestion(mode: 'dot' | 'matvec' | 'eloE' | 'eloUpdate', a: number[], b: number[], d: Difficulty, skill = 'prob.vectors'): Question {
  if (mode === 'dot') { const v = a.reduce((s, x, i) => s + x * b[i], 0); return mk(skill, '7 · Vectors and Elo', { prompt: `A rating is a dot product: weights (${a.join(', ')}) · features (${b.join(', ')}). What is the rating?`, expression: a.map((x, i) => `${x}×${b[i]}`).join(' + ') + ' = ?', answer: v, unit: '', difficulty: d, hint: 'Multiply matching entries, add them up.', steps: [`${a.map((x, i) => `${lab(x, 'weight')} × ${lab(b[i], 'feature')} = ${x * b[i]}`).join('; ')}.`, `Sum = ${lab(v, 'rating')}. A weighted sum of factors is a dot product, the core of every rating system.`], visual: { type: 'matrix', rows: [a], vec: b, label: 'w · x' } }); }
  if (mode === 'matvec') { const M = [[a[0], a[1]], [a[2], a[3]]]; const v = [M[0][0] * b[0] + M[0][1] * b[1], M[1][0] * b[0] + M[1][1] * b[1]]; return mk(skill, '7 · Vectors and Elo', { prompt: `Matrix × vector: [[${M[0].join(', ')}], [${M[1].join(', ')}]] × (${b.join(', ')}). What is the first entry of the result?`, expression: `${M[0][0]}×${b[0]} + ${M[0][1]}×${b[1]} = ?`, answer: v[0], unit: '', difficulty: d, hint: 'Each output row is that matrix row dotted with the vector.', steps: [`Row 1 · vector = ${M[0][0]} × ${b[0]} + ${M[0][1]} × ${b[1]} = ${lab(v[0], 'first entry')}.`, `Row 2 · vector = ${M[1][0]} × ${b[0]} + ${M[1][1]} × ${b[1]} = ${lab(v[1], 'second entry')}.`, `A matrix applies many weighted sums at once: many teams, many factors.`], visual: { type: 'matrix', rows: M, vec: b, label: 'M x' } }); }
  if (mode === 'eloE') { const ra = a[0]; const rb = b[0]; const e = elo(ra, rb); const ans = approx(e * 100, 1); return mk(skill, '7 · Vectors and Elo', { prompt: `Elo ratings: A ${ra}, B ${rb}. Expected score for A: E = 1 ÷ (1 + 10^((R_B − R_A) ÷ 400)). As a percent? (10^0.25 ≈ 1.778, 10^0.5 ≈ 3.162, 10^0.75 ≈ 5.623, 10^1 = 10; negatives invert)`, expression: `1 ÷ (1 + 10^(${rb - ra} ÷ 400)) × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'A 400-point gap means 10:1 odds.', steps: [`(R_B − R_A) ÷ 400 = (${lab(rb, 'B rating')} − ${lab(ra, 'A rating')}) ÷ 400 (rating gap for ten to one odds) = ${num((rb - ra) / 400, 3)}.`, `10^${num((rb - ra) / 400, 3)} = ${lab(num(10 ** ((rb - ra) / 400), 3), 'B to A odds')}.`, `E = 1 ÷ (1 + ${num(10 ** ((rb - ra) / 400), 3)}) = ${num(e, 3)} = ${lp(e * 100, 'expected score for A')}.`], visual: { type: 'elo', diff: ra - rb } }); }
  const ra = a[0]; const rb = b[0]; const K = a[1]; const S = b[1]; const e = elo(ra, rb); const nr = ra + K * (S - e); const ans = approx(nr, 0);
  return mk(skill, '7 · Vectors and Elo', { prompt: `A (${ra}) plays B (${rb}), expected score for A is ${num(e, 2)}. A ${S === 1 ? 'wins' : S === 0.5 ? 'draws' : 'loses'} (S = ${S}). With K = ${K}, what is A's new rating? R' = R + K(S − E)`, expression: `${ra} + ${K} × (${S} − ${num(e, 2)}) = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Surprise × K: beating a stronger player moves you more.', steps: [`S − E = ${lab(S, 'actual score')} − ${lab(num(e, 2), 'expected score')} = ${lab(num(S - e, 2), 'surprise')}.`, `K × that = ${lab(K, 'K factor')} × ${lab(num(S - e, 2), 'surprise')} = ${lab(num(K * (S - e), 1), 'rating change')}.`, `New rating ≈ ${lab(ra, 'old rating')} ${K * (S - e) < 0 ? '−' : '+'} ${num(Math.abs(K * (S - e)), 1)} = ${lab(num(nr, 0), 'new rating')}. B moves by the same amount the other way.`], visual: { type: 'elo', diff: ra - rb } });
}

/* ---------- 8 markov & monte carlo ---------- */
export function markovQuestion(mode: 'twostep' | 'steady' | 'walk' | 'mc', p: number, q: number, n: number, d: Difficulty, rng: Rng, skill = 'prob.markov'): Question {
  const states = rng.pick([['form', 'slump'], ['dry', 'rain'], ['working', 'broken']]);
  if (mode === 'twostep') { const v = p * p + (1 - p) * (1 - q); const ans = approx(v * 100, 1); return mk(skill, '8 · Chains and Monte Carlo', { prompt: `A Markov chain: from ${states[0]}, stay with probability ${pct(p)} %; from ${states[1]}, return to ${states[0]} with ${pct(1 - q)} %. Starting in ${states[0]}, probability of being in ${states[0]} two steps later?`, expression: `${num(p, 2)}×${num(p, 2)} + ${num(1 - p, 2)}×${num(1 - q, 2)} = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Two routes: stay, stay; or leave, come back. Add them.', steps: [`Stay then stay: ${lab(num(p, 2), 'chance to stay')} × ${lab(num(p, 2), 'chance to stay')} = ${num(p * p, 4)}.`, `Leave then return: ${lab(num(1 - p, 2), 'chance to leave')} × ${lab(num(1 - q, 2), 'chance to return')} = ${num((1 - p) * (1 - q), 4)}.`, `Sum = ${num(v, 4)} = ${lp(v * 100, `chance of ${states[0]}`)}. The next state depends only on the current one: no memory.`], visual: { type: 'markov', states, p, q } }); }
  if (mode === 'steady') { const s = (1 - q) / (1 - p + 1 - q); const ans = approx(s * 100, 1); return mk(skill, '8 · Chains and Monte Carlo', { prompt: `Same chain: stay in ${states[0]} ${pct(p)} %, stay in ${states[1]} ${pct(q)} %. In the long run, what fraction of time is spent in ${states[0]}?`, expression: `(1−q) ÷ ((1−p) + (1−q)) = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Steady state: flow out of A equals flow into A.', steps: [`Leaving ${states[0]}: rate 1 − p = ${lab(num(1 - p, 2), `chance of leaving ${states[0]}`)}. Leaving ${states[1]}: 1 − q = ${lab(num(1 - q, 2), `chance of leaving ${states[1]}`)}.`, `Share of time in ${states[0]} = ${num(1 - q, 2)} ÷ (${num(1 - p, 2)} + ${num(1 - q, 2)}) = ${lp(s * 100, `time in ${states[0]}`)}.`, `Whatever state you start in, the chain forgets it and settles here.`], visual: { type: 'markov', states, p, q } }); }
  if (mode === 'walk') { const up = p; const steps = n; const ans = approx((2 * up - 1) * steps, 2); return mk(skill, '8 · Chains and Monte Carlo', { prompt: `A random walk: each step is +1 with probability ${pct(up)} %, else −1. After ${steps} steps, what is the expected position?`, expression: `${steps} × (${num(up, 2)} − ${num(1 - up, 2)}) = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Expected step = p(+1) + (1−p)(−1). Multiply by the number of steps.', steps: [`Expected step = ${lab(num(up, 2), 'chance of a step up')} − ${lab(num(1 - up, 2), 'chance of a step down')} = ${lab(num(2 * up - 1, 2), 'average step')}.`, `${lab(num(2 * up - 1, 2), 'average step')} × ${lab(steps, 'steps')} = ${lab(num((2 * up - 1) * steps, 2), 'expected position')}.`, `The spread grows like √steps: the walk drifts ${num(2 * up - 1, 2)} per step but wanders about ±${num(Math.sqrt(steps), 1)}.`], visual: { type: 'walk', p: up, steps } }); }
  const sims = n; const hits = Math.round(sims * p); const est = hits / sims; const se = Math.sqrt((est * (1 - est)) / sims); const ans = approx(est * 100, 1);
  return mk(skill, '8 · Chains and Monte Carlo', { prompt: `Monte Carlo: you simulate the season ${sims} times; the team makes the playoffs in ${hits} runs. Estimated probability, as a percent? (Its standard error is about ±${num(se * 100, 1)} points.)`, expression: `${hits} ÷ ${sims} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'A simulation estimate is just a proportion of runs.', steps: [`${lab(hits, 'playoff runs')} ÷ ${lab(sims, 'simulated seasons')} = ${num(est, 3)} = ${lp(est * 100, 'estimated chance')}.`, `Standard error √(p(1−p) ÷ runs) = ${num(se * 100, 1)} points; more runs tighten it.`, `Monte Carlo replaces algebra you cannot do with counting you can.`], visual: { type: 'hist', p: est, sims } });
}

/* ---------- 9 decision ---------- */
export function decisionQuestion(mode: 'ev' | 'kelly' | 'ruin' | 'fair', p: number, b: number, stake: number, d: Difficulty, rng: Rng, skill = 'prob.decision'): Question {
  const q = 1 - p; const thing = rng.pick(['a project bid', 'a wager', 'a parts order', 'a match']);
  if (mode === 'ev') { const ev = p * b * stake - q * stake; const ans = approx(ev, 2); return mk(skill, '9 · EV, Kelly, ruin', { prompt: `${thing[0].toUpperCase() + thing.slice(1)}: you risk ${stake}. With probability ${pct(p)} % you gain ${num(b, 2)} × ${stake} = ${num(b * stake, 2)}; otherwise you lose the ${stake}. Expected value?`, expression: `${num(p, 2)} × ${num(b * stake, 2)} − ${num(q, 2)} × ${stake} = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'EV = Σ probability × payoff, losses negative.', steps: [`Win branch: ${lab(num(p, 2), 'chance to win')} × ${lab(num(b * stake, 2), 'gain')} = ${num(p * b * stake, 2)}.`, `Loss branch: ${lab(num(q, 2), 'chance to lose')} × ${lab(`−${stake}`, 'stake lost')} = −${num(q * stake, 2)}.`, `EV = ${lab(num(ev, 2), 'expected value per play')}${ev > 0 ? ': positive, worth repeating' : ': negative, decline'}. EV is the long-run average, not what happens once.`], visual: { type: 'tree', root: `risk ${stake}`, branches: [{ label: `win +${num(b * stake, 2)}`, p }, { label: `lose −${stake}`, p: q }] } }); }
  if (mode === 'fair') { const fair = q / p; const ans = approx(fair, 2); return mk(skill, '9 · EV, Kelly, ruin', { prompt: `You believe ${thing} succeeds with probability ${pct(p)} %. What payout multiple b (gain per unit risked) makes EV exactly zero?`, expression: `b = q ÷ p = ?`, ...ans, unit: '', difficulty: d, decimal: true, hint: 'Set p × b = q and solve for b.', steps: [`EV = p b − q = 0 → b = q ÷ p = ${lab(num(q, 2), 'chance of failure')} ÷ ${lab(num(p, 2), 'chance of success')} = ${lab(num(fair, 2), 'break-even payout')}.`, `Any offer above ${num(fair, 2)} has positive EV for you; below it, negative. This is how a probability becomes a price.`], visual: { type: 'oddsbar', a: Math.round(q * 100), b: Math.round(p * 100) } }); }
  if (mode === 'kelly') { const f = (b * p - q) / b; const ans = approx(Math.max(0, f) * 100, 1); return mk(skill, '9 · EV, Kelly, ruin', { prompt: `Kelly: with win probability ${pct(p)} % and payout b = ${num(b, 2)}, what fraction of the bankroll maximises long-run growth? f = (bp − q) ÷ b, as a percent.`, expression: `(${num(b, 2)}×${num(p, 2)} − ${num(q, 2)}) ÷ ${num(b, 2)} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Edge over odds. Zero or negative means do not play.', steps: [`bp − q = ${lab(num(b * p, 3), 'payout times win chance')} − ${lab(num(q, 2), 'chance to lose')} = ${lab(num(b * p - q, 3), 'edge')}.`, `${lab(num(b * p - q, 3), 'edge')} ÷ ${lab(num(b, 2), 'payout')} = ${num(f, 4)} = ${lp(f * 100, 'share of bankroll to stake')}${f <= 0 ? ' → no edge, stake nothing' : ''}.`, `Full Kelly is volatile; many use half Kelly. Over-betting past 2× Kelly loses money even with an edge.`], visual: { type: 'kelly', p, b } }); }
  const n = stake; const ruin = p > 0.5 ? (q / p) ** n : 1; const ans = approx(ruin * 100, 1);
  return mk(skill, '9 · EV, Kelly, ruin', { prompt: `Even-money game, win probability ${pct(p)} %, betting 1 unit each time with a bankroll of ${n} units and no stopping point. Risk of ruin ≈ (q ÷ p)^${n}. As a percent?`, expression: `(${num(q, 2)} ÷ ${num(p, 2)})^${n} × 100 = ? %`, ...ans, unit: '%', difficulty: d, decimal: true, hint: 'Ratio of loss to win probability, to the power of the bankroll.', steps: [`q ÷ p = ${lab(num(q, 2), 'chance to lose')} ÷ ${lab(num(p, 2), 'chance to win')} = ${lab(num(q / p, 3), 'loss to win ratio')}.`, `${num(q / p, 3)} to the power ${lab(n, 'bankroll units')} = ${num(ruin, 4)} = ${lp(ruin * 100, 'risk of ruin')}.`, `A bigger bankroll relative to the bet shrinks ruin fast; with no edge (p ≤ 50 %) ruin is certain eventually.`], visual: { type: 'bars', title: `Risk of ruin vs bankroll, p = ${num(p, 2)}`, values: [2, 5, 10, 20, 40].map((k) => ({ label: String(k), v: (q / p) ** k })), highlight: [2, 5, 10, 20, 40].indexOf(n) } });
}

export function probQuestion(kind: ProbKind, d: Difficulty, rng: Rng, skillId?: string): Question {
  const k: Exclude<ProbKind, 'all'> = kind === 'all' ? rng.pick(['algebra', 'count', 'sample', 'events', 'conditional', 'bayes', 'center', 'sampling', 'hypothesis', 'binomial', 'poisson', 'normal', 'regress', 'vectors', 'markov', 'decision'] as const) : kind;
  const sid = skillId ?? (kind === 'all' ? 'prob' : `prob.${k}`);
  const P = () => rng.pick(d <= 2 ? [0.2, 0.25, 0.4, 0.5, 0.6, 0.75, 0.8] : [0.15, 0.3, 0.35, 0.45, 0.55, 0.65, 0.7, 0.85]);
  if (k === 'algebra') { const mode = d <= 2 ? rng.pick(['oddsToP', 'proportion'] as const) : rng.pick(['oddsToP', 'pToOdds', 'proportion', 'rearrange'] as const); if (mode === 'rearrange') return algebraQuestion(mode, rng.pick([40, 50, 55, 60, 65, 75]), rng.pick([20, 40, 60, 80]), d, rng, sid); if (mode === 'proportion') return algebraQuestion(mode, rng.int(2, 12), rng.int(2, 8), d, rng, sid); return algebraQuestion(mode, rng.int(1, 9), rng.int(1, 5), d, rng, sid); }
  if (k === 'count') { const mode = d <= 2 ? rng.pick(['multiply', 'perm'] as const) : rng.pick(['multiply', 'perm', 'comb'] as const); return countQuestion(mode, rng.int(mode === 'multiply' ? 2 : 4, mode === 'multiply' ? 5 : d <= 3 ? 7 : 10), mode === 'multiply' ? rng.int(2, 5) : rng.int(2, 3), d, rng, sid); }
  if (k === 'sample') { const mode = d <= 2 ? rng.pick(['dice', 'complement'] as const) : rng.pick(['dice', 'coins', 'complement'] as const); return sampleQuestion(mode, mode === 'dice' ? rng.int(2, 12) : mode === 'coins' ? rng.int(2, 5) : rng.int(5, 95), d, rng, sid); }
  if (k === 'events') { const mode = d <= 2 ? rng.pick(['independent', 'exclusive'] as const) : rng.pick(['independent', 'exclusive', 'dependent', 'atleast'] as const); if (mode === 'exclusive') { const p1 = rng.pick([0.3, 0.4, 0.45, 0.5]); return eventsQuestion(mode, p1, rng.pick([0.2, 0.25, 0.3]), d, rng, sid); } if (mode === 'dependent') return eventsQuestion(mode, rng.pick([0.3, 0.4, 0.5, 0.6, 0.7]), 0, d, rng, sid); if (mode === 'atleast') return eventsQuestion(mode, rng.pick([0.1, 0.2, 0.25, 0.3, 0.4]), rng.int(2, 6), d, rng, sid); return eventsQuestion(mode, P(), P(), d, rng, sid); }
  if (k === 'conditional') { const a = rng.int(10, 60); const b = rng.int(10, 60); const c = rng.int(10, 60); const e = rng.int(10, 60); const table = { rows: ['home', 'away'] as [string, string], cols: ['win', 'not win'] as [string, string], n: [[a, b], [c, e]] as [[number, number], [number, number]] }; return conditionalQuestion(table, d <= 2 ? 'given' : rng.pick(['given', 'joint', 'marginal'] as const), d, sid); }
  if (k === 'bayes') return bayesQuestion(rng.pick(d <= 3 ? [0.1, 0.2, 0.3] : [0.01, 0.02, 0.05, 0.1]), rng.pick([0.8, 0.9, 0.95]), rng.pick([0.8, 0.9, 0.95]), d, rng, sid);
  if (k === 'center') { const n = d <= 2 ? 4 : 5; const data = Array.from({ length: n }, () => rng.int(2, 12)); return centerQuestion(data, d <= 2 ? 'mean' : rng.pick(['mean', 'variance', 'sd'] as const), d, rng, sid); }
  if (k === 'sampling') return samplingQuestion(d <= 2 ? 'expected' : rng.pick(['expected', 'se', 'margin'] as const), P(), rng.pick([25, 50, 100, 400, 900, 1600]), d, sid);
  if (k === 'hypothesis') { const n = rng.pick([50, 100, 200, 400]); const p0 = rng.pick([0.5, 0.6, 0.4]); const wins = Math.round(n * (p0 + rng.pick([-0.12, -0.08, -0.05, 0.03, 0.06, 0.1, 0.15]))); return hypothesisQuestion(p0, n, wins, d <= 3 ? 'z' : rng.pick(['z', 'sig'] as const), d, sid); }
  if (k === 'binomial') { const n = rng.int(3, d <= 3 ? 5 : 8); return binomialQuestion(n, rng.int(0, n), P(), d <= 3 ? 'exact' : rng.pick(['exact', 'atleast'] as const), d, rng, sid); }
  if (k === 'poisson') return poissonQuestion(rng.pick([0.5, 1, 1.5, 2, 2.5, 3]), rng.int(0, 4), d <= 3 ? 'exact' : rng.pick(['exact', 'atmost'] as const), d, rng, sid);
  if (k === 'normal') { const mu = rng.pick([50, 60, 70, 80, 100]); const sigma = rng.pick([4, 5, 8, 10]); const mode = d <= 2 ? 'z' : rng.pick(['z', 'below', 'above', 'tcrit'] as const); if (mode === 'tcrit') return normalQuestion(mode, 0, 1, rng.pick([3, 5, 8, 10, 15, 20, 30]), d, rng, sid); return normalQuestion(mode, mu, sigma, mu + sigma * rng.pick([-2, -1.5, -1, -0.5, 0.5, 1, 1.5, 2, 2.5]), d, rng, sid); }
  if (k === 'regress') { const mode = d <= 2 ? 'predict' : rng.pick(['predict', 'slope', 'logistic', 'multi'] as const); if (mode === 'logistic') return regressQuestion(mode, 0, rng.pick([-2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2]), 0, d, rng, sid); if (mode === 'multi') return regressQuestion(mode, rng.int(1, 3), rng.int(1, 3), rng.int(1, 9), d, rng, sid); return regressQuestion(mode, rng.int(5, 30), rng.pick([1.5, 2, 2.5, 3, 0.5]), rng.int(4, 20), d, rng, sid); }
  if (k === 'vectors') { const mode = d <= 2 ? rng.pick(['dot', 'eloE'] as const) : rng.pick(['dot', 'matvec', 'eloE', 'eloUpdate'] as const); if (mode === 'dot') return vectorsQuestion(mode, [rng.int(1, 5), rng.int(1, 5), rng.int(1, 5)], [rng.int(1, 9), rng.int(1, 9), rng.int(1, 9)], d, sid); if (mode === 'matvec') return vectorsQuestion(mode, [rng.int(1, 5), rng.int(1, 5), rng.int(1, 5), rng.int(1, 5)], [rng.int(1, 9), rng.int(1, 9)], d, sid); const ra = rng.pick([1400, 1500, 1600, 1800, 2000]); const diff = rng.pick([-400, -300, -200, -100, 0, 100, 200, 300, 400]); if (mode === 'eloE') return vectorsQuestion(mode, [ra], [ra - diff], d, sid); return vectorsQuestion(mode, [ra, rng.pick([16, 20, 32])], [ra - diff, rng.pick([1, 0, 0.5])], d, sid); }
  if (k === 'markov') { const mode = d <= 2 ? rng.pick(['twostep', 'mc'] as const) : rng.pick(['twostep', 'steady', 'walk', 'mc'] as const); if (mode === 'mc') return markovQuestion(mode, rng.pick([0.3, 0.42, 0.55, 0.61, 0.72, 0.85]), 0, rng.pick([200, 500, 1000, 2000]), d, rng, sid); if (mode === 'walk') return markovQuestion(mode, rng.pick([0.5, 0.55, 0.6, 0.7]), 0, rng.pick([10, 20, 50, 100]), d, rng, sid); return markovQuestion(mode, rng.pick([0.6, 0.7, 0.8, 0.9]), rng.pick([0.5, 0.6, 0.7]), 0, d, rng, sid); }
  const mode = d <= 2 ? rng.pick(['ev', 'fair'] as const) : rng.pick(['ev', 'fair', 'kelly', 'ruin'] as const);
  if (mode === 'ruin') return decisionQuestion(mode, rng.pick([0.52, 0.55, 0.6, 0.65]), 1, rng.pick([2, 5, 10, 20, 40]), d, rng, sid);
  return decisionQuestion(mode, rng.pick([0.3, 0.4, 0.45, 0.5, 0.55, 0.6, 0.7]), rng.pick([0.8, 1, 1.5, 2, 2.5, 3]), rng.pick([10, 20, 50, 100]), d, rng, sid);
}

export const genProb: Generator = (skillId, params, ctx) => probQuestion(String(params?.kind ?? 'all') as ProbKind, ctx.difficulty, ctx.rng, skillId);
