import {missions,byId} from '../src/content.js';import {adapters} from '../src/models.js';import {scene,esc} from '../src/visuals.js';import {createRoomClient} from '../src/room-client.js';import {openStore,loadSave,persist} from '../src/storage.js';
const $=s=>document.querySelector(s),client=createRoomClient(localStorage);let view=null,busy=false;
const status=s=>$('#status').textContent=s;
function render(next){if(next)view=next;const conn=client.connection();$('#setup').hidden=!!conn;$('#room').hidden=!conn;if(!view)return;$('#players').innerHTML=`<h2>${esc(byId[view.mission].title)}</h2><p>${view.players.map(p=>esc(p.name)+(p.id===view.self?' (you)':'')).join(' · ')}</p><p>${view.roles.map(r=>r.role+': '+esc(view.players.find(p=>p.id===r.profile)?.name)).join(' · ')}</p>`;const s=view.session,m=byId[view.mission];if(!s){$('#task').innerHTML=view.self===view.host?'<button data-action="start">Start with this team</button>':'<p>Waiting for the host to start.</p>';return;}$('#scene').innerHTML=scene(m.adapter,s.input,s.trials.at(-1),s.trials.length?1:0);let panel='';if(['predict','explain'].includes(s.stage)){const q=m.questions[s.stage];panel=`<h2>${s.stage==='predict'?'Individual prediction':'Individual explanation'}</h2>`;if(view.actor===view.self)panel+=`<p>${esc(q.prompt)}</p>${q.options.map((text,i)=>`<button data-action="answer" data-choice="${i}">${esc(text)}</button>`).join('')}<button data-action="hint">Help with this idea</button>${s.help[s.stage][view.self]?`<p>Supported response: ${esc(q.options[q.correct])}</p>`:''}`;else panel+=`<p>Waiting for ${esc(view.players.find(p=>p.id===view.actor)?.name)}. Other answers remain hidden.</p>`;}else if(s.stage==='experiment'){const a=adapters[m.adapter],role=id=>view.roles.find(r=>r.role===id)?.profile===view.self;panel=`<h2>Shared experiment</h2><p>${esc(a.fixed)}. Compare ${m.compare.join(' and ')} ${a.unit}.</p><label class="field">${esc(a.input)}<input id="setting" type="number" min="${a.min}" max="${a.max}" step="${a.step}" value="${s.input}" ${role('Builder')?'':'disabled'}></label>${role('Builder')?'<button data-action="configure">Set experiment</button>':''}${role('Tester')?'<button data-action="trial">Run shared trial</button>':''}${role('Explainer')?'<button data-action="explain">Begin individual explanations</button>':''}<ul>${s.trials.map(t=>`<li>${t.input} ${a.unit} → ${t.value.toFixed(2)} ${a.outUnit}</li>`).join('')}</ul>`;}else panel=`<h2>Everyone contributed</h2><p>Your individual answers can be saved to your journal. Team completion does not award solo mastery.</p>${view.self===view.host?'<button data-action="next">Rotate roles and try again</button>':''}`;$('#task').innerHTML=panel;}
async function act(fn){if(busy)return;busy=true;try{const result=await fn();if(result)render(result);}catch(e){status(e.message);}finally{busy=false;if(!view)render();}}
$('#connect').onsubmit=e=>{e.preventDefault();act(async()=>{const data=await loadSave(),p=data?.profiles.find(p=>p.id===$('#profile').value);if(!p)throw Error('Create an explorer in the game first.');return client.connect({url:$('#url').value,invite:$('#invite').value.trim(),profile:p.id,name:p.name,mission:$('#mission').value});});};
$('#task').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;act(()=>client.action(b.dataset.action,b.dataset.action==='answer'?{choice:Number(b.dataset.choice)}:b.dataset.action==='configure'?{input:Number($('#setting').value)}:{}));};
$('#refresh').onclick=()=>act(()=>client.refresh());$('#retry').onclick=()=>act(()=>client.retry());$('#share').onclick=()=>{$('#invitation').textContent='Share privately: '+client.connection().invite;};$('#leave').onclick=()=>act(()=>{if(!confirm('Leave this connection? Rejoining creates a new player and is unavailable after the room starts. Save your evidence first.'))return;client.leave();location.reload();});$('#close').onclick=()=>act(async()=>{if(!confirm('Close the room for everyone? Save individual evidence first.'))return;await client.close();location.reload();});
$('#import').onclick=()=>act(async()=>{if(!view)throw Error('Refresh the room first.');const data=await loadSave(),p=data?.profiles.find(p=>p.id===client.connection().profile);if(!p)throw Error('The linked local explorer is missing.');p.coopEvidence??=[];const ids=new Set(p.coopEvidence.map(e=>e.id));let count=0;for(const item of view.evidence){if(ids.has(item.id))continue;const record={...item,remoteProfile:item.profile,profile:p.id,online:true};p.coopEvidence.push(record);await persist(data,{...record,type:'online-coop-contribution'});ids.add(item.id);count++;}status(count+' individual contributions saved. Return to the game to read your journal.');});
await openStore();const data=await loadSave();$('#profile').innerHTML=(data?.profiles||[]).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#mission').innerHTML=missions.map(m=>`<option value="${m.id}">${esc(m.title)}</option>`).join('');render();if(client.connection())await act(()=>client.connection().pending?client.retry():client.refresh());setInterval(()=>{if(client.connection()&&!document.hidden&&!busy)act(async()=>{const next=await client.refresh();return next?.revision!==view?.revision?next:null;});},5000);
