import {startUpdates} from './updates.js';
import {profileStore} from './profiles.js';
import {optionPrice,backtest,series} from './advanced-engine.js';
import {KEY,fresh,valid,mastery,record,grade,question,chooseSkill,desk,quoteAt,pnl,openTrade,advance,closeTrade,migrate,repairResult,variations,rng,scenarios,planScore,sessions,sessionAt,setClock,startDay,closeDay,dueCount,processScore} from './engine.js';
import {worlds,skillNames,roadmap,sources} from './content.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=fresh(),warning='',view='floor',world=worlds[0],lesson=null,session=null,sim=desk(),message='',observe=false,ticker=null;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!valid(parsed))throw Error();state=migrate(parsed);}}catch{warning='Saved progress could not be read. You can practice now; export a backup before closing.';}
let players=null;
try{players=profileStore(localStorage,state);state=players.load();}catch{warning='Player profiles could not be loaded. Existing saved data has been kept; export any practice you do now.';}
function save(){try{if(!players)throw Error();players.save(state);return true;}catch{warning='Progress could not be saved on this device. Use Export progress to keep a copy.';return false;}}
function playerDialog(){
 const d=document.createElement('dialog');d.className='player-dialog';
 d.innerHTML=`<h2>Your player profile</h2><p>Keep your name and learning progress on this browser. Profiles are not password-protected and do not automatically sync between devices.</p><form id="rename-player"><label for="player-name">Your name</label><input id="player-name" maxlength="40" required autocomplete="nickname" value="${esc(players.current().name==='Guest'?'':players.current().name)}"><button class="btn primary">Save name</button></form><h3>Switch player</h3><div class="player-list">${players.list().map(p=>`<button class="btn" data-player="${esc(p.id)}" ${p.id===players.current().id?'disabled':''}>${esc(p.name)}${p.id===players.current().id?' · current':''}</button>`).join('')}</div><form id="new-player"><label for="new-player-name">New player name</label><input id="new-player-name" maxlength="40" required><button class="btn">Create separate profile</button></form><p class="small">Saving your name keeps your existing progress. A new profile starts a new expedition. Use Export progress on the floor for a backup; imports go into the current player.</p><p id="player-error" role="alert"></p><form method="dialog"><button class="btn subtle">Close</button></form>`;
 document.body.append(d);d.addEventListener('close',()=>d.remove());
 const act=fn=>{try{if(!save())throw Error(warning);fn();d.close();render();}catch(e){d.querySelector('#player-error').textContent=e.message;}};
 d.querySelector('#rename-player').onsubmit=e=>{e.preventDefault();act(()=>players.rename(d.querySelector('#player-name').value));};
 const change=fn=>act(()=>{fn();state=players.load();session=null;sim=desk();research={seed:Date.now()>>>0,frozen:null,revealed:false};view='floor';message='';});
 d.querySelector('#new-player').onsubmit=e=>{e.preventDefault();change(()=>players.add(d.querySelector('#new-player-name').value));};
 d.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>change(()=>players.switch(b.dataset.player)));
 d.showModal();
}

const score=w=>Math.round(w.skills.reduce((sum,s)=>sum+mastery(state.records[s]),0)/w.skills.length);
const unlocked=w=>worlds.indexOf(w)===0||!!state.exams?.[worlds[worlds.indexOf(w)-1].id]?.passed;
const hhmm=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
// Each session fills a third of the strip, whatever its length in minutes.
const clockPos=c=>{const i=sessions.findIndex(([,,to])=>c<to);if(i<0)return 100;const [,from,to]=sessions[i];return (i+Math.max(0,c-from)/(to-from))*100/3;};
const speedLabel=s=>s===0?'⏸ paused':s===3?'▶▶ 3×':'▶ 1×';
function strip(){const d=state.day,name=d.session==='closed'?'MARKET CLOSED':`${sessions.find(x=>x[0]===d.session)[3].toUpperCase()} SESSION`;return `<div class="clock" role="group" aria-label="Market clock, day ${d.n}"><div class="clock-head"><span>DAY ${d.n} · MARKET CLOCK</span><span class="clock-now s-${d.session}" id="clock-now">${name} · ${hhmm(d.clock)} · ${speedLabel(d.speed)}</span></div><div class="clock-bar" role="progressbar" aria-label="Market day progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(clockPos(d.clock))}" aria-valuetext="${name} ${hhmm(d.clock)}">${sessions.map(([id])=>`<i class="s-${id}"></i>`).join('')}<b style="left:${clockPos(d.clock).toFixed(1)}%"></b></div><div class="clock-legend">${sessions.map(([id,,,label,what])=>`<span class="s-${id}">${label} · ${what}</span>`).join('')}</div></div>`;}
function shell(body,{chips:extra=''}={}){const due=dueCards().length;const unexplored=currentWorld().lessons.filter(l=>!state.lessons.includes(l.id)).length;const tabs=[['floor','◈','The floor'],["world","☼","Briefing",unexplored],['worlds','◇','Worlds'],['practice','⌁','Desk calls'],['desk','▥','Trading desk'],['labs','⚗','Research labs'],['notebook','⬡','Risk review',due],['close','◎','Close of day'],['sources','◎','Field guide']];const who=players?.current().name??'Guest';$('#app').innerHTML=`<div class="shell"><aside><div class="brand"><b>⟠</b><div>FOREX QUEST<small>THE TRADING FLOOR</small></div></div><nav aria-label="Main navigation">${tabs.map(([id,icon,label,count])=>`<button data-nav="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}><span class="ico" aria-hidden="true">${icon}</span>${label}${count?`<span class="count" aria-label="${count} waiting">${count}</span>`:''}</button>`).join('')}</nav><div class="side-note"><b>${esc(who)}</b> · Day ${state.day.n}<br><button id="player-profile" ${players?'':'disabled'}>${who==='Guest'?'Add your name':'Player profiles'}</button><br><a href="../">← Back to Eng Quest</a></div></aside><main id="main" tabindex="-1"><div class="topbar">${strip()}${extra}<span class="sim-badge">● SIMULATION ONLY</span></div>${warning?`<div class="toast" role="status">${esc(warning)}</div>`:''}${body}<footer>Practice funds only · Progress stays in this browser · No broker connection<br>Learning scores measure practice, not readiness for profitable trading.</footer></main></div>`;$('#player-profile').onclick=playerDialog;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;if(view==='world')world=currentWorld();session=null;message='';render();});}
function worldsScreen(){shell(`<div class="eyebrow">World map</div><h1>Twelve worlds, one desk.</h1><div class="section-head"><h2>Your learning worlds</h2><span class="small">${passedCount()}/12 worlds restored</span></div><div class="grid">${worlds.map((w,i)=>`<article class="card" style="--accent:${w.color}"><div class="row"><span class="world-icon">${w.icon}</span><span class="world-num">World ${String(i+1).padStart(2,'0')}</span></div><h3>${w.title}</h3><p>${w.subtitle}</p><div class="progress" role="progressbar" aria-label="${w.title} mastery" aria-valuenow="${score(w)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${score(w)}%"></span></div><span class="small">${score(w)}% mastery · 3 lessons</span><button class="btn" data-world="${w.id}" ${unlocked(w)?'':'disabled'}>${unlocked(w)?'Enter world →':'Clear previous world challenge'}</button></article>`).join('')}</div><p>${passedCount()===12?'All twelve worlds are restored. Your expedition is complete; due reviews and research labs remain available.':'Each cleared world challenge restores one part of the city network. The final challenge combines every world.'}</p>`);document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>{world=worlds.find(w=>w.id===b.dataset.world);view='world';render();});}
const passedCount=()=>Object.values(state.exams).filter(e=>e.passed).length;
const currentWorld=()=>worlds.find(w=>unlocked(w)&&!state.exams[w.id]?.passed)??worlds.at(-1);
const todayScenario=()=>Object.keys(scenarios)[(state.day.n-1)%Object.keys(scenarios).length];
function dueCards(now=Date.now()){return Object.entries(state.notebook).filter(([,q])=>(q.due??0)<=now);}
const account=()=>10000;
const money=(x,d=0)=>`${x<0?'−':''}$${Math.abs(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const tone=m=>m>=90?'up':m>=70?'gold':'london';
const meter=(label,value,extra='')=>`<div class="meter"><span>${label}</span><div class="track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><i class="bg-${tone(value)}" style="width:${value}%"></i></div><b class="${tone(value)}">${value}%</b>${extra}</div>`;
function chips(){return `<div class="chips"><div class="chip"><strong class="up">${money(account())}</strong><span>PRACTICE ACCT</span></div><div class="chip"><strong class="gold">EUR/USD</strong><span>LICENCE · TIER ${passedCount()}</span></div><div class="chip"><strong class="ny">${state.streak?.current??0}</strong><span>DAY STREAK</span></div></div>`;}
// Up next: unexplored lesson in the current world → today's scenario → due reviews → close.
function upNext(){const w=currentWorld(),l=w.lessons.find(x=>!state.lessons.includes(x.id)),ids=Object.keys(scenarios),sc=todayScenario(),due=dueCards().length;
 if(l&&!state.loop.briefing)return {tone:'asia',eyebrow:'UP NEXT · BRIEFING',title:l.title,text:`${w.title} · lesson ${w.lessons.indexOf(l)+1} of ${w.lessons.length}. ${l.what}`,label:'Open the briefing ▸',go:()=>{world=w;lesson=l;view='lesson';}};
 if(!state.loop.desk)return {tone:'london',eyebrow:'UP NEXT · DESK OPEN',title:`${scenarios[sc].name} · scenario ${ids.indexOf(sc)+1} of ${ids.length}`,text:`${scenarios[sc].description} ${scenarios[sc].calendar.filter(e=>e.impact==='high').map(e=>`${e.title} at step ${e.step}.`).join(' ')} Plan before the quote moves.`,label:'Walk to the desk ▸',observe:true,go:()=>{if(!sim.position&&sim.scenario!==sc)sim=desk(sc);view='desk';}};
 if(due)return {tone:'newyork',eyebrow:'UP NEXT · RISK REVIEW',title:`${due} flag${due===1?'':'s'} due on Ari’s bench`,text:'Repair them before New York close to keep the review streak.',label:'Open the risk review ▸',go:()=>{view='notebook';}};
 return {tone:'gold',eyebrow:'UP NEXT · CLOSE OF DAY',title:'The loop is done for today',text:'Ledger, journal and mastery deltas, then a fresh market day.',label:'Close the day ▸',go:()=>{view='close';}};}
function floor(){const next=upNext(),w=currentWorld(),due=dueCards().length,sc=scenarios[todayScenario()],l=w.lessons.find(x=>!state.lessons.includes(x.id))??w.lessons.at(-1);
 const rows=[['briefing',`Briefing · ${l.title}`,'Asia','lesson'],['desk',`Desk · ${sc.name}`,'London','desk'],['review',`Risk review · ${due} flag${due===1?'':'s'} due`,'New York','notebook'],['close','Close of day · ledger & journal','17:00','close']];
 const done=rows.filter(([k])=>state.loop[k]).length,current=rows.find(([k])=>!state.loop[k])?.[0];
 const best=Math.max(state.snapshot.bestConquer??0,session?.mode==='conquer'?session.correct:0),plan=Math.max(0,...(state.plans??[]).filter(p=>p.day===state.day.n).map(p=>p.score));
 const missions=[['Answer 8 of 10 desk calls','practice',best*10,`${best} / 10 · conquer run`,'london'],['Open one trade with a 4/4 plan','process score',plan*25,'hypothesis · invalidation · size · cost','gold'],['Clear all due reviews before close','keeps streak',due?0:100,`${due} due · Ari’s bench`,'newyork']];
 const top=Object.entries(state.records).map(([k,r])=>[k,mastery(r)]).sort((a,b)=>b[1]-a[1])[0];
 const news=[due?`Ari flagged <b class="down">${due} card${due===1?'':'s'}</b> for review`:'Ari’s bench is clear',top&&top[1]>=70?`Your ${skillNames[top[0]]} mastery hit <b class="up">${top[1]}%</b>`:'',`Today’s tape: <b class="london">${sc.name}</b>`].filter(Boolean);
 const ready=w.skills.filter(k=>mastery(state.records[k])>=70).length;
 shell(`<div class="floor"><div class="stack"><section class="up-next tone-${next.tone}"><div class="up-eyebrow">${next.eyebrow}</div><h1>${esc(next.title)}</h1><p>${esc(next.text)}</p><div class="row"><button class="btn gold" id="up-next">${next.label}</button>${next.observe?'<button class="btn subtle" id="up-observe">Observe only</button>':''}</div></section>
 <section class="panel grow"><div class="panel-head"><h2 class="label">Today’s loop</h2><span class="up">${done} of 4 done</span></div><div class="loop">${rows.map(([k,label,meta,go],i)=>`<button class="loop-row ${state.loop[k]?'done':k===current?'now':''}" data-go="${go}"><span class="mark">${state.loop[k]?'✓':i+1}</span><span class="grow">${esc(label)}</span><span class="meta">${state.loop[k]?'done':k===current?'open now':meta}</span></button>`).join('')}</div></section></div>
 <div class="stack"><section class="panel"><div class="panel-head"><h2 class="label">Daily missions</h2><span>reset at New York close</span></div>${missions.map(([t,tag,v,sub,c])=>`<div class="mission"><div class="mission-head"><span>${t}</span><span class="gold">${v>=100?'✓ done':tag}</span></div><div class="track"><i class="bg-${c}" style="width:${Math.min(100,v)}%"></i></div><small>${sub}</small></div>`).join('')}</section>
 <section class="panel"><h2 class="label">Floor news</h2><p class="news">${news.join(' · ')}</p></section>
 <section class="panel grow"><div class="panel-head"><h2 class="label">Next licence · ${w.title}</h2><span class="gold">${ready} of ${w.skills.length} skills ready</span></div>${w.skills.map(k=>meter(skillNames[k],mastery(state.records[k]))).join('')}<p class="small">${unlockLine(w)}</p><div class="row"><button class="btn subtle" id="floor-practice">Practise these skills</button>${ready===w.skills.length?`<button class="btn gold" id="floor-exam">Licence exam ▸</button>`:''}</div></section></div></div>
 <div class="row backup"><button class="btn subtle" id="export">Export progress</button><label class="btn subtle" for="import">Import progress</label><input type="file" id="import" accept="application/json" class="screen-reader"></div>`,{chips:chips()});
 $('#up-next').onclick=()=>{next.go();render();};if($('#up-observe'))$('#up-observe').onclick=()=>{next.go();observe=true;render();};
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.go==='lesson'){world=w;lesson=l;}view=b.dataset.go;render();});
 $('#floor-practice').onclick=()=>start(w.skills);if($('#floor-exam'))$('#floor-exam').onclick=()=>start(w.id==='capstone'?Object.keys(skillNames):w.skills,'exam',null,w.id);
 wireBackup();}
const unlockLine=w=>`Passing restores ${w.title} and opens the next world’s briefing.`;
function wireBackup(){$('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='forex-quest-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error();const parsed=JSON.parse(await f.text());if(!valid(parsed))throw Error();state=migrate(parsed);save();render();}catch{warning='That file is not a valid Forex Quest progress export.';render();}};}
// Colleagues voice the floor. Copy only; they never change scoring.
const colleagues={noor:['Noor','macro analyst','asia','“Write down the expectation before the release prints. If you can’t say what the market expected, you can’t say you were surprised.”'],jules:['Jules','execution','london','“A chart crossing your stop is not a fill. Read the bid, read the ask, then decide.”'],ari:['Ari','risk','gold','“Size comes from the loss budget, never from how sure you feel.”'],mara:['Mara','navigator','mint','“Name the base, the quote and the units before you touch a number.”']};
const crew={harbor:'mara',execution:'jules',risk:'ari',charts:'mara',macro:'noor',funding:'noor',strategy:'mara',crisis:'ari',quant:'noor',micro:'jules',research:'mara',capstone:'ari'};
const colleague=w=>colleagues[crew[w?.id]??'mara'];
const worldOf=skill=>worlds.find(w=>w.skills.includes(skill))??worlds[0];
function calendarPanel(id=todayScenario(),tick=null){const sc=scenarios[id];return `<section class="panel"><div class="panel-head"><h2 class="label">Today’s calendar · synthetic</h2><span>${esc(sc.name)} · times in scenario steps</span></div><div class="calendar">${sc.calendar.map(e=>`<div class="event imp-${e.impact==='—'?'end':e.impact} ${tick!==null&&e.step<tick?'past':''}"><b>step ${e.step}</b><div class="grow"><strong>${esc(e.title)}</strong><small>${esc(e.expected)}</small></div><span class="pill">${e.impact}</span></div>`).join('')}</div></section>`;}
function briefingAside(w){const [name,role,c,says]=colleague(w),due=dueCards().length;return `<div class="stack">${calendarPanel()}<section class="panel"><h2 class="label">Briefing checklist</h2><ul class="checklist">${w.lessons.map((l,i)=>`<li class="${state.lessons.includes(l.id)?'done':lesson?.id===l.id?'now':''}"><span>${state.lessons.includes(l.id)?'✓':lesson?.id===l.id?i+1:''}</span>Lesson ${i+1} · ${esc(l.title)}</li>`).join('')}<li class="${due?'':'done'}"><span>${due?'':'✓'}</span>${due} due review${due===1?'':'s'} from the risk bench</li></ul><p class="small">Desk opens whenever you like — the briefing is a head start, not a gate. Lessons stay available all day.</p></section><section class="says says-${c}"><div class="up-eyebrow">${name.toUpperCase()} SAYS</div><p>${says}</p></section></div>`;}
const deskSkills=new Set(['pip','spread','executionjudgment','risk','margin','riskjudgment','surprise','macrojudgment']);
function worldScreen(){const [name,role,c]=colleague(world);shell(`<div class="brief"><div class="stack"><div class="up-eyebrow ${c}">${state.day.session==='asia'?'ASIA SESSION':'BRIEFING'} · ${hhmm(state.day.clock)} · ${world.title.toUpperCase()} · WITH ${name.toUpperCase()}, ${role.toUpperCase()}</div><h1>${world.title}</h1><p>${world.subtitle} Explore an explanation, then try a new example without a hint.</p><div class="lesson-list">${world.lessons.map((l,i)=>`<button data-lesson="${l.id}"><span class="small">${state.lessons.includes(l.id)?'✓ Explored':`Lesson ${i+1} of ${world.lessons.length}`}</span><h3>${l.title}</h3><small>${skillNames[l.skill]}</small></button>`).join('')}</div><div class="row"><button class="btn primary" id="world-practice">Practice this world →</button><button class="btn" id="world-exam" ${world.skills.every(k=>mastery(state.records[k])>=70)?'':'disabled'}>World challenge · ${world.id==='capstone'?54:12} questions</button></div><p class="small">Each skill needs 70% practice mastery to enter. Clear at least 80% overall and two-thirds in every tested skill. The final challenge covers all 27 skills. ${state.exams[world.id]?.passed?'✓ World restored.':''}</p></div>${briefingAside(world)}</div>`);document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lesson=world.lessons.find(l=>l.id===b.dataset.lesson);view='lesson';render();});$('#world-practice').onclick=()=>start(world.skills);$('#world-exam').onclick=()=>start(world.id==='capstone'?Object.keys(skillNames):world.skills,'exam',null,world.id);}
function lessonScreen(){const [name,role,c]=colleague(world),k=world.lessons.indexOf(lesson);shell(`<div class="brief"><article class="stack"><div class="up-eyebrow ${c}">${state.day.session==='asia'?'ASIA SESSION':'BRIEFING'} · ${hhmm(state.day.clock)} · ${world.title.toUpperCase()} · WITH ${name.toUpperCase()}, ${role.toUpperCase()}</div><h1>${lesson.title}</h1><div class="pills"><span class="pill">Lesson ${k+1} of ${world.lessons.length}</span><span class="pill">Skill · ${skillNames[lesson.skill]}</span>${deskSkills.has(lesson.skill)?'<span class="pill up-pill">Used on the desk today</span>':''}</div><section class="panel prose"><div class="label mint">What it means</div><p>${lesson.what}</p><div class="label mint">Why it matters</div><p>${lesson.why}</p></section><div class="callout"><span class="label mint">Worked example</span><p>${lesson.example}</p></div><section class="panel prose"><div class="label mint">The move to remember</div><p>${lesson.rule}</p></section><div class="row"><button class="btn gold" id="try">Try two on my own ▸</button><span class="small">Marks the lesson explored, then 2 fresh examples. No hints, no timer.</span></div></article>${briefingAside(world)}</div>`);$('#try').onclick=()=>{state.lessons=[...new Set([...state.lessons,lesson.id])];state.loop.briefing=true;state=setClock(state,Math.min(479,state.day.clock+20));save();start([lesson.skill],'lesson');};}
function makeQueue(skills,n,random=Math.random){const queue=[];for(let i=0;i<n;i++){const skill=skills[i%skills.length];let q,tries=0;do{q=question(skill,random);}while(queue.some(x=>x.id===q.id)&&++tries<500);queue.push(q);}return queue;}
function start(skills,mode='practice',original=null,examWorld=null){
 const queue=mode==='lesson'?makeQueue(skills,2):mode==='exam'?makeQueue(skills,examWorld==='capstone'?54:12):mode==='repair'?[...variations(original),question(skills.find(k=>k!==original.skill)??original.skill)]:mode==='conquer'?makeQueue(skills,10):null;
 session={skills,mode,count:0,correct:0,q:queue?.[0]??original??question(chooseSkill(state.records,skills)),result:null,queue,answers:[],examWorld,repairId:original?.id};view='practice';render();
}
function practice(){if(!session){const sk=Object.keys(skillNames),d=state.day;shell(`<div class="up-eyebrow london">DESK CALLS · ${hhmm(d.clock)}</div><h1>Colleagues ask. You answer.</h1><p>Untimed practice targets weak and due skills. Conquer mixes ten questions. Calculations and decisions build separate mastery; there is no speed gate.</p><div class="row"><button class="btn gold" id="mixed">Adaptive mixed practice</button><button class="btn" id="conquer">Conquer · 10 questions</button></div><div class="grid skills" style="margin-top:20px">${sk.map(k=>{const m=mastery(state.records[k]),[name,,c]=colleague(worldOf(k));return `<div class="panel skill-card"><div class="panel-head"><span class="${c}">${name.toUpperCase()} ASKS</span><span>${(state.records[k]?.due??Infinity)<=Date.now()?'due':state.records[k]?'':'new'}</span></div><h3>${skillNames[k]}</h3><div class="track"><i class="bg-${tone(m)}" style="width:${m}%"></i></div><div class="row"><span class="small">${m}% mastery</span><button class="btn subtle" data-skill="${k}" aria-label="Practice ${skillNames[k]}">Practice →</button></div></div>`;}).join('')}</div>`);document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>start([b.dataset.skill]));$('#mixed').onclick=()=>start(sk);$('#conquer').onclick=()=>start(sk.sort(()=>Math.random()-.5),'conquer');return;}
 const finished=session.queue&&session.count>=session.queue.length&&session.result===null;
 if(finished){let note='Review the explanations and keep practicing.';
 if(!session.saved){
 if(session.mode==='exam'){const by={};session.answers.forEach(a=>{by[a.q.skill]??={n:0,c:0};by[a.q.skill].n++;by[a.q.skill].c+=Number(a.correct);});const passed=session.correct>=Math.ceil(session.queue.length*.8)&&Object.values(by).every(x=>x.c>=Math.ceil(x.n*2/3));const old=state.exams[session.examWorld];state.exams[session.examWorld]={passed:passed||old?.passed||false,best:Math.max(session.correct,old?.best??0),total:session.queue.length,at:Date.now()};session.passed=passed;}
 if(session.mode==='repair'){const clean=session.answers.slice(0,4).every(a=>a.correct);const old=state.notebook[session.repairId];const early=Date.now()<(old?.due??0);state=repairResult(state,session.repairId,clean);if(!dueCards().length)state.loop.review=true;session.repairNote=early?'Early practice completed; the spaced-review date has not advanced.':clean?'Clean repair recorded. Three spaced clean repairs clear the card.':'The original and three related variations need independent correct answers. Try again after reviewing.';}
 if(session.mode==='conquer')state.snapshot.bestConquer=Math.max(state.snapshot.bestConquer??0,session.correct);
 session.saved=true;save();}
 if(session.mode==='exam')note=session.passed?'World restored. Continue the expedition.':'Challenge not yet cleared. Review weak skills before trying a fresh set.';
 if(session.mode==='repair')note=session.repairNote;
 shell(`<div class="card"><div class="eyebrow">${session.mode==='exam'?'World challenge':session.mode==='repair'?'Repair run':session.mode==='lesson'?'Two on your own':'Conquer'} complete</div><h1>${session.correct} / ${session.queue.length}</h1><p>${note}</p><button class="btn primary" id="again">Back to the floor</button></div><div class="lesson-list">${session.answers.map(a=>`<div class="card"><strong>${a.correct?'✓':'↺'} ${esc(a.q.prompt)}</strong><p>Your answer: ${esc(a.q.choices?.[Number(a.raw)]??a.raw)}<br>Expected: ${esc(a.q.choices?.[a.q.answer]??a.q.answer)}</p><p>${esc(a.q.explanation)}</p></div>`).join('')}</div>`);$('#again').onclick=()=>{session=null;view='floor';render();};return;}
 const q=session.q,exam=session.mode==='exam',[name,role,c]=colleague(worldOf(q.skill)),d=state.day,r=session.result,n=session.queue?.length;
 const runLabel={exam:'LICENCE EXAM',conquer:'CONQUER RUN',repair:'REPAIR RUN',lesson:'TWO ON YOUR OWN',practice:'ADAPTIVE'}[session.mode];
 const shown=[...new Set([q.skill,...session.skills])].slice(0,6);
 shell(`<div class="calls"><div class="stack"><div class="panel-head"><span class="up-eyebrow london">${d.session==='closed'?'AFTER HOURS':sessions.find(x=>x[0]===d.session)[3].toUpperCase()} · ${n?`DESK CALL ${session.count+(r?0:1)} OF ${n} · `:''}${runLabel}</span><span>untimed · ${exam?'explanations at the end':'explanations now'}</span></div>
 <div class="call"><div class="avatar av-${c}" aria-hidden="true">${name[0]}</div><section class="bubble"><div class="label">${name.toUpperCase()} · ${role.toUpperCase()} · ${esc(skillNames[q.skill].toUpperCase())}</div><h2>${esc(q.prompt)}</h2>
 ${r?'':`<form id="answer-form">${q.choices?`<fieldset class="choices"><legend>Choose the best supported answer</legend>${q.choices.map((x,i)=>`<label><input type="radio" name="answer" value="${i}" required><span>${esc(x)}</span></label>`).join('')}</fieldset>`:'<label class="field">Your answer <input id="answer" type="number" step="any" required autocomplete="off" inputmode="decimal"></label>'}<button class="btn primary">Check</button></form>`}</section></div>
 ${r?`<div class="feedback ${exam?'':r.correct?'good':'bad'}" role="status"><div class="feedback-head"><strong>${exam?'Answer recorded.':r.correct?'Correct — you have the reasoning.':'Let’s repair the reasoning.'}</strong>${exam?'':`<span class="${r.after>r.before?"up":r.after<r.before?"down":"muted"}">${esc(skillNames[q.skill])} ${r.before}% → ${r.after}%</span>`}</div>${exam?'':`<p>Your answer: ${esc(q.choices?.[Number(r.raw)]??r.raw)} · Expected: ${esc(q.choices?.[q.answer]??q.answer)}</p><p>${esc(q.explanation)}</p>${!r.correct?'<p class="small">Saved to Ari’s risk bench for spaced repair.</p>':''}`}<div class="row"><button class="btn gold" id="next">${session.queue&&session.count===session.queue.length?'See results':'Next call ▸'}</button>${session.from==='desk'?'<button class="btn subtle" id="back-desk">Back to the desk</button>':''}</div></div>`:''}
 <p class="small">Same engine: adaptive practice picks weak and due skills; a wrong answer goes to Ari’s risk bench. Calls interrupt the desk only when you ask for them. Mastery needs varied examples. Challenges show explanations at the end. Repair runs include an original, three variations, and one transfer question.</p></div>
 <div class="stack">${n?`<div class="panel"><h3 class="label">This run</h3><div class="dots">${session.queue.map((_,i)=>{const a=session.answers[i];return `<i class="${!a?'':exam?'bg-gold':a.correct?'bg-up':'bg-down'}"></i>`;}).join('')}</div><div class="panel-head" style="margin-top:6px"><span>${session.answers.length} answered${exam?'':` · ${session.correct} correct`}</span>${session.mode==='conquer'?'<span class="gold">mission: 8 of 10</span>':''}</div></div>`:''}<div class="panel grow"><h3 class="label">Skills on the floor today</h3>${shown.map(k=>meter(skillNames[k],mastery(state.records[k]),`<em>${(state.records[k]?.due??Infinity)<=Date.now()?'due':state.records[k]?'':'new'}</em>`)).join('')}<p class="small">Mastery = recency-weighted accuracy, capped by distinct examples (unchanged). Bars turn gold at 70% — licence-ready.</p></div></div></div>`);
 if(r){$('#next').onclick=()=>{session.result=null;session.q=session.queue?.[session.count]??question(chooseSkill(state.records,session.skills));render();$('#answer')?.focus();};if($('#back-desk'))$('#back-desk').onclick=()=>{session=null;view='desk';render();};}
 else{$('#answer-form').onsubmit=e=>{e.preventDefault();const raw=q.choices?$('input[name=answer]:checked')?.value:$('#answer').value;if(raw===undefined)return;const correct=grade(q,raw),before=mastery(state.records[q.skill]);state=record(state,q,correct);state.snapshot.answers=(state.snapshot.answers??0)+1;state.snapshot.correct=(state.snapshot.correct??0)+Number(correct);if(!correct&&state.notebook[q.id]&&!state.notebook[q.id].flaggedDay)state.notebook[q.id].flaggedDay=state.day.n;save();session.result={raw,correct,before,after:mastery(state.records[q.skill])};session.answers.push({q,raw,correct});session.count++;session.correct+=Number(correct);render();$('#next').focus();};}
}
const countWord=n=>['Nothing','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten'][n]??String(n);
const inDays=t=>{const d=Math.ceil((t-Date.now())/86400000);return d<=1?'tomorrow':`in ${d} days`;};
function notebook(){const now=Date.now(),entries=Object.entries(state.notebook),due=entries.filter(([,q])=>(q.due??0)<=now),later=entries.filter(([,q])=>(q.due??0)>now).sort((a,b)=>a[1].due-b[1].due),st=state.streak,idx=id=>entries.findIndex(([k])=>k===id);
 if(!due.length&&!state.loop.review){state.loop.review=true;save();}
 const flag=([id,q],i)=>`<article class="panel flag-card"><div class="panel-head"><span class="down">${esc((skillNames[q.skill]??'Practice').toUpperCase())}${q.flaggedDay?` · FLAGGED DAY ${q.flaggedDay}`:''}</span><span>${q.clean??0} / 3 clean repairs · due now</span></div><p class="flag-q">${esc(q.prompt)}</p><div class="row"><button class="btn ${i===0?'gold':''}" data-repair="${idx(id)}">Repair run · 5 questions</button><span class="small">original + 3 variations + 1 transfer</span></div></article>`;
 shell(`<div class="review"><div class="stack"><div><div class="up-eyebrow newyork">NEW YORK · ${hhmm(state.day.clock)} · RISK REVIEW WITH ARI</div><h1>${due.length?`${countWord(due.length)} flagged. Clear ${due.length===1?'it':'them'} before close.`:'Nothing due. The bench is clear.'}</h1><p>Each repair uses the original, three related variations, and a transfer question. Three clean core repairs, scheduled now → 3 days → 7 days, clear the card. Early practice does not advance the schedule.</p></div>
 ${due.length?due.map(flag).join(''):`<div class="panel empty"><h2>The bench is clear.</h2><p>Mistakes from practice appear here automatically.</p></div>`}
 <section class="panel how"><h2 class="label">How a repair run works</h2><div class="steps">${[['1','Original','down'],['2–4','Three same-skill variations','newyork'],['5','Transfer from a neighbour skill','london'],['✓','4/4 core = clean','up'],['×3','now → +3d → +7d clears','gold']].map(([n,t,c])=>`<div><b class="${c}">${n}</b><span>${t}</span></div>`).join('')}</div><p class="small">First four correct = clean repair. Three clean repairs, spaced now → 3 days → 7 days, clear the flag. Early runs don’t advance the clock.</p></section></div>
 <div class="stack"><section class="streak"><div class="panel-head"><div><div class="up-eyebrow newyork">REVIEW STREAK</div><strong class="big" id="streak-days">${st.current} day${st.current===1?'':'s'}</strong></div><span class="soft">Reviews cleared on time<br>Best: ${st.best}</span></div><div class="cells" aria-hidden="true">${Array.from({length:14},(_,i)=>`<i class="${i>=14-Math.min(14,st.current)?'bg-newyork':''}"></i>`).join('')}</div><p class="small">A day counts when every due review is cleared before New York close. Nothing to review counts too.</p></section>
 <section class="panel grow"><h2 class="label">On the bench · upcoming</h2><div class="upcoming">${later.map(([id,q])=>`<button class="up-row" data-repair="${idx(id)}" aria-label="Early practice: ${esc(skillNames[q.skill]??'Practice')}"><b class="london">${inDays(q.due)}</b><span class="grow">${esc(skillNames[q.skill]??'Practice')}</span><small>${q.clean??0} / 3 clean</small></button>`).join('')}${(state.reviewHistory??[]).slice(-2).reverse().map(r=>`<div class="up-row"><b class="up">cleared</b><span class="grow">${esc(skillNames[r.id.split(':')[0]]??'Repair')}</span><small>${new Date(r.at).toLocaleDateString()} ✓</small></div>`).join('')}${later.length||state.reviewHistory?.length?'':'<p class="small">Nothing scheduled.</p>'}</div></section>
 <section class="says says-gold"><div class="up-eyebrow">ARI SAYS</div><p>“A flag isn’t a punishment. It’s the one place where a wrong answer is worth more than a right one.”</p></section></div></div>`);
 document.querySelectorAll('[data-repair]').forEach(b=>b.onclick=()=>{const q=entries[Number(b.dataset.repair)][1],w=worldOf(q.skill);start(w.skills,'repair',q);});}
const px=i=>70+i*41,py=mid=>170-(mid-1.1)*25000;
function chart(){const sc=scenarios[sim.scenario],q=quoteAt(sim.tick,sim.scenario),points=Array.from({length:sim.tick+1},(_,i)=>{const x=quoteAt(i,sim.scenario);return {x:px(i),y:py((x.bid+x.ask)/2)};}),last=points.at(-1),events=sc.calendar.filter(e=>e.step<11);
 return `<svg class="chart" viewBox="0 0 560 300" role="img" aria-label="Synthetic EUR/USD midpoint quotes through step ${sim.tick}. Current bid ${q.bid}, ask ${q.ask}.${events.map(e=>` ${e.title} at step ${e.step}.`).join('')}"><g stroke="#1a2f4a" fill="none"><path d="M30 60H540M30 120H540M30 180H540M30 240H540"/></g><g stroke="#243d5a" stroke-dasharray="4 6" fill="none"><path d="${[0,2,4,6,8,10].map(i=>`M${px(i)} 30V270`).join('')}"/></g>${events.map(e=>`${e.impact==='high'?`<rect x="${px(e.step)-30}" y="30" width="60" height="240" fill="rgba(255,200,87,.08)"/>`:''}<path d="M${px(e.step)} 30V270" stroke="${e.impact==='high'?'#ffc857':e.impact==='med'?'#5ec8ff':'#b48cff'}" stroke-width="2" stroke-dasharray="6 4"/><text x="${px(e.step)+6}" y="${e.impact==='high'?48:e.impact==='med'?84:120}" fill="${e.impact==='high'?'#ffc857':e.impact==='med'?'#5ec8ff':'#b48cff'}" font-size="11" font-weight="700">${esc(e.title.toUpperCase())} · step ${e.step}</text>`).join('')}<text x="36" y="22" fill="#9fb3c8" font-size="11">EUR/USD · synthetic scenario · no future quotes shown</text><polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#64e8c4" stroke-width="3"/><circle cx="${last.x}" cy="${last.y}" r="6" fill="#64e8c4"/><text x="${Math.min(last.x+8,490)}" y="${last.y-8}" fill="#eef4f7" font-size="12" font-weight="700">${((q.bid+q.ask)/2).toFixed(5)}</text><text x="36" y="292" fill="#9fb3c8" font-size="10">step 0</text><text x="505" y="292" fill="#9fb3c8" font-size="10">step 11</text></svg>`;}
const checkRows=p=>{const e=p.event;return [['Hypothesis',p.checks[0]?'states what you expect and why':'say what you expect and why — “I expect … because …”'],['Invalidation',p.checks[1]?'names the price / event that proves it wrong':'name a price level or an “if …” that proves it wrong'],['Size vs budget',`${money(p.planned,2)} planned stop risk. `+(p.checks[2]?(e?`Under 0.6% (${money(p.cap,2)}) before the ${e.spreadPips}-pip ${e.title.toLowerCase()} at step ${e.step}.`:`Within the 1% budget (${money(p.budget,2)}).`):p.planned>p.budget?`Over the 1% budget (${money(p.budget,2)}); the desk will refuse it. Suggest ${p.suggestedUnits.toLocaleString('en-US')}.`:e?`The ${e.spreadPips}-pip ${e.title.toLowerCase()} spread at step ${e.step} makes a gap fill likely. Suggest ${p.suggestedUnits.toLocaleString('en-US')}.`:'Enter whole units and a stop.')],['Cost acknowledged',`round trip ${money(p.cost,2)} at the current ${p.spreadPips}-pip spread${p.checks[3]?'':' — mention it or tick the box'}`]];};
function officer(p){return `<div class="officer-head"><div><div class="up-eyebrow gold">RISK OFFICER · ARI</div><h2>Plan quality</h2></div><div class="ring" role="img" aria-label="Plan quality ${p.score} of 4"><span id="plan-score">${p.score}/4</span></div></div><ul class="checks">${checkRows(p).map(([t,d],i)=>`<li class="${p.checks[i]?'ok':'flag'}"><span aria-hidden="true">${p.checks[i]?'✓':'!'}</span><div><b>${t}</b> <span class="muted">${esc(d)}</span><span class="screen-reader">${p.checks[i]?' — passed':' — needs work'}</span></div></li>`).join('')}</ul>`;}
function readTicket(){return {side:document.querySelector('input[name=side]:checked')?.value??'buy',units:Number($('#units').value),stopPips:Number($('#stop').value),reason:$('#reason').value,ackCost:$('#ack-cost').checked};}
function deskScreen(){const q=quoteAt(sim.tick,sim.scenario),floating=pnl(sim.position,q),sc=scenarios[sim.scenario],d=state.day,spread=((q.ask-q.bid)/.0001),ahead=sc.calendar.find(e=>e.spreadPips&&e.step>sim.tick),today=state.journal.filter(l=>l.day===d.n),sessionName=d.session==='closed'?'AFTER HOURS':sessions.find(x=>x[0]===d.session)[3].toUpperCase();
 const right=sim.finished?`<section class="panel"><h2>Mission complete</h2><p>${sim.logs.length?'Review each plan and outcome below.':'You observed the whole scenario without taking exposure. Staying out is a valid decision.'}</p><p>Did you distinguish planned stop risk from actual loss? Did your plan have evidence, or only a guess?</p><button class="btn" id="restart">New practice account</button></section>`
 :sim.position?`<section class="panel"><h2>Open position</h2><p>${sim.position.side.toUpperCase()} ${sim.position.units.toLocaleString()} EUR</p><p>Entry ${sim.position.entry.toFixed(5)}<br>Stop trigger ${sim.position.stop.toFixed(5)}<br>Unrealized P/L ${money(floating,2)}<br>Reserved margin ${money(sim.position.margin,2)}</p><p>${esc(sim.position.reason)}</p>${Number.isInteger(sim.position.plan)?`<p class="small">Ari approved this plan at ${sim.position.plan}/4. The score stays with the plan, whatever the outcome.</p>`:''}<button class="btn" id="close">Close at current quote</button></section>`
 :observe?`<section class="panel"><h2>Observing</h2><p>No exposure while you watch the tape. Stop observing to write a plan.</p></section>`
 :`<form id="trade" class="stack" novalidate><section class="panel ticket"><h2>Order ticket</h2><fieldset class="side-pick"><legend class="screen-reader">Direction</legend><label class="buy"><input type="radio" name="side" value="buy" checked><span>Buy EUR</span></label><label class="sell"><input type="radio" name="side" value="sell"><span>Sell EUR</span></label></fieldset><div class="pair"><label class="field">Units (EUR)<input id="units" type="number" min="1" step="1" value="10000" required inputmode="numeric"></label><label class="field">Stop (pips)<input id="stop" type="number" min="1" max="1000" step="any" value="20" required inputmode="decimal"></label></div><label class="field">Why enter · what invalidates it?<textarea id="reason" minlength="10" maxlength="500" required placeholder="State your hypothesis and uncertainty…"></textarea></label><label class="ack"><input type="checkbox" id="ack-cost"> <span id="cost-line"></span></label></section><section class="panel officer" aria-live="polite"><div id="officer"></div><div class="row"><button class="btn gold grow">Approve &amp; open ▸</button><button type="button" class="btn subtle" id="fix-size">Fix size</button></div><p class="small">Approval scores the <i>plan</i>, not the outcome. It feeds the league; it never feeds mastery. A legal trade always opens; “Fix size” is a suggestion.</p></section></form>`;
 shell(`<div class="desk-head"><div><div class="up-eyebrow">${sessionName} · STEP ${sim.tick} OF 11 · ${sc.name.toUpperCase()}</div><h1>EUR/USD desk</h1></div><div class="speed" role="group" aria-label="Desk clock">${[[0,'⏸','Pause'],[1,'▶ 1×','Play at 1×'],[3,'▶▶ 3×','Play at 3×']].map(([v,l,a])=>`<button data-speed="${v}" aria-label="${a}" aria-pressed="${d.speed===v}">${l}</button>`).join('')}<button id="advance" ${sim.finished?'disabled':''}>${sim.position?'Step ▸':'Observe next ▸'}</button>${sim.position||sim.finished?'':`<button id="observe" aria-pressed="${observe}">${observe?'Stop observing':'Observe only'}</button>`}</div><div class="chips"><div class="chip"><strong>${money(sim.balance,2)}</strong><span>BALANCE</span></div><div class="chip"><strong>${money(sim.balance+floating,2)}</strong><span>EQUITY</span></div><div class="chip"><strong class="gold">${money(sim.balance*.01)}</strong><span>1% RISK BUDGET</span></div></div></div>
 <div class="row scenario-row"><label class="field inline">Scenario<select id="scenario" ${sim.position?'disabled':''}>${Object.entries(scenarios).map(([id,x])=>`<option value="${id}" ${sim.scenario===id?'selected':''}>${x.name}</option>`).join('')}</select></label><p class="small">${sc.description} Manage a ${money(sim.balance)} practice account across 12 synthetic quotes. You can observe without trading. This repeatable teaching scenario is not a strategy backtest. The clock runs only while a position is open or you are observing; pause any time.</p></div>
 ${message?`<div class="toast" role="alert">${esc(message)}</div>`:''}<div class="desk"><div class="stack"><section class="chart-box">${chart()}<div class="quote"><div class="bid"><span>BID · SELL EUR</span><strong>${q.bid.toFixed(5)}</strong></div><div class="ask"><span>ASK · BUY EUR</span><strong>${q.ask.toFixed(5)}</strong></div><p class="small">Spread: ${spread.toFixed(1)} pips${ahead?` · widens to ${ahead.spreadPips} at the ${ahead.title.toLowerCase()}`:''}. No commission or overnight financing in this short scenario.</p></div></section><div class="desk-foot"><section class="panel"><h2 class="label">Desk call</h2><p class="news">Jules: “Spread is ${spread.toFixed(1)} pips now. Want a spread-cost call before you size?” <button class="link gold" id="desk-call">Take the call ▸</button></p></section><section class="panel"><h2 class="label">Journal · today</h2>${today.length?`<ul class="mini-journal">${today.slice(-3).reverse().map(l=>`<li>${esc(l.summary.split('. Plan:')[0])}</li>`).join('')}</ul>`:'<p class="news muted">No positions yet. Observation counts.</p>'}</section></div><p class="notice">Stops fill at the next available executable quote. A gap can exceed your planned loss.</p><details><summary>Scenario rules</summary><p class="small">EUR/USD, USD account, one position at a time. Initial margin = entry notional ÷ 20. Liquidation occurs at a quoted tick if equity ≤ 50% of reserved initial margin. Planned stop risk is capped at 1% of balance. These are illustrative rules, not universal broker requirements. No partial fills, intratick path, financing, or variable commissions are modeled. Spread widens during the scenario.</p></details></div><div class="stack">${right}</div></div><div class="section-head"><h2>Decision journal</h2><span class="small">Outcomes do not award mastery</span></div>${state.journal.length?state.journal.slice(-8).reverse().map(l=>`<div class="card" style="margin-bottom:12px"><p>${esc(l.summary)}</p></div>`).join(''):'<p>Closed positions and completed observation missions appear here.</p>'}`);
 $('#scenario').onchange=e=>{sim=desk(e.target.value,account());observe=false;message='';render();};$('#advance').onclick=()=>deskUpdate(advance);document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{state.day.speed=Number(b.dataset.speed);save();render();});if($('#observe'))$('#observe').onclick=()=>{observe=!observe;render();};if($('#close'))$('#close').onclick=()=>deskUpdate(x=>closeTrade(x));if($('#restart'))$('#restart').onclick=()=>{sim=desk(sim.scenario,account());observe=false;render();};
 $('#desk-call').onclick=()=>{start(['spread']);session.from='desk';render();};
 if($('#trade')){const refresh=()=>{const t=readTicket(),p=planScore(t,sim);$('#officer').innerHTML=officer(p);$('#cost-line').textContent=`Round trip at the current spread: ${money(p.cost,2)} (${p.spreadPips} pips). I’ve counted this cost.`;$('#fix-size').disabled=p.checks[2]||!p.suggestedUnits;return p;};refresh();$('#trade').addEventListener('input',refresh);
  $('#fix-size').onclick=()=>{const p=refresh();if(p.suggestedUnits){$('#units').value=p.suggestedUnits;refresh();$('#units').focus();}};
  $('#trade').onsubmit=e=>{e.preventDefault();const t=readTicket(),p=planScore(t,sim);try{const next=openTrade(sim,t);sim={...next,position:{...next.position,plan:p.score}};state.plans=[...(state.plans??[]),{at:Date.now(),day:state.day.n,score:p.score,checks:p.checks,tradeIndex:null}].slice(-200);save();message='';render();}catch(err){message=err.message;const banner=document.createElement('div');banner.className='toast';banner.setAttribute('role','alert');banner.textContent=message;$('#trade').querySelector('.toast')?.remove();$('#trade').prepend(banner);}};}}
function deskUpdate(fn){const before=sim.logs.length;sim=fn(sim);const added=sim.logs.slice(before);if(sim.finished&&sim.logs.length===0)added.push({summary:'Observation mission completed without opening a position. No capital exposed.'});if(sim.finished){observe=false;state.loop.desk=true;}const start=state.journal.length;state.journal=[...state.journal,...added.map(l=>({...l,day:state.day.n}))].slice(-100);
 // Link each closed trade back to the plan Ari scored when it opened.
 added.forEach((l,i)=>{if(!Number.isInteger(l.plan))return;const plan=[...(state.plans??[])].reverse().find(p=>p.tradeIndex===null&&p.day===state.day.n);if(plan)plan.tradeIndex=Math.min(start+i,state.journal.length-1);});
 state=setClock(state,480+sim.tick*35);save();message='';render();}
// Speed 0/1/3 drives advance() only on the desk, and only while a position is open or observe mode is on.
function syncTicker(){const ms=view==='desk'&&state.day.speed>0&&!sim.finished&&(sim.position||observe)?Math.round(4000/state.day.speed):0;if(ticker?.ms===ms)return;clearInterval(ticker?.id);ticker=ms?{ms,id:setInterval(()=>deskUpdate(advance),ms)}:null;}
const reflections=[['plan','Followed the plan'],['luck','Got lucky'],['changed','Changed my mind']];
function closeScreen(){if(!state.loop.close||state.day.session!=='closed'){state=closeDay(state,Date.now());save();}
 const n=state.day.n,trades=state.journal.map((l,i)=>[l,i]).filter(([l])=>l.day===n&&Number.isFinite(l.profit)),open=account(),net=trades.reduce((t,[l])=>t+l.profit,0),spreadPaid=trades.reduce((t,[l])=>t+(l.spreadCost??0),0),planned=trades.reduce((t,[l])=>t+(l.planned??0),0),lost=trades.reduce((t,[l])=>t+Math.max(0,-l.profit),0);
 const snap=state.snapshot.records??{},moved=Object.keys(skillNames).map(k=>[k,snap[k],mastery(state.records[k])]).filter(([k,a,b])=>a===undefined?state.records[k]:a!==b).sort((x,y)=>Math.abs(y[2]-(y[1]??0))-Math.abs(x[2]-(x[1]??0))).slice(0,6);
 const todayPlans=(state.plans??[]).filter(p=>p.day===n),avgPlan=todayPlans.length?(todayPlans.reduce((t,p)=>t+p.score,0)/todayPlans.length).toFixed(1):'—',due=dueCards().length,cleared=Math.max(0,(state.reviewHistory??[]).length-(state.snapshot.reviews??0));
 const w=currentWorld(),ready=!state.exams[w.id]?.passed&&w.skills.every(k=>mastery(state.records[k])>=70),nextSc=scenarios[Object.keys(scenarios)[n%Object.keys(scenarios).length]];
 shell(`<div class="close"><div class="stack"><div><div class="up-eyebrow newyork">NEW YORK CLOSE · 17:00 · DAY ${n}</div><h1>Desk closed. Here’s the day.</h1></div>
 <section class="panel"><h2 class="label">Practice P&amp;L ledger</h2><div class="ledger"><div><span>Opening balance</span><b>${money(open,2)}</b></div>${trades.map(([l],i)=>`<div><span>Trade ${i+1} · ${l.side} ${l.units.toLocaleString('en-US')} EUR · ${esc((l.why??'closed').toLowerCase())}</span><b class="${l.profit>=0?'up':'down'}">${l.profit>=0?'+':''}${money(l.profit,2)}</b></div>`).join('')}${trades.length?`<div><span>Spread paid across ${trades.length===1?'the trade':`${trades.length} trades`}</span><b class="muted">${money(spreadPaid,2)}</b></div><div><span>Planned stop risk vs realised loss</span><b class="muted">${money(planned)} → ${money(lost)}</b></div>`:'<div><span>No trades today. Observation counts.</span><b class="muted">—</b></div>'}<div class="total"><span>Closing balance</span><b class="${net>=0?'up':'down'}">${money(open+net,2)}</b></div></div><p class="small">Practice funds. Outcome shown for honesty, not reward — nothing on this card changes mastery or licences. Each scenario restarts the practice account; this ledger sums today’s closed trades against one opening balance.</p></section>
 <section class="panel grow"><h2 class="label">Journal review · one question per trade</h2>${trades.length?trades.map(([l,idx],i)=>`<div class="reflect"><small>Trade ${i+1} · ${l.side} ${l.units.toLocaleString('en-US')} EUR${l.stopPips?` · stop ${l.stopPips}`:''} · closed ${l.profit>=0?'+':''}${money(l.profit,2)}${Number.isInteger(l.plan)?` · plan ${l.plan}/4`:''}</small><p>${esc((l.summary.split('Plan: ')[1]??'').slice(0,160))} <b>${l.profit>=0?'Was the plan followed, or did the profit decide?':'Was the loss inside the plan, or did the plan change?'}</b></p><div class="pills" role="group" aria-label="Reflection for trade ${i+1}">${reflections.map(([v,t])=>`<button class="chip-btn" data-reflect="${idx}" data-value="${v}" aria-pressed="${l.reflection===v}">${t}</button>`).join('')}</div></div>`).join(''):'<p class="news muted">No trades to review. Staying out is a valid decision.</p>'}</section></div>
 <div class="stack"><section class="panel"><div class="panel-head"><h2 class="label">Mastery moved today</h2><span class="up">${state.snapshot.answers??0} answers · ${state.snapshot.correct??0} correct</span></div>${moved.length?moved.map(([k,a,b])=>`<div class="meter gain"><span>${skillNames[k]}</span><div class="track"><i class="bg-${b<(a??0)?'down':tone(b)}" style="width:${b}%"></i>${a!==undefined?`<u style="left:${a}%"></u>`:''}</div><b class="${b<(a??0)?'down':tone(b)}">${a===undefined?`new · ${b}`:`${a} → ${b}${b<a?' ↓':''}`}</b></div>`).join(''):'<p class="news muted">No mastery changes today. Desk calls and briefings move these bars; P&amp;L never does.</p>'}</section>
 <section class="panel"><h2 class="label">Day ${n} scorecard</h2><div class="scorecard">${[[avgPlan,'avg plan quality','gold'],[`${cleared}/${cleared+due}`,'review cards cleared','up'],[state.streak.current,'day streak','newyork'],[state.lessons.length-(state.snapshot.lessons??0),'lessons explored','asia'],[(state.blueprints??[]).filter(b=>b.frozenDay===n).length,'blueprints frozen','muted'],[processScore(state),'process score','mint']].map(([v,t,c])=>`<div><strong class="${c}">${v}</strong><span>${t}</span></div>`).join('')}</div></section>
 <section class="up-next tone-gold grow"><div class="up-eyebrow">TOMORROW · DAY ${n+1}</div><h1>${ready?`${w.title} licence exam is open`:`Tomorrow’s tape: ${nextSc.name}`}</h1><p>${ready?`All ${w.skills.length} skills ≥ 70%. ${w.id==='capstone'?54:12} questions, explanations at the end, 80% to pass. ${unlockLine(w)}`:`${nextSc.description} ${nextSc.calendar.filter(e=>e.impact==='high').map(e=>`${e.title} at step ${e.step}.`).join(' ')}`}</p><div class="row"><button class="btn gold" id="start-day">Start Day ${n+1} ▸</button><button class="link muted" id="export">Export progress</button><label class="link muted" for="import">Import</label><input type="file" id="import" accept="application/json" class="screen-reader"><button class="link muted" id="switch-player">Switch player</button></div></section></div></div>`);
 document.querySelectorAll('[data-reflect]').forEach(b=>b.onclick=()=>{const l=state.journal[Number(b.dataset.reflect)];l.reflection=l.reflection===b.dataset.value?undefined:b.dataset.value;if(!l.reflection)delete l.reflection;save();render();});
 $('#start-day').onclick=()=>{state=startDay(state,Date.now());sim=desk(todayScenario(),account());observe=false;session=null;save();view='floor';render();};$('#switch-player').onclick=()=>players?playerDialog():null;wireBackup();}
function guide(){shell(`<div class="eyebrow">Field guide / Evidence before confidence</div><h1>Know what a model can tell you.</h1><section class="card lesson"><h2>Three categories of knowledge</h2><p><strong>Mechanics:</strong> quote conventions and calculations can have definite answers.</p><p><strong>Models:</strong> parity and option pricing depend on assumptions. A forward price is not automatically a forecast of the future spot rate.</p><p><strong>Hypotheses:</strong> chart patterns, carry rules, and predictive indicators require tests against costs and unseen data. An institutional story is not proof of an edge.</p><h2>Corrections carried into this curriculum</h2><p>Uncovered currency positions retain FX risk. Covered parity deviations reflect funding and balance-sheet frictions. Carry positions are difficult to measure. VPIN’s predictive claims are disputed. A profitable backtest may be overfit.</p><h2>Offline play</h2><p>After the first successful online load caches the game, it can open offline on this browser. Add this page to your home screen using your browser’s install or share menu. External reference links still need internet. Export progress to move it between devices.</p><h2>Reference shelf</h2>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p class="small">Sources reviewed September 2026. Foundation exercises and scenarios are original teaching examples, not live prices. All twelve worlds include lessons and assessments. Research labs are simplified educational tools, not production pricing or execution systems.</p></section>`);}
function render(){if(view==='desk'&&state.day.clock<480){state=setClock(state,480);save();}if(view==='notebook'&&state.day.clock<900){state=setClock(state,900);save();}({floor,close:closeScreen,worlds:worldsScreen,world:worldScreen,lesson:lessonScreen,practice,notebook,desk:deskScreen,labs:labsScreen,sources:guide}[view]??floor)();syncTicker();}
let lab='hedge',labResult=null,research={seed:123,frozen:null,revealed:false};
function fields(defs){return defs.map(([id,label,value,step='any',min,max])=>`<label class="field">${label}<input id="${id}" name="${id}" type="number" value="${value}" step="${step}" ${min!==undefined?`min="${min}"`:''} ${max!==undefined?`max="${max}"`:''} required></label>`).join('');}
function labsScreen(){
 const names={hedge:'Forward hedge builder',options:'FX option workshop',research:'Strategy test bench',flow:'Order-flow observatory'};
 shell(`<div class="eyebrow">Research labs / Change one variable</div><h1>Put the theory to work.</h1><p>Build a hedge, price an option, test a rule, and inspect order flow. Every result is conditional on the displayed assumptions.</p><div class="row">${Object.entries(names).map(([id,n])=>`<button class="btn ${lab===id?'primary':''}" data-lab="${id}">${n}</button>`).join('')}</div><section id="lab-panel" class="card" style="margin-top:24px"></section>`);
 document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{lab=b.dataset.lab;labResult=null;render();});
 const panel=$('#lab-panel');
 if(lab==='hedge'){
 panel.innerHTML=`<h2>A workshop’s euro invoice</h2><p>Your USD-funded city owes a fixed EUR invoice in the future. Compare a forward hedge with leaving the payment exposed.</p><form id="lab-form"><div class="grid">${fields([['spot','Spot (USD per EUR)',1.1,.00001,.01,100],['domestic','USD simple annual rate (%)',5,.01,-10,100],['foreign','EUR simple annual rate (%)',3,.01,-10,100],['years','Maturity (years)',1,.01,.01,10],['invoice','Invoice (EUR)',10000,1,1,10000000]])}</div><button class="btn primary">Build the hedge</button></form><div id="lab-result" aria-live="polite"></div>`;
 $('#lab-form').onsubmit=e=>{e.preventDefault();const S=+$('#spot').value,rd=+$('#domestic').value/100,rf=+$('#foreign').value/100,T=+$('#years').value,n=+$('#invoice').value;if(1+rf*T<=0||1+rd*T<=0){$('#lab-result').textContent='These simple-rate accumulation factors must be positive.';return;}const F=S*(1+rd*T)/(1+rf*T);$('#lab-result').innerHTML=`<div class="callout"><h3>Contract rate: ${F.toFixed(5)} USD/EUR</h3><p>Locked invoice cost: $${(F*n).toFixed(2)}</p><p>F = S × (1 + rdT) / (1 + rfT). Matched maturity, simple rates, no spread, basis, or fees.</p></div><div class="table-scroll"><table><thead><tr><th>Illustrative future spot</th><th>Unhedged payment</th><th>Forward payment</th></tr></thead><tbody>${[.9,1,1.1].map(k=>`<tr><td>${(S*k).toFixed(5)}</td><td>$${(S*k*n).toFixed(2)}</td><td>$${(F*n).toFixed(2)}</td></tr>`).join('')}</tbody></table></div><p>The forward fixes a contractual exchange price; it may cost more or less than the eventual spot conversion. These scenarios have no assigned probabilities.</p>`;state.labs.hedge=true;save();};
 }
 if(lab==='options'){
 panel.innerHTML=`<h2>Garman–Kohlhagen workshop</h2><p>European call and put values per EUR in a USD quote. Rates are continuously compounded. Volatility is annualized.</p><form id="lab-form"><div class="grid">${fields([['spot','Spot S (USD/EUR)',1.1,.0001,.01,100],['strike','Strike K (USD/EUR)',1.1,.0001,.01,100],['years','Maturity T (years)',1,.01,0,50],['domestic','USD continuous rate (%)',5,.01,-100,100],['foreign','EUR continuous rate (%)',3,.01,-100,100],['vol','Annual volatility (%)',10,.1,0,500]])}</div><button class="btn primary">Price and stress the option</button></form><div id="lab-result" aria-live="polite"></div>`;
 $('#lab-form').onsubmit=e=>{e.preventDefault();try{const params={S:+$('#spot').value,K:+$('#strike').value,T:+$('#years').value,rd:+$('#domestic').value/100,rf:+$('#foreign').value/100,vol:+$('#vol').value/100},x=optionPrice(params);$('#lab-result').innerHTML=`<div class="stats"><div class="stat"><strong>$${x.call.toFixed(5)}</strong><span>Call per EUR</span></div><div class="stat"><strong>$${x.put.toFixed(5)}</strong><span>Put per EUR</span></div><div class="stat"><strong>${x.forward.toFixed(5)}</strong><span>Model forward USD/EUR</span></div></div><p>Spot call delta: ${x.delta.toFixed(4)} · Vega for +1 percentage point of volatility: $${x.vega.toFixed(5)} per EUR.</p><div class="table-scroll"><table><thead><tr><th>Spot stress</th><th>Call value</th><th>Put value</th></tr></thead><tbody>${[.95,1,1.05].map(k=>{const z=optionPrice({...params,S:params.S*k});return `<tr><td>${(params.S*k).toFixed(5)}</td><td>$${z.call.toFixed(5)}</td><td>$${z.put.toFixed(5)}</td></tr>`;}).join('')}</tbody></table></div><p>Assumes constant rates and volatility, continuous diffusion, European exercise, and frictionless hedging. Smiles, jumps, and actual pricing conventions are omitted. At zero time or volatility, a deterministic limiting value is used; delta is discontinuous at the boundary. These are model prices, not executable quotes.</p>`;state.labs.options=true;save();}catch(err){$('#lab-result').textContent=err.message;}};
 }
 if(lab==='flow'){
 panel.innerHTML=`<h2>Read volume without inventing a motive</h2><p>Three synthetic buckets each contain 1,000 classified units. Change buying in the third bucket. Selling is the remaining volume.</p><form id="lab-form">${fields([['buy','Buy-initiated units in bucket 3',900,1,0,1000]])}<button class="btn primary">Inspect the buckets</button></form><div id="lab-result" aria-live="polite"></div>`;
 $('#lab-form').onsubmit=e=>{e.preventDefault();const buy=+$('#buy').value,buckets=[[600,400],[450,550],[buy,1000-buy]],proxy=buckets.reduce((s,[b,a])=>s+Math.abs(b-a),0)/3000;$('#lab-result').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Bucket</th><th>Buy</th><th>Sell</th><th>Signed imbalance</th></tr></thead><tbody>${buckets.map(([b,a],i)=>`<tr><td>${i+1}</td><td>${b}</td><td>${a}</td><td>${((b-a)/10).toFixed(1)}%</td></tr>`).join('')}</tbody></table></div><div class="callout"><p>Mean absolute bucket imbalance: ${(proxy*100).toFixed(1)}%</p></div><p>This is an educational equal-volume imbalance calculation. It is not a validated VPIN implementation, a probability of informed trading, or a crash forecast. Trade classification and coverage are assumed, not estimated. The VPIN literature is disputed.</p>`;state.labs.flow=true;save();};
 }
 if(lab==='research'){
 panel.innerHTML=`<h2>Freeze the rule. Then reveal the holdout.</h2><p>Synthetic 121-close EUR/USD sample · seed ${research.seed}. Signals see only closes before entry. Each one-interval round trip uses 10,000 EUR; 1 pip of total cost equals $1. No carry, margin, or intrainterval stops.</p><form id="research-form"><div class="grid"><label class="field">Rule<select id="kind" ${research.frozen?'disabled':''}><option value="momentum">Momentum</option><option value="reversion">Mean reversion</option><option value="flat">No trade</option></select></label>${fields([['lookback','Previous closes in signal',research.frozen?.lookback??5,1,2,30],['cost','Total cost per round trip (pips)',research.frozen?.costPips??2,.1,0,100]])}</div><div class="row"><button class="btn primary" ${research.frozen?'disabled':''}>Evaluate training & freeze</button><button type="button" class="btn" id="reveal" ${!research.frozen||research.revealed?'disabled':''}>Reveal later holdout</button><button type="button" class="btn subtle" id="new-data">New synthetic experiment</button></div></form><div id="lab-result" aria-live="polite"></div><p class="small">Every training evaluation is counted: ${state.labs.trials??0}. Repeated experimentation is part of selection, not independent proof of an edge. No result here establishes real-market profitability.</p>`;
 if(research.frozen){$('#kind').value=research.frozen.kind;$('#lookback').disabled=true;$('#cost').disabled=true;showResearch();}
 $('#research-form').onsubmit=e=>{e.preventDefault();research.frozen={kind:$('#kind').value,lookback:+$('#lookback').value,costPips:+$('#cost').value};state.labs.trials=(state.labs.trials??0)+1;save();render();};$('#reveal').onclick=()=>{research.revealed=true;state.labs.research=true;save();render();};$('#new-data').onclick=()=>{research={seed:(Date.now()>>>0),frozen:null,revealed:false};render();};
 }
}
function showResearch(){const prices=series(research.seed),config=research.frozen,train=backtest(prices,{...config,end:70}),test=research.revealed?backtest(prices,{...config,start:70}):null;const row=(n,x)=>`<tr><th>${n}</th><td>$${x.net.toFixed(2)}</td><td>$${x.costs.toFixed(2)}</td><td>${x.drawdown.toFixed(2)}%</td><td>${x.trades}</td></tr>`;$('#lab-result').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Period</th><th>Net P/L</th><th>Costs</th><th>Max drawdown</th><th>Round trips</th></tr></thead><tbody>${row('Training',train)}${test?row('Later holdout',test):'<tr><td colspan="5">Later data withheld until you reveal it.</td></tr>'}${row('No-trade benchmark',{net:0,costs:0,drawdown:0,trades:0})}</tbody></table></div>${test?`<div class="callout"><p>${test.net>0?'This synthetic holdout was profitable.':'This synthetic holdout was not profitable.'} One sample does not establish an edge. Compare results, costs, and selection history.</p></div>`:''}`;}

render();

startUpdates({beforeReload:save});
