import {advancedWorlds} from './advanced-content.js';
export const worlds=[
{id:'harbor',title:'Currency Harbor',subtitle:'Learn the language of exchange.',icon:'◈',skills:['quote','inverse'],mentor:'Mara · Currency navigator',color:'#64e8c4',lessons:[
{id:'base',title:'Two currencies. One price.',what:'EUR/USD = 1.1000 means one euro costs 1.10 US dollars. EUR is the base; USD is the quote currency.',why:'Before a calculation or a trade, identify what one unit means. A rising EUR/USD means the euro strengthens against the dollar; it does not mean both currencies rise.',example:'A city workshop needs €2,000. At 1.1000 USD per EUR, the cost is 2,000 × 1.10 = $2,200 before fees.',rule:'Base units × quote price = quote-currency amount.',skill:'quote'},
{id:'reverse',title:'Turn the exchange around',what:'When you start with the quote currency, divide by the exchange rate to find the base amount.',why:'Units tell you whether to multiply or divide. USD ÷ (USD/EUR) leaves EUR.',example:'A traveler has $550. At EUR/USD 1.1000, 550 ÷ 1.10 = €500, before costs.',rule:'Quote amount ÷ quote price = base-currency units.',skill:'inverse'},
{id:'pairs',title:'A network, not one exchange',what:'FX includes spot trades, forwards, FX swaps, currency swaps, and options. The OTC market is spread across dealers and venues; there is no single complete global spot order book.',why:'A retail screen is one view of the market. A quote, volume display, or candle does not reveal every institution’s orders.',example:'A manufacturer can exchange dollars for euros today (spot) or contract today for an exchange later (forward). The two transactions solve different timing needs.',rule:'Always identify the instrument, currency pair, venue, and time horizon.',skill:'quote'}]},
{id:'execution',title:'Execution District',subtitle:'See what a trade actually costs.',icon:'⌁',skills:['pip','spread'],mentor:'Jules · Execution specialist',color:'#82b6ff',lessons:[
{id:'pips',title:'Small moves, measurable units',what:'A conventional pip is 0.0001 for EUR/USD and 0.01 for many JPY-quoted pairs. A platform may display finer fractional pips.',why:'A pip measures a price change, not a fixed dollar profit. Cash value depends on units and account currency.',example:'EUR/USD 1.1000 → 1.1020 moves 20 pips. For 10,000 EUR units, one pip is 10,000 × 0.0001 = $1 in a USD account.',rule:'Pips = price change ÷ pip size. Quote-currency pip value = base units × pip size.',skill:'pip'},
{id:'costs',title:'The spread is real',what:'You buy the base currency at the ask and sell it at the bid. The ask is normally higher than the bid.',why:'An immediate round trip starts with a cost. Commissions and financing can add to it. Spreads can widen during stress.',example:'Buy 10,000 EUR at 1.1002, sell at 1.1000: 10,000 × (1.1000 − 1.1002) = −$2 before other charges.',rule:'Evaluate results using executable bid/ask prices, not only a midpoint chart.',skill:'spread'},
{id:'orders',title:'An order is an instruction',what:'A market order seeks execution at available prices. A limit order sets a price boundary but may not fill. An ordinary stop becomes executable after its trigger and does not guarantee a fill price.',why:'A chart crossing your stop does not mean a dealer could fill there. Gaps, liquidity, and broker rules matter.',example:'A sell stop at 1.0990 may fill at 1.0974 if that is the next available bid after a gap. A stop-limit could remain unfilled.',rule:'Separate the trigger, the available quote, and the actual fill.',skill:'spread'}]},
{id:'risk',title:'Risk Fortress',subtitle:'Protect the city’s trading desk.',icon:'⬡',skills:['risk','margin'],mentor:'Ari · Risk officer',color:'#f4c57a',lessons:[
{id:'sizing',title:'Size comes from the loss budget',what:'Position size links a loss budget to the distance between entry and a planned stop. The exercise uses a 1% budget; this is a training constraint, not a personal recommendation.',why:'Picking size first can make a reasonable price idea financially dangerous. Real losses can exceed planned stop risk.',example:'$10,000 × 1% = $100. With a 20-pip EUR/USD stop and no costs, units = 100 ÷ (20 × 0.0001) = 50,000 EUR.',rule:'Whole units = floor(loss budget ÷ loss per unit). Allow for costs and gap risk separately.',skill:'risk'},
{id:'collateral',title:'Margin is not your loss limit',what:'Initial margin is collateral needed to support a position. Leverage relates the notional exposure to that collateral. Equity changes as the position gains or loses.',why:'A small margin requirement does not make an exposure small. Liquidation rules vary, and losses may exceed deposited funds.',example:'10,000 EUR at 1.1000 is $11,000 notional. At an illustrative 20:1 limit, initial margin is $550. A 100-pip adverse move costs $100 before other costs.',rule:'Notional ÷ leverage limit = initial margin. Equity = balance + unrealized P/L.',skill:'margin'},
{id:'judgment',title:'A good decision can lose',what:'A winning trade does not prove skill, and a losing trade does not prove a bad decision. Assess the information, rules, costs, and exposure known before the outcome.',why:'Choosing not to trade is valid when the evidence or execution conditions do not support your plan. Several positions can share the same underlying currency risk.',example:'Long EUR/USD and long GBP/USD both involve short USD exposure. Different pair names do not guarantee diversification.',rule:'Record the hypothesis, invalidation condition, size, and costs before seeing the result.',skill:'risk'}]}
];
export const skillNames={quote:'Currency conversion',inverse:'Reverse conversion',pip:'Pip distance',spread:'Spread cost',risk:'Position sizing',margin:'Initial margin'};
const retiredRoadmap=['Chart Observatory','Central Bank Capital','Global Funding Network','Strategy Laboratory','Crisis Archives','Quantitative Academy','Market Microstructure','Research Trials','Capstone Desk'];
export const sources=[
['BIS · 2025 FX turnover and market instruments','https://www.bis.org/publications/202509-commentary-otc-derivatives'],
['CFTC · Forex fraud and retail trading risks','https://www.cftc.gov/LearnAndProtect/AdvisoriesAndArticles/fraudadv_forex.html'],
['CFTC · Understanding retail forex losses','https://www.cftc.gov/LearnAndProtect/AdvisoriesAndArticles/reduce_risk_of_forex_fraud.htm'],
['BIS · Covered parity and funding frictions','https://www.bis.org/publ/work590.htm'],
['BIS · August 2024 carry-trade unwind','https://www.bis.org/publications/bulletin-90-market-turbulence-and-carry-trade-unwind-august-2024'],
['Andersen & Bondarenko · VPIN research dispute','https://www.kellogg.northwestern.edu/academics-research/research/detail/2014/vpin-and-the-flash-crash/'],
['Research paper · Sparse dynamic shrinkage and Meese–Rogoff','https://arxiv.org/html/2507.14408v1']
];

worlds[0].skills.push('quotejudgment'); worlds[1].skills.push('executionjudgment'); worlds[2].skills.push('riskjudgment');
worlds.push(...advancedWorlds);
Object.assign(skillNames,{quotejudgment:'Quote reasoning',executionjudgment:'Order reasoning',riskjudgment:'Risk reasoning',returns:'Percent returns',chartjudgment:'Chart evidence',surprise:'Release surprises',macrojudgment:'Macro reasoning',forward:'Forward pricing',parityjudgment:'Funding & parity',expectancy:'Net expectancy',strategyjudgment:'Strategy evidence',stress:'Stress losses',crisisjudgment:'Crisis decisions',optionpayoff:'Option net payoff',modeljudgment:'Model assumptions',imbalance:'Order imbalance',microjudgment:'Microstructure',rmse:'Forecast error',researchjudgment:'Research integrity',portfolio:'Portfolio stress',capstonejudgment:'Desk judgment'});
export const roadmap=[];
sources.push(
 ['Bank of England · 1992 ERM policy account','https://www.bankofengland.co.uk/quarterly-bulletin/1992/q4/operation-of-monetary-policy'],
 ['SNB · January 2015 minimum-rate decision','https://www.snb.ch/en/publications/communication/press-releases/2015/pre_20150115'],
 ['Federal Reserve · Central-bank swap-line mechanics','https://www.federalreserve.gov/newsevents/pressreleases/swap-lines-faqs.htm'],
 ['BIS · FX fragmentation and execution','https://www.bis.org/publications/qr-201912/fx-trade-execution-complex-and-highly-fragmented'],
 ['AMD quantitative-finance library · Garman–Kohlhagen equations','https://xilinx.github.io/Vitis_Libraries/quantitative_finance/2022.1/methods/garman_kohlhagen.html'],
 ['Meese & Rogoff · Original out-of-sample forecasting study','https://www.sciencedirect.com/science/article/pii/002219968390017X'],
 ['Bailey, Borwein, López de Prado & Zhu · Backtest overfitting','https://www.davidhbailey.com/dhbpapers/backtest-prob.pdf']
);
