import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';import {missions} from '../src/content.js';import {adapters,simulate,insideBay} from '../src/models.js';
const win=new Window({url:'http://localhost:5187',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});win.document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
for(const [k,v]of Object.entries({window:win,document:win.document,localStorage:win.localStorage,navigator:win.navigator,location:win.location,matchMedia:()=>({matches:true}),requestAnimationFrame:()=>0,cancelAnimationFrame:()=>{}}))Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});
await import('../src/app.js');const tick=()=>new Promise(r=>setTimeout(r,5));await tick();await tick();
const $=s=>win.document.querySelector(s);const click=async(s)=>{const e=$(s);assert.ok(e,'Missing '+s);assert.equal(e.disabled,false,'Disabled '+s);e.click();await tick();};const set=async(s,v)=>{const e=$(s);e.value=String(v);e.dispatchEvent(new win.Event('input',{bubbles:true}));await tick();};const save=()=>JSON.parse(localStorage.getItem('science-quest.v1'));const run=id=>save().profiles.find(p=>p.id===save().active).runs[id];
async function answer(value=0){await click(`[data-action="choice"][data-value="${value}"]`);await click('[data-action="check"]');}
async function next(){await click('[data-action="next"]');}
async function open(id){if(!$(`[data-action="start"][data-id="${id}"]`)){await click('[data-action="region"][data-id="'+missions.find(m=>m.id===id).region+'"]');}await click(`[data-action="start"][data-id="${id}"]`);}

test('Full guided flow across all 27 missions, including both transfer contexts',async()=>{for(const m of missions){await click('[data-action="nav"][data-view="explore"]');await open(m.id);assert.equal(run(m.id).stage,'notice');await next();for(const stage of ['predict','build']){assert.equal(run(m.id).stage,stage);await answer();assert.equal($('.feedback').classList.contains('good'),true,m.id+' '+stage);await next();}if(m.adapter==='energy'){for(const [id,val]of [['supply','*'],['demand','*'],['margin','-']]){const el=$('#energy-'+id);el.value=val;el.dispatchEvent(new win.Event('change',{bubbles:true}));await tick();}await click('[data-action=energy-check]');}for(const input of m.compare){await set('#experiment-input',input);await click('[data-action="run"]');}if(m.target&&!m.compare.some(x=>insideBay(simulate(m.adapter,x).value,...m.target))){const model=adapters[m.adapter];let solution;for(let x=model.min;x<=model.max+1e-7;x+=model.step){x=Number(x.toFixed(6));if(insideBay(simulate(m.adapter,x).value,...m.target)){solution=x;break;}}await set('#experiment-input',solution);await click('[data-action="run"]');}await click('[data-action="compare"]');for(const stage of ['compare','explain','transfer1','transfer2']){assert.equal(run(m.id).stage,stage);await answer();await next();}assert.equal(run(m.id).completed,true);assert.equal(Object.values(run(m.id).evidence).filter(Boolean).length,6);assert.match($('#main').textContent,/Demonstrated/);}});

test('Hints do not confer mastery; an independent retry can complete missing evidence',async()=>{await click('[data-action="nav"][data-view="settings"]');$('#profile-name').value='Hint Explorer';$('#new-profile').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('[data-action="nav"][data-view="explore"]');await open('rover-rescue');await next();await click('[data-action="hint"]');await answer();await next();await answer();await next();for(const x of [.1,.3]){await set('#experiment-input',x);await click('[data-action="run"]');}await click('[data-action="compare"]');for(let i=0;i<4;i++){await answer();await next();}assert.equal(run('rover-rescue').evidence.predict,undefined);assert.match($('#main').textContent,/Learning/);await click('[data-action="retry"]');assert.equal(run('rover-rescue').stage,'predict');await answer();assert.equal(run('rover-rescue').evidence.predict,true);assert.equal(run('rover-rescue').hintHistory.length,1);});

test('Profile separation, persistent checkpoint, journal and invention rebuild',async()=>{const before=save();assert.equal(before.profiles.length,2);assert.equal(Object.keys(before.profiles[1].runs).length,1);assert.equal(Object.keys(before.profiles[0].runs).length,27);await click('[data-action="nav"][data-view="explore"]');await click('[data-action="nav"][data-view="test"]');assert.equal(run('rover-rescue').stage,'predict');await click('[data-action="nav"][data-view="lab"]');await click('[data-action="run"]');$('#invention-name').value='Trolley experiment';await click('[data-action="save-invention"]');await click('[data-action="nav"][data-view="journal"]');assert.match($('#main').textContent,/Trolley experiment/);await click('[data-action="load-invention"]');assert.match($('#main').textContent,/Free Lab/);assert.equal($('#experiment-input').value,'0.2');});

test('All four arcade modes complete without awarding mission mastery',async()=>{for(const [id,inputs]of Object.entries({cargo:[.2,.4,.3],signal:[2,5,1],habitat:[20,40,30],buildoff:[.2,.4,.1]})){await click('[data-action="nav"][data-view="arcade"]');await click(`[data-action="arcade-start"][data-id="${id}"]`);for(const input of inputs){await set('#experiment-input',input);await click('[data-action="arcade-test"]');assert.match($('#main').textContent,/Design delivered/);await click('[data-action="arcade-next"]');}assert.match($('#main').textContent,/Challenge complete/);await click('[data-action="arcade-exit"]');}});

test('Save snapshot survives app reinitialization',async()=>{const id=save().active;await import('../src/app.js?reload-test=1');await tick();assert.equal(save().active,id);assert.match($('.profile-button').textContent,/Hint Explorer/);assert.equal(save().profiles[1].inventions.length,1);});
