import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';import {missions} from '../src/content.js';import {adapters,simulate,insideBay} from '../src/models.js';
const win=new Window({url:'http://localhost:5187',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});win.document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
for(const [k,v]of Object.entries({window:win,document:win.document,localStorage:win.localStorage,navigator:win.navigator,location:win.location,matchMedia:()=>({matches:true}),requestAnimationFrame:()=>0,cancelAnimationFrame:()=>{}}))Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});
await import('../src/app.js');const tick=()=>new Promise(r=>setTimeout(r,5));await tick();await tick();
const $=s=>win.document.querySelector(s);const click=async(s)=>{const e=$(s);assert.ok(e,'Missing '+s);assert.equal(e.disabled,false,'Disabled '+s);e.click();await tick();};const set=async(s,v)=>{const e=$(s);e.value=String(v);e.dispatchEvent(new win.Event('input',{bubbles:true}));await tick();};const save=()=>{const value=JSON.parse(localStorage.getItem('science-quest.v1'));return value.snapshot||value;};const run=id=>save().profiles.find(p=>p.id===save().active).runs[id];
async function answer(value=0){if(document.querySelector('[data-action=run]')?.textContent==='Test transfer design'){const stage=document.querySelector('.task-panel .eyebrow').textContent;await set('#experiment-input',stage.includes('CONTEXT')?.4:.2);await click('[data-action=run]');}await click(`[data-action="choice"][data-value="${value}"]`);await click('[data-action="check"]');}
async function next(){await click('[data-action="next"]');}
async function open(id){if(!$(`[data-action="start"][data-id="${id}"]`)){await click('[data-action="region"][data-id="'+missions.find(m=>m.id===id).region+'"]');}await click(`[data-action="start"][data-id="${id}"]`);}

test('Learning pathways expose all grade routes and open the selected mission',async()=>{await click('[data-action="nav"][data-view="courses"]');assert.equal(document.querySelectorAll('.course-grid article').length,13);assert.match(document.querySelector('#main').textContent,/not a complete grade curriculum/);await click('[data-action="start"][data-id="light-window"]');assert.equal(run('light-window').stage,'notice');assert.match(document.querySelector('h1').textContent,/A Window for Light/);await click('[data-action="nav"][data-view="explore"]');});

test('Full guided flow across all 35 missions, including both transfer contexts',async()=>{for(const m of missions){await click('[data-action="nav"][data-view="explore"]');await open(m.id);assert.equal(run(m.id).stage,'notice');await next();for(const stage of ['predict','build']){assert.equal(run(m.id).stage,stage);await answer();assert.equal($('.feedback').classList.contains('good'),true,m.id+' '+stage);await next();}if(m.adapter==='energy'){for(const [id,val]of [['supply','*'],['demand','*'],['margin','-']]){const el=$('#energy-'+id);el.value=val;el.dispatchEvent(new win.Event('change',{bubbles:true}));await tick();}await click('[data-action=energy-check]');}for(const input of m.compare){await set('#experiment-input',input);await click('[data-action="run"]');}if(m.target&&!m.compare.some(x=>insideBay(simulate(m.adapter,x).value,...m.target))){const model=adapters[m.adapter];let solution;for(let x=model.min;x<=model.max+1e-7;x+=model.step){x=Number(x.toFixed(6));if(insideBay(simulate(m.adapter,x).value,...m.target)){solution=x;break;}}await set('#experiment-input',solution);await click('[data-action="run"]');}for(const el of [...win.document.querySelectorAll('[data-action="select-trial"]')].slice(0,2)){await click(`[data-action="select-trial"][data-id="${el.dataset.id}"]`);}await click('[data-action="compare"]');for(const stage of ['compare','explain','transfer1','transfer2']){assert.equal(run(m.id).stage,stage);await answer();await next();}assert.equal(run(m.id).completed,true);assert.equal(Object.values(run(m.id).evidence).filter(Boolean).length,6);assert.match($('#main').textContent,/Demonstrated/);}});

test('Hints do not confer mastery; an independent retry can complete missing evidence',async()=>{await click('[data-action="nav"][data-view="settings"]');$('#profile-name').value='Hint Explorer';$('#new-profile').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('[data-action="nav"][data-view="explore"]');await open('rover-rescue');await next();await click('[data-action="hint"]');await answer();await next();await answer();await next();for(const x of [.1,.3]){await set('#experiment-input',x);await click('[data-action="run"]');}for(const el of [...win.document.querySelectorAll('[data-action="select-trial"]')].slice(0,2)){await click(`[data-action="select-trial"][data-id="${el.dataset.id}"]`);}await click('[data-action="compare"]');for(let i=0;i<4;i++){await answer();await next();}assert.equal(run('rover-rescue').evidence.predict,undefined);assert.match($('#main').textContent,/Learning/);await click('[data-action="retry"]');assert.equal(run('rover-rescue').stage,'predict');await answer();assert.equal(run('rover-rescue').evidence.predict,true);assert.equal(run('rover-rescue').hintHistory.length,1);});

test('Profile separation, persistent checkpoint, journal and invention rebuild',async()=>{const before=save();assert.equal(before.profiles.length,2);assert.equal(Object.keys(before.profiles[1].runs).length,1);assert.equal(Object.keys(before.profiles[0].runs).length,35);await click('[data-action="nav"][data-view="explore"]');await click('[data-action="nav"][data-view="test"]');assert.equal(run('rover-rescue').stage,'predict');await click('[data-action="nav"][data-view="lab"]');await click('[data-action="run"]');$('#invention-name').value='Trolley experiment';await click('[data-action="save-invention"]');await click('[data-action="nav"][data-view="journal"]');assert.match($('#main').textContent,/Trolley experiment/);await click('[data-action="load-invention"]');assert.match($('#main').textContent,/Free Lab/);assert.equal($('#experiment-input').value,'0.2');});

test('All four arcade modes complete without awarding mission mastery',async()=>{for(const [id,inputs]of Object.entries({cargo:[.2,.4,.3],signal:[2,5,1],habitat:[20,40,30],buildoff:[.2,.4,.1]})){await click('[data-action="nav"][data-view="arcade"]');await click(`[data-action="arcade-start"][data-id="${id}"]`);for(const input of inputs){await set('#experiment-input',input);await click('[data-action="arcade-test"]');assert.match($('#main').textContent,/Design delivered/);await click('[data-action="arcade-next"]');}assert.match($('#main').textContent,/Challenge complete/);await click('[data-action="arcade-exit"]');}});

test('The actual mission UI restores selected answers and feedback after leaving a checkpoint',async()=>{await click('[data-action="nav"][data-view="test"]');await click('[data-action="choice"][data-value="1"]');await click('[data-action="check"]');assert.equal(run('rover-rescue').checkpoint.feedback.ok,false);await click('[data-action="nav"][data-view="journal"]');await click('[data-action="nav"][data-view="test"]');assert.equal(document.querySelector('[data-action="choice"][data-value="1"]').getAttribute('aria-pressed'),'true');assert.match(document.querySelector('.feedback').textContent,/Take another look/);});

test('Reduced-motion replay displays the selected saved trial, not the newest trial',async()=>{const original=save().active,first=save().profiles[0].id;await click('[data-action="nav"][data-view="settings"]');await click(`[data-action="profile"][data-id="${first}"]`);await click('[data-action="nav"][data-view="explore"]');await open('rover-rescue');await click('[data-action="replay"][data-index="0"]');assert.match(document.querySelector('#scene svg').getAttribute('aria-label'),/Ramp height: 0.1 m/);assert.match(document.querySelector('#scene svg').getAttribute('aria-label'),/Stopping distance: 0.5 m/);await click('[data-action="nav"][data-view="settings"]');await click(`[data-action="profile"][data-id="${original}"]`);});

test('Shared-device flow records separate answers, rotates jobs and persists workshop placement',async()=>{await click('[data-action="nav"][data-view="lab"]');await click('[data-action="coop"]');for(const el of document.querySelectorAll('[name=coop-player]'))el.checked=true;$('#coop-mission').value='rover-rescue';$('#coop-setup').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('[data-action="coop-hint"]');for(let i=0;i<2;i++){await click('[data-action="coop-choice"][data-value="0"]');await click('[data-action="coop-answer"]');}assert.equal(save().coopSessions[0].stage,'experiment');for(const x of [.1,.3]){await set('#coop-input',x);await click('[data-action="coop-run"]');}await click('[data-action="coop-explain"]');for(const i of [1,0]){await click(`[data-action="coop-choice"][data-value="${i}"]`);await click('[data-action="coop-answer"]');}assert.match($('#main').textContent,/Everyone contributed/);assert.equal(save().profiles[0].coopEvidence[0].assisted,true);assert.equal(save().profiles[1].coopEvidence[0].assisted,false);await click('[data-action="coop-next"]');assert.equal(save().coopSessions[0].round,1);const original=save().active;await click('[data-action="nav"][data-view="settings"]');await click(`[data-action="profile"][data-id="${save().profiles[0].id}"]`);await click('[data-action="nav"][data-view="explore"]');await click('[data-action="nav"][data-view="workshop"]');assert.equal(document.querySelectorAll('.upgrade-card.earned').length,18);const select=document.querySelector('[data-placement="Window shelf"]');select.value='compass';select.dispatchEvent(new win.Event('change',{bubbles:true}));await tick();assert.equal(save().profiles[0].world.placements['Window shelf'],'compass');await click('[data-action="nav"][data-view="settings"]');await click(`[data-action="profile"][data-id="${original}"]`);});

test('Reading controls remain separate when switching explorers',async()=>{await click('[data-action="nav"][data-view="settings"]');const active=save().active,other=save().profiles.find(p=>p.id!==active).id;const large=$('#large-text');large.checked=true;large.dispatchEvent(new win.Event('change',{bubbles:true}));await tick();assert.equal(save().profiles.find(p=>p.id===active).reading.large,true);await click(`[data-action="profile"][data-id="${other}"]`);assert.equal($('#large-text').checked,false);await click('[data-action="nav"][data-view="settings"]');await click(`[data-action="profile"][data-id="${active}"]`);assert.equal($('#large-text').checked,true);});

test('Journal adult feedback preserves mastery and captures the reviewed attempts',async()=>{await click('[data-action="nav"][data-view="journal"]');const form=document.querySelector('.adult-feedback');assert.ok(form);const mission=form.dataset.mission,before=JSON.stringify(run(mission).evidence);form.elements.reviewer.value='Adult test reviewer';form.elements.note.value='Talk through the trial comparison.';form.dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(run(mission).adultFeedback.at(-1).note,'Talk through the trial comparison.');assert.equal(JSON.stringify(run(mission).evidence),before);assert.ok(run(mission).adultFeedback.at(-1).attemptIds.length>0);});

test('Save snapshot survives app reinitialization',async()=>{const id=save().active;await import('../src/app.js?reload-test=1');await tick();assert.equal(save().active,id);assert.match($('.profile-button').textContent,/Hint Explorer/);assert.equal(save().profiles[1].inventions.length,1);});
