import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';import {climateQuestions,climateExpected} from '../src/climate-data.js';
const win=new Window({url:'http://localhost:5187/?activity=climate-data',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});win.document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
for(const [k,v]of Object.entries({window:win,document:win.document,localStorage:win.localStorage,navigator:win.navigator,location:win.location,matchMedia:()=>({matches:true}),requestAnimationFrame:()=>0,cancelAnimationFrame:()=>{}}))Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});
const tick=()=>new Promise(r=>setTimeout(r,10));await import('../src/app.js');await tick();await tick();const $=s=>document.querySelector(s),click=async s=>{assert.ok($(s),s);assert.equal($(s).disabled,false,s);$(s).click();await tick();},save=()=>JSON.parse(localStorage.getItem('science-quest.v1')).snapshot,active=()=>save().profiles.find(p=>p.id===save().active);
const fill=async step=>{const response={...Object.fromEntries(Object.entries(climateExpected(step)).map(([k,v])=>[k,String(v)])),...Object.fromEntries(Object.entries(climateQuestions[step]||{}).map(([k,q])=>[k,q.correct])),notes:'I used the stated years and kept the baseline fixed.'};for(const [key,value]of Object.entries(response)){const el=$(`[data-climate="${key}"]`);el.value=value;el.dispatchEvent(new win.Event('change',{bubbles:true}));await tick();}};
test('Observed climate activity opens by link, resumes responses and completes all four evidence checks',async()=>{
 assert.match($('h1').textContent,/Temperature Record/);assert.ok($('svg[aria-label^="NASA GISTEMP"]'));assert.equal(document.querySelectorAll('table tbody tr').length,146);assert.match($('#main').textContent,/not a confidence interval/);assert.ok($('a[download]').getAttribute('href').includes('2026-09-29.csv'));
 await fill(0);await click('[data-action=climate-exit]');await click('[data-action=climate-open]');assert.equal(active().climateData.drafts[0].meaning,'relative');
 for(let step=0;step<4;step++){await fill(step);await click('[data-action=climate-check]');assert.equal(active().climateData.attempts.at(-1).correct,true);await fill(step);await click('[data-action=climate-next]');}
 assert.equal(active().climateData.complete,true);assert.deepEqual(active().runs,{});await click('[data-action=nav][data-view=journal]');assert.match($('#main').textContent,/Observed climate records/);assert.match($('#main').textContent,/I used the stated years/);assert.match($('#main').textContent,/gistemp-v4-loti-2026-09-29/);
});
test('A second explorer gets a separate source-linked record with persistent worked-help status',async()=>{
 await click('[data-action=nav][data-view=settings]');$('#profile-name').value='Climate observer';$('#new-profile').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('[data-action=nav][data-view=explore]');await click('[data-action=nav][data-view=courses]');await click('[data-action=climate-open]');assert.equal(active().climateData.attempts.length,0);await click('[data-action=climate-help]');await click('[data-action=climate-exit]');await click('[data-action=climate-open]');assert.match($('#main').textContent,/Worked answers used/);assert.deepEqual(active().climateData.helped,[0]);assert.equal(save().profiles[0].climateData.complete,true);
});
