import test from 'node:test';import assert from 'node:assert/strict';import {applyPush} from '../cloud/protocol.js';import {createSyncKey,preparePush,syncRequest} from '../src/cloud-client.js';import {makeProfile} from '../src/learning.js';import worker,{ScienceSave} from '../cloud/worker.js';
const p=makeProfile('Cloud test'),snapshot={version:1,profiles:[p],active:p.id,settings:{}},event={id:'event-one',profile:p.id,type:'assessment'};
test('Sync is idempotent, rejects divergent events and preserves concurrent changes as conflicts',async()=>{const push=preparePush(snapshot,[event],0),one=await applyPush(null,push,1);assert.equal(one.body.revision,1);assert.equal((await applyPush(one.state,push)).body.replayed,true);const stale=preparePush(snapshot,[],0);assert.equal((await applyPush(one.state,stale)).body.conflict,true);const altered=preparePush(snapshot,[{...event,type:'different'}],1);assert.equal((await applyPush(one.state,altered)).status,409);const two=await applyPush(one.state,preparePush(snapshot,[event],1),2);assert.equal(two.state.events.length,1);assert.equal(two.state.history.length,1);assert.equal(two.state.history[0].revision,1);assert.equal(one.state.revision,1);});
test('Cloud request uses private authorization headers and reports conflicts for explicit reconciliation',async()=>{const key=createSyncKey();assert.equal(key.length,64);const result=await syncRequest({url:'https://example.org',key},async(url,options)=>{assert.equal(url,'https://example.org/v1/sync');assert.equal(options.headers.Authorization,'Bearer '+key);assert.ok(!url.includes(key));return Response.json({revision:2,snapshot},{status:409});});assert.equal(result.conflict,true);await assert.rejects(()=>syncRequest({url:'http://example.org',key}));});
test('Worker rejects unapproved origins, missing keys and accepts bodyless preflight',async()=>{assert.equal((await worker.fetch(new Request('https://service/v1/sync'),{})).status,401);assert.equal((await worker.fetch(new Request('https://service/v1/sync',{headers:{Origin:'https://unapproved.example'}}),{})).status,403);const r=await worker.fetch(new Request('https://service/v1/sync',{method:'OPTIONS',headers:{Origin:'https://chiokebuckley-art.github.io'}}),{});assert.equal(r.status,204);});
test('Durable service persists successful revisions, exposes recovery history and deletes explicitly',async()=>{const map=new Map(),storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),transaction:async fn=>fn(storage),deleteAll:async()=>map.clear()},service=new ScienceSave({storage});let r=await service.fetch(new Request('https://service/v1/sync',{method:'PUT',body:JSON.stringify(preparePush(snapshot,[event],0))}));assert.equal(r.status,200);r=await service.fetch(new Request('https://service/v1/sync'));assert.equal((await r.json()).events.length,1);await service.fetch(new Request('https://service/v1/sync',{method:'DELETE'}));assert.equal(map.size,0);});

test('Idempotence stores bounded digests while rejecting reuse of an ID for different data',async()=>{const large=structuredClone(snapshot);large.profiles[0].extra='x'.repeat(200000);const push=preparePush(large,[event],0),one=await applyPush(null,push);assert.equal(one.state.operations[0].digest.length,64);assert.equal(one.state.operations[0].payload,undefined);assert.ok(JSON.stringify(one.state.operations).length<200);assert.equal((await applyPush(one.state,push)).body.replayed,true);assert.equal((await applyPush(one.state,{...push,events:[]})).status,409);});
test('Legacy full-payload operation records replay and compact on the next accepted write',async()=>{const push=preparePush(snapshot,[event],0),one=await applyPush(null,push);const legacy=structuredClone(one.state);legacy.operations=[{id:push.operationId,revision:1,payload:JSON.stringify({snapshot:push.snapshot,events:push.events,baseRevision:0})}];assert.equal((await applyPush(legacy,push)).body.replayed,true);const next=await applyPush(legacy,preparePush(snapshot,[event],1));assert.ok(next.state.operations.every(o=>o.digest.length===64&&!('payload'in o)));assert.ok('payload'in legacy.operations[0]);});
