import test from 'node:test';import assert from 'node:assert/strict';
import{checkpoint,chooseAnswer,storeFeedback,advanceRun,beginReview,beginRetry,migrateRun,toggleTrialSelection,hasSelectedFairPair,selectedTrials}from'../src/controller.js';
import{createRun,CATEGORIES}from'../src/learning.js';import{missions}from'../src/content.js';import{simulate}from'../src/models.js';
const run=()=>createRun(missions.find(m=>m.id==='rover-rescue'));
test('Answers, hints and successful checks survive serialization at every scored checkpoint',()=>{for(const stage of ['predict','build','compare','explain','transfer1','transfer2']){const r=run();r.stage=stage;chooseAnswer(r,2);storeFeedback(r,{ok:false,text:'Supported attempt'});let resumed=JSON.parse(JSON.stringify(r));assert.deepEqual(checkpoint(resumed),{stage,choice:2,feedback:{ok:false,text:'Supported attempt'}});assert.throws(()=>advanceRun(resumed));chooseAnswer(resumed,0);storeFeedback(resumed,{ok:true,text:'Saved check'});resumed=JSON.parse(JSON.stringify(resumed));advanceRun(resumed);assert.notEqual(resumed.stage,stage);}});
test('A retry only repeats the missing check, without erasing earned evidence or world progress',()=>{const r=run();r.completed=true;r.evidence=Object.fromEntries(CATEGORIES.filter(c=>c!=='explain').map(c=>[c,true]));beginRetry(r);assert.equal(r.stage,'explain');chooseAnswer(r,0);r.evidence.explain=true;storeFeedback(r,{ok:true,text:'Independent evidence'});advanceRun(r);assert.equal(r.stage,'done');assert.equal(Object.keys(r.evidence).length,6);assert.equal(r.completed,true);});
test('A retention review checkpoints before user input and preserves earned creations',()=>{const r=run();r.completed=true;r.evidence=Object.fromEntries(CATEGORIES.map(c=>[c,true]));beginReview(r);const restored=JSON.parse(JSON.stringify(r));assert.equal(restored.reviewing,true);assert.equal(restored.stage,'transfer2');assert.equal(restored.assistance.transfer2,false);assert.throws(()=>advanceRun(restored));});
test('Learners select the evidence pair; repeated settings cannot satisfy a fair comparison',()=>{const r=run();r.trials=[.1,.1,.3].map((h,i)=>({...simulate('ramp',h),id:String(i)}));toggleTrialSelection(r,'0');toggleTrialSelection(r,'1');assert.equal(hasSelectedFairPair(r),false);assert.throws(()=>toggleTrialSelection(r,'2'));toggleTrialSelection(r,'1');toggleTrialSelection(r,'2');assert.equal(hasSelectedFairPair(r),true);assert.deepEqual(selectedTrials(r).map(t=>t.input),[.1,.3]);assert.deepEqual(selectedTrials(JSON.parse(JSON.stringify(r))).map(t=>t.id),['0','2']);});
test('Version 1.0 mission records migrate additively',()=>{const r=run();r.stage='compare';r.evidence.predict=true;r.trials=[simulate('ramp',.1),simulate('ramp',.3)];delete r.attempts;delete r.answers;const migrated=migrateRun(r);assert.equal(migrated.evidence.predict,true);assert.equal(migrated.trials.length,2);assert.equal(hasSelectedFairPair(migrated),true);assert.equal(checkpoint(migrated).stage,'compare');});
