import test from 'node:test';import assert from 'node:assert/strict';
import {createCoopSession,recordCoopAnswer,markCoopHelp,runCoopTrial,explainTogether,nextCoopRound,rolesFor} from '../src/coop.js';
import {reconcileWorld,placeDecoration} from '../src/world.js';import {validateSharedSave,mergeSharedSave,removeSharedProfile} from '../src/shared-save.js';import {makeProfile} from '../src/learning.js';import {byId} from '../src/content.js';
const mission=byId['rover-rescue'];
function setup(){const profiles=[makeProfile('One'),makeProfile('Two')],s=createCoopSession(profiles.map(p=>p.id),mission,profiles);return{profiles,s};}
function predictions(s,profiles){for(const p of profiles)recordCoopAnswer(s,mission,p.id,0,profiles);}
function experiment(s){const tester=rolesFor(s).find(x=>x.role==='Tester').profile;s.input=.1;runCoopTrial(s,tester);s.input=.3;runCoopTrial(s,tester);explainTogether(s);}
test('Co-op enforces roster, turns, experiment gates and individual assisted evidence',()=>{const {profiles,s}=setup();assert.throws(()=>createCoopSession([profiles[0].id],mission,profiles));assert.throws(()=>createCoopSession([profiles[0].id,profiles[0].id],mission,profiles));assert.throws(()=>runCoopTrial(s,profiles[0].id));assert.throws(()=>recordCoopAnswer(s,mission,profiles[1].id,0,profiles));markCoopHelp(s,profiles[0].id);predictions(s,profiles);assert.equal(s.stage,'experiment');assert.equal(profiles[0].coopEvidence[0].assisted,true);assert.equal(profiles[1].coopEvidence[0].assisted,false);assert.throws(()=>runCoopTrial(s,profiles[1].id));assert.throws(()=>explainTogether(s));experiment(s);recordCoopAnswer(s,mission,profiles[0].id,1,profiles);recordCoopAnswer(s,mission,profiles[1].id,0,profiles);assert.equal(s.stage,'complete');assert.equal(profiles[0].coopEvidence[1].correct,false);assert.equal(profiles[1].coopEvidence[1].correct,true);for(const p of profiles)assert.deepEqual(p.runs,{});const first=rolesFor(s);nextCoopRound(s,mission);assert.notEqual(rolesFor(s)[0].profile,first[0].profile);assert.equal(s.history.length,1);assert.equal(s.trials.length,0);assert.deepEqual(s.help,{predict:{},explain:{}});});
test('Shared backup conflict remaps roster, contribution owners, history and evidence without replacing local progress',()=>{const {profiles,s}=setup();predictions(s,profiles);experiment(s);for(const p of profiles)recordCoopAnswer(s,mission,p.id,0,profiles);nextCoopRound(s,mission);const data={version:1,profiles,active:profiles[0].id,coopSessions:[s],coopActive:s.id};validateSharedSave(data);const imported=structuredClone(data);imported.profiles[0].name='Changed';const clone=structuredClone(imported.profiles[0]);clone.id='imported-one';const {merged}=mergeSharedSave(data,imported,new Map([[profiles[0].id,clone.id]]),[clone]);assert.equal(merged.coopSessions.length,2);const added=merged.coopSessions[1];assert.deepEqual(added.roster,[clone.id,profiles[1].id]);assert.equal(added.history[0].answers.predict[clone.id].profile,clone.id);assert.equal(merged.profiles[2].coopEvidence[0].session,added.id);assert.equal(data.profiles.length,2);assert.equal(mergeSharedSave(data,data,new Map(),[]).merged.coopSessions.length,1);removeSharedProfile(merged,clone.id);assert.equal(merged.coopSessions.length,1);const bad=structuredClone(data);bad.coopSessions[0].roster[0]='missing';assert.throws(()=>validateSharedSave(bad));});
test('World rewards are permanent, isolated, idempotent and placeable only after earning',()=>{const a=makeProfile(),b=makeProfile();assert.deepEqual(reconcileWorld(a),[]);assert.throws(()=>placeDecoration(a,'compass','Work bench'));a.runs['first-move']={completed:true};assert.equal(reconcileWorld(a,100).length,1);assert.deepEqual(reconcileWorld(a,200),[]);a.runs['first-move'].completed=false;a.runs['first-move'].reviewFailed=true;reconcileWorld(a);assert.equal(a.world.upgrades[0].earnedAt,100);placeDecoration(a,'compass','Work bench');placeDecoration(a,'compass','Window shelf');assert.deepEqual(a.world.placements,{'Window shelf':'compass'});assert.throws(()=>placeDecoration(a,'compass','Unknown'));reconcileWorld(b);assert.equal(b.world.decorations.length,0);});
