import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';
const win=new Window({url:'http://localhost:5187/',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});win.document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
for(const [k,v]of Object.entries({window:win,document:win.document,localStorage:win.localStorage,navigator:win.navigator,location:win.location,matchMedia:()=>({matches:true}),requestAnimationFrame:()=>0,cancelAnimationFrame:()=>{}}))Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});
const tick=()=>new Promise(r=>setTimeout(r,10));await import('../src/app.js');await tick();await tick();const $=s=>document.querySelector(s),click=async s=>{assert.ok($(s),s);assert.equal($(s).disabled,false,s);$(s).click();await tick();},save=()=>JSON.parse(localStorage.getItem('science-quest.v1')).snapshot,active=()=>save().profiles.find(p=>p.id===save().active);
test('Harbor opens all facilities, resumes discoveries and returns from the real Free Lab',async()=>{
 await click('[data-action=region][data-id=motion]');assert.equal(document.querySelectorAll('.harbor-hotspots button').length,3);
 await click('[data-action=harbor-site][data-id=crane]');await click('#harbor-detail [data-action=start]');assert.match($('h1').textContent,/First Move/);await click('[data-action=region][data-id=motion]');assert.match($('.site-crane').textContent,/In progress/);
 await click('[data-action=harbor-site][data-id=route]');assert.equal($('#harbor-detail [data-action=start]').dataset.id,'restore-route');await click('#harbor-detail [data-action=start]');assert.match($('h1').textContent,/Restore the Route/);await click('[data-action=region][data-id=motion]');
 await click('[data-action=harbor-site][data-id=lab]');await click('[data-action=harbor-lab]');assert.ok($('[data-action=region][data-id=motion]'));await click('[data-action=run]');const before=active();assert.equal(before.inventions.length,0);assert.equal(Object.values(before.runs).some(r=>r.completed),false);await click('[data-action=region][data-id=motion]');assert.ok($('.harbor-board'));assert.match($('.site-lab').textContent,/Needs discovery/);
 await click('#harbor-detail [data-action=start]');assert.match($('h1').textContent,/Rover Rescue/);await click('[data-action=region][data-id=motion]');assert.match($('.site-lab').textContent,/In progress/);assert.match($('#harbor-detail').textContent,/Resume discovery/);
});
