import {testLocks} from './sync-lock-helper.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';import {makeProfile} from '../src/learning.js';import {applyPush} from '../cloud/protocol.js';
const win=new Window({url:'http://localhost:5187/sync/'});win.document.write(await fs.readFile(new URL('../sync/index.html',import.meta.url),'utf8'));Object.defineProperty(win.navigator,'locks',{value:testLocks()});let cloud=null;for(const [k,v]of Object.entries({window:win,document:win.document,localStorage:win.localStorage,navigator:win.navigator,fetch:async(url,options)=>{if(options.method==='GET')return Response.json(cloud);const result=await applyPush(cloud,JSON.parse(options.body));cloud=result.state;return Response.json(result.body,{status:result.status});}}))Object.defineProperty(globalThis,k,{value:v,configurable:true});const {openStore,persist}=await import('../src/storage.js');await openStore();const p=makeProfile('Device test');await persist({version:1,active:p.id,profiles:[p],settings:{}},{profile:p.id,type:'test'});await import('../sync/sync.js');const $=s=>document.querySelector(s),tick=()=>new Promise(r=>setTimeout(r,10));
test('Sync page connects without leaking key, uploads and imports through storage',async()=>{$('#url').value='https://example.org';$('#connect').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match($('#status').textContent,/Connected locally/);assert.equal($('#private-key').textContent,'');$('#upload').click();await tick();assert.equal(cloud.revision,1);assert.match($('#status').textContent,/Upload saved/);$('#download').click();await tick();assert.match($('#status').textContent,/Cloud discoveries imported/);$('#disconnect').click();await tick();assert.match($('#status').textContent,/Disconnected/);});
test('A competing sync tab gets an actionable message and leaves connection inputs untouched',async()=>{
 let release;const held=navigator.locks.request('science-quest.cloud-session.v1',{ifAvailable:true},()=>new Promise(resolve=>release=resolve));
 $('#url').value='https://example.org';$('#key').value='a'.repeat(64);$('#connect').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();
 assert.match($('#status').textContent,/another.*tab is busy/i);assert.equal($('#key').value,'a'.repeat(64));assert.ok([...document.querySelectorAll('button')].every(b=>!b.disabled));
 release();await held;$('#connect').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match($('#status').textContent,/Connected locally/);$('#show-key').click();await tick();assert.equal($('#private-key').textContent,'a'.repeat(64));$('#disconnect').click();await tick();assert.equal($('#private-key').textContent,'');
});
