import type { AchievementDef } from '../types';
import { asset } from '../../assets';

const icon = (f: string) => asset(`/assets/icons/${f}.svg`);

export const ACHIEVEMENTS: AchievementDef[] = [
  { id: 'first-answer', name: 'First Spark', description: 'Answer your first problem correctly.', icon: icon('star'), xp: 10 },
  { id: 'first-battle', name: 'Into the Dark', description: 'Win your first battle in the Multiplication Mines.', icon: icon('sword'), xp: 25 },
  { id: 'streak-10', name: 'Steady Hands', description: 'Answer 10 problems in a row correctly.', icon: icon('target'), xp: 40 },
  { id: 'streak-25', name: 'Machine Precision', description: 'Answer 25 problems in a row correctly.', icon: icon('gauge'), xp: 100 },
  { id: 'answers-100', name: 'Centurion', description: 'Answer 100 problems.', icon: icon('abacus'), xp: 50 },
  { id: 'answers-500', name: 'Ledger Keeper', description: 'Answer 500 problems.', icon: icon('book'), xp: 150 },
  { id: 'answers-1000', name: 'Thousand Gears', description: 'Answer 1,000 problems.', icon: icon('gear'), xp: 300 },
  { id: 'table-mastered', name: 'Table Mastered', description: 'Bring one multiplication table to Mastered (90%+).', icon: icon('medal'), xp: 75 },
  { id: 'hard-facts', name: 'The Hard Facts', description: 'Master 6×7, 7×8, 6×8, 7×9 and 8×9.', icon: icon('crystal'), xp: 120 },
  { id: 'mult-mastered', name: 'Power Core Ready', description: 'Bring overall multiplication mastery to 90%.', icon: icon('energy'), xp: 250 },
  { id: 'dragon', name: 'Dragonslayer', description: 'Defeat the Multiplication Dragon.', icon: icon('dragon'), xp: 300 },
  { id: 'level-5', name: 'Technician', description: 'Reach level 5.', icon: icon('level-up'), xp: 50 },
  { id: 'level-10', name: 'Surveyor', description: 'Reach level 10.', icon: icon('level-up'), xp: 100 },
  { id: 'lessons-3', name: 'Student of Vector', description: 'Complete three lessons.', icon: icon('scroll'), xp: 40 },
  { id: 'review-dungeon', name: 'Nothing Forgotten', description: 'Clear the Dungeon of Forgotten Knowledge.', icon: icon('skull'), xp: 80 },
  { id: 'bridge', name: 'Bridge Builder', description: 'Rebuild the bridge to the mines.', icon: icon('bridge'), xp: 60 },
  { id: 'streak-days-3', name: 'Three Days Running', description: 'Train on three consecutive days.', icon: icon('calendar'), xp: 60 },
  { id: 'streak-days-7', name: 'Weekly Rhythm', description: 'Train on seven consecutive days.', icon: icon('calendar'), xp: 150 },
  { id: 'depth-8', name: 'Bottom of the Mines', description: 'Clear the eighth gallery of the Multiplication Mines.', icon: icon('pickaxe'), xp: 100 },
  { id: 'project-workshop', name: 'Workshop Founder', description: 'Complete the Workshop project.', icon: icon('anvil'), xp: 120 },
  { id: 'blitz-20', name: 'Quick Draw', description: 'Score 20 correct in one 60-second Blitz.', icon: icon('hourglass'), xp: 60 },
  { id: 'blitz-35', name: 'Lightning Hands', description: 'Score 35 correct in one 60-second Blitz.', icon: icon('energy'), xp: 150 },
  { id: 'conquer-1', name: 'Table Conqueror', description: 'Conquer a full times table against the clock.', icon: icon('medal'), xp: 80 },
  { id: 'conquer-all', name: 'Chart Master', description: 'Conquer all twelve times tables.', icon: icon('trophy'), xp: 400 },
  { id: 'bonds-10', name: 'Perfect Ten', description: 'Conquer the bonds to 10.', icon: icon('star'), xp: 50 },
  { id: 'bonds-100', name: 'Century Maker', description: 'Conquer the bonds to 100.', icon: icon('coins'), xp: 120 },
  { id: 'rocket-liftoff', name: 'Liftoff', description: 'Complete the Launch Pad rocket mission.', icon: icon('energy'), xp: 50 },
  { id: 'rocket-orbit', name: 'In Orbit', description: 'Reach Low Orbit in the Rocket Game.', icon: icon('telescope'), xp: 120 },
  { id: 'rocket-moon', name: 'One Small Step', description: 'Land on the Moon.', icon: icon('trophy'), xp: 400 },
  { id: 'notebook-1', name: 'Case Closed', description: 'Clear your first wrong-answer card with three clean fixes.', icon: icon('book'), xp: 40 },
  { id: 'notebook-10', name: 'Error Hunter', description: 'Clear ten wrong-answer cards.', icon: icon('scroll'), xp: 150 },
  { id: 'notebook-empty', name: 'Clean Slate', description: 'Clear every card in the notebook.', icon: icon('star'), xp: 100 },
  { id: 'gear-win', name: 'Strongest Gear', description: 'Win a game of Weakest Gear.', icon: icon('trophy'), xp: 120 },
  { id: 'gear-chain', name: 'Full Chain', description: 'Climb the whole chain to 1,000 gears.', icon: icon('cog'), xp: 100 },
  { id: 'gear-final', name: 'Last Two Standing', description: 'Reach the Weakest Gear final.', icon: icon('medal'), xp: 50 },
  { id: 'gear-pot', name: 'Arena Champion', description: 'Win a Weakest Gear pot of 2,000 gears or more.', icon: icon('chest'), xp: 200 },
  { id: 'stud-win', name: 'First Pot', description: 'Win a hand of Stud Math.', icon: icon('coins'), xp: 40 },
  { id: 'stud-flush', name: 'Flush Fitter', description: 'Win with a flush or better.', icon: icon('crystal'), xp: 100 },
  { id: 'stud-fullhouse', name: 'Full House Foreman', description: 'Win with a full house or better.', icon: icon('anvil'), xp: 150 },
  { id: 'stud-royal', name: 'Royal Engineer', description: 'Make a straight flush or a royal flush.', icon: icon('trophy'), xp: 500 },
  { id: 'stud-500', name: 'Gear Baron', description: 'Build a bankroll of 500 gears.', icon: icon('chest'), xp: 120 },
  { id: 'stud-cashier', name: 'Cashier', description: 'Compute a 2-to-1 or better payout correctly.', icon: icon('abacus'), xp: 60 },
  { id: 'mental-blitz', name: 'Head Math', description: 'Get 20 two-digit sums right in one mental-math Blitz.', icon: icon('brain'), xp: 90 },
  { id: 'mental-conquer', name: 'Number Structure', description: 'Conquer a mental addition & subtraction set.', icon: icon('abacus'), xp: 100 },
  { id: 'volume-blitz', name: 'Tank Gauger', description: 'Measure 7 volumes right in one Blitz.', icon: icon('flask'), xp: 90 },
  { id: 'volume-conquer', name: 'Master of Measure', description: 'Conquer a volume set.', icon: icon('crystal'), xp: 100 },
  { id: 'measure-blitz', name: 'Steady Hand', description: 'Read 7 measurements right in one Blitz.', icon: icon('ruler'), xp: 90 },
  { id: 'measure-conquer', name: 'Inspector', description: 'Conquer a measurement set.', icon: icon('calipers'), xp: 100 },
  { id: 'pattern-blitz', name: 'Pattern Spotter', description: 'Solve 7 Pattern Lab puzzles in one Blitz.', icon: icon('target'), xp: 90 },
  { id: 'pattern-conquer', name: 'Rule Finder', description: 'Conquer a Pattern Lab set.', icon: icon('target'), xp: 100 },
  { id: 'blocks-blitz', name: 'Cube Counter', description: 'Count 7 block stacks right in one Blitz.', icon: icon('crystal'), xp: 90 },
  { id: 'blocks-conquer', name: 'Master Builder', description: 'Conquer a Spatial Blocks set.', icon: icon('crystal'), xp: 100 },
  { id: 'paths-blitz', name: 'Every Way', description: 'Count 7 ways right in one Blitz.', icon: icon('map'), xp: 90 },
  { id: 'paths-conquer', name: 'Pathfinder', description: 'Conquer a Counting Paths set.', icon: icon('map'), xp: 100 },
  { id: 'data-blitz', name: 'Chart Reader', description: 'Read 7 charts right in one Blitz.', icon: icon('dashboard'), xp: 90 },
  { id: 'data-conquer', name: 'Data Detective', description: 'Conquer a Charts & Venn set.', icon: icon('dashboard'), xp: 100 },
  { id: 'logic-blitz', name: 'Clear Thinker', description: 'Solve 7 logic puzzles in one Blitz.', icon: icon('brain'), xp: 90 },
  { id: 'logic-conquer', name: 'Logician', description: 'Conquer a Logic Lite set.', icon: icon('brain'), xp: 100 },
  { id: 'pctmulti-blitz', name: 'Step by Step', description: 'Solve 7 multi-step percent stories in one Blitz.', icon: icon('coins'), xp: 90 },
  { id: 'pctmulti-conquer', name: 'Tariff Master', description: 'Conquer a multi-step percent set.', icon: icon('coins'), xp: 100 },
  { id: 'grid-blitz', name: 'Mirror Maker', description: 'Solve 7 grid puzzles in one Blitz.', icon: icon('compass'), xp: 90 },
  { id: 'grid-conquer', name: 'Shape Shifter', description: 'Conquer a Mirror & Grid set.', icon: icon('compass'), xp: 100 },
  { id: 'geo-blitz', name: 'Set Square', description: 'Solve 7 shape and angle problems in one Blitz.', icon: icon('compass'), xp: 90 },
  { id: 'geo-conquer', name: 'Geometer', description: 'Conquer a shapes & angles set.', icon: icon('compass'), xp: 100 },
  { id: 'rates-blitz', name: 'Rate Setter', description: 'Solve 7 rate problems in one Blitz.', icon: icon('dashboard'), xp: 90 },
  { id: 'rates-conquer', name: 'Unit Wrangler', description: 'Conquer a rates & conversions set.', icon: icon('dashboard'), xp: 100 },
  { id: 'fit-blitz', name: 'Tenth of a Millimetre', description: 'Read 7 precision measurements in one Blitz.', icon: icon('calipers'), xp: 90 },
  { id: 'fit-conquer', name: 'Toolmaker', description: 'Conquer a precision & fit set.', icon: icon('calipers'), xp: 100 },
  { id: 'phys-blitz', name: 'Torque Talker', description: 'Solve 7 force and power problems in one Blitz.', icon: icon('gauge'), xp: 90 },
  { id: 'phys-conquer', name: 'Load Master', description: 'Conquer a forces & power set.', icon: icon('gauge'), xp: 100 },
  { id: 'pipe-blitz', name: 'Pipe Fitter', description: 'Solve 7 plumbing problems in one Blitz.', icon: icon('pump'), xp: 90 },
  { id: 'pipe-conquer', name: 'Master Plumber', description: 'Conquer a plumbing set.', icon: icon('pump'), xp: 100 },
  { id: 'speed-pass', name: 'On the Clock', description: 'Pass a speed set: 90 % right, 90 % on time.', icon: icon('hourglass'), xp: 60 },
  { id: 'speed-3', name: 'Three Seconds', description: 'Pass a speed set on the 3-second clock.', icon: icon('energy'), xp: 200 },
  { id: 'prob-blitz', name: 'Odds Maker', description: 'Solve 7 probability problems in one Blitz.', icon: icon('telescope'), xp: 90 },
  { id: 'prob-conquer', name: 'Modeller', description: 'Conquer a probability-lab set.', icon: icon('telescope'), xp: 100 },
  { id: 'spiral-blitz', name: 'Review Runner', description: 'Solve 7 spiral-review problems in one Blitz.', icon: icon('scroll'), xp: 90 },
  { id: 'spiral-conquer', name: 'Sheet Slayer', description: 'Conquer a spiral-review set.', icon: icon('scroll'), xp: 100 },
  { id: 'precalc-blitz', name: 'Prep School', description: 'Solve 7 calculus-prep problems in one Blitz.', icon: icon('lab'), xp: 90 },
  { id: 'precalc-conquer', name: 'Ready for Calculus', description: 'Conquer a calculus-prep set.', icon: icon('lab'), xp: 100 },
  { id: 'mm-make10', name: 'Make 10 Master', description: 'Master the complements to ten.', icon: icon('star'), xp: 40 },
  { id: 'mm-make100', name: 'Make 100 Master', description: 'Master the complements to a hundred.', icon: icon('star'), xp: 60 },
  { id: 'mm-add2', name: 'Addition Apprentice', description: 'Pass a two-digit mental addition mastery round.', icon: icon('abacus'), xp: 80 },
  { id: 'mm-add3', name: 'Addition Master', description: 'Pass a three-digit mental addition mastery round.', icon: icon('abacus'), xp: 140 },
  { id: 'mm-sub', name: 'Subtraction Master', description: 'Pass a three-digit mental subtraction mastery round.', icon: icon('rock'), xp: 140 },
  { id: 'mm-mul', name: 'Multiplication Master', description: 'Pass a two-digit mental multiplication mastery round.', icon: icon('multiply'), xp: 160 },
  { id: 'mm-compensate', name: 'Compensation Expert', description: 'Master rounding and compensating in both addition and subtraction.', icon: icon('brain'), xp: 120 },
  { id: 'mm-100', name: '100 Mental Problems', description: 'Solve 100 problems in the Mental Math Academy.', icon: icon('abacus'), xp: 60 },
  { id: 'mm-500', name: '500 Mental Problems', description: 'Solve 500 problems in the Mental Math Academy.', icon: icon('abacus'), xp: 150 },
  { id: 'mm-1000', name: '1,000 Mental Problems', description: 'Solve 1,000 problems in the Mental Math Academy.', icon: icon('trophy'), xp: 300 },
  { id: 'mm-streak25', name: '25-Answer Streak', description: 'Twenty-five correct mental answers in a row.', icon: icon('fire'), xp: 100 },
  { id: 'mm-streak50', name: '50-Answer Streak', description: 'Fifty correct mental answers in a row.', icon: icon('fire'), xp: 200 },
  { id: 'mm-speed', name: 'Speed Demon', description: 'Clear the fastest clock on any mental skill.', icon: icon('energy'), xp: 180 },
  { id: 'mm-perfect', name: 'Perfect Round', description: 'A flawless ten-question mental round.', icon: icon('medal'), xp: 90 },
  { id: 'mm-boss', name: 'Titan Slayer', description: 'Defeat a Mental Math world boss.', icon: icon('sword'), xp: 150 },
  { id: 'mm-master', name: 'Mental Math Master', description: 'Master every world of the Academy.', icon: icon('trophy'), xp: 500 },
  { id: 'mm-workout', name: 'Daily Discipline', description: 'Complete seven daily mental workouts.', icon: icon('calendar'), xp: 200 },
  { id: 'trick-blitz', name: 'Human Calculator', description: 'Get 12 trick problems right in one Blitz.', icon: icon('brain'), xp: 90 },
  { id: 'trick-conquer', name: 'Trickster', description: 'Conquer a math-tricks set.', icon: icon('crystal'), xp: 100 },
  { id: 'word-blitz', name: 'Story Solver', description: 'Get 8 word problems right in one Blitz.', icon: icon('book'), xp: 80 },
  { id: 'word-conquer', name: 'Case Closed', description: 'Conquer a word-problem set.', icon: icon('scroll'), xp: 100 },
  { id: 'mill-1000', name: 'Safe at $1,000', description: 'Reach the first safe haven in Math Millionaire.', icon: icon('coins'), xp: 50 },
  { id: 'mill-32000', name: 'Safe at $32,000', description: 'Reach the second safe haven in Math Millionaire.', icon: icon('chest'), xp: 120 },
  { id: 'mill-million', name: 'Math Millionaire', description: 'Win the million.', icon: icon('trophy'), xp: 500 },
  { id: 'mill-solo', name: 'No Help Needed', description: 'Clear five rungs without using a lifeline.', icon: icon('brain'), xp: 60 },
  { id: 'rocket-perfect', name: 'Flawless Flight', description: 'Finish a rocket mission with no bombs and every answer right.', icon: icon('star'), xp: 100 },
];

export const achievementById = (id: string) => ACHIEVEMENTS.find((a) => a.id === id);
