import {BY_ID,ENTRIES} from './content.js';
import {LESSONS,GRADE_TITLES,gradeName,getCourse,coursePlan,unlocked,workFor,completeLesson,teachingFor,courseQuestion} from './course.js';
import {recordAnswer} from './engine.js';
export function createCourseUI(api){
 const {p,persist,shell,esc,button,heading,speak,toast}=api;let active=null;
 const academyLink='<a class="academy-banner" href="#visual-library" data-action="nav" data-route="visual-library"><span>▤</span><div><b>My Visual Library</b><p>Your scanned books, picture pages, and meaning cards.</p></div><strong>Open my library →</strong></a><a class="academy-banner" href="./academy/"><span>▧</span><div><b>Small Common Word Academy</b><p>See the meaning. Explore 3,000 original illustrated scenes.</p></div><strong>Start the journey →</strong></a>';
 const gradeOptions=selected=>Array.from({length:13},(_,g)=>`<option value="${g}" ${String(selected)===String(g)?'selected':''}>${gradeName(g)}</option>`).join('')+`<option value="adult" ${selected==='adult'?'selected':''}>Adult · rebuild all foundations</option>`;
 function fields(profile){let c=getCourse(profile);return `<label>School grade / course goal<select name="targetGrade">${gradeOptions(profile.level===5?'adult':c.target)}</select></label><p class="small">Everyone starts at kindergarten. This sets the finish line, not a shortcut past earlier lessons.</p>`;}
 function configure(profile,value){let c=getCourse(profile);if(value==='adult'){profile.level=5;c.target=12;}else{let g=Number(value);if(!Number.isInteger(g)||g<0||g>12)return false;c.target=g;profile.level=g<=1?1:g<=5?2:g<=8?3:4;}c.configured=true;return true;}
 function renderHome(){let c=getCourse(p()),plan=coursePlan(p());
 if(!c.configured){shell(`${academyLink}${heading('LET’S BUILD YOUR FOUNDATION','Your own path, from the beginning.','Learn the meaning first. Practice with help. Then show what you understand.')}<section class="lesson-panel enrollment"><div class="course-mascot">🐾</div><h2>Where are we headed?</h2><p>Choose your school grade. We will start at kindergarten and work forward, one small lesson at a time.</p><form id="course-enroll"><label>Explorer’s name<input name="name" value="${esc(p().name)}" required maxlength="30"></label>${fields(p())}<button class="btn primary" type="submit">Start with kindergarten →</button></form><p class="small">Your existing quiz progress is kept. Lesson completion starts fresh because the earlier game did not check these teaching steps.</p></section>`);return;}
 const next=plan.next,completedGrades=Array.from({length:c.target+1},(_,g)=>g).filter(g=>plan.lessons.filter(l=>l.grade===g).every(l=>c.passed[l.id]));
 shell(`${academyLink}${heading(`${esc(p().name.toUpperCase())}’S FOUNDATION PATH`,plan.complete?'You reached your finish line!':`Kindergarten → ${gradeName(c.target)}`,plan.complete?'Your selected foundation course is complete. Keep reviewing meanings so they stay with you.':'We teach one meaning at a time. Every completed lesson opens the next step.')}<section class="course-hero"><div><p class="eyebrow">${plan.complete?'COURSE COMPLETE':'YOUR NEXT SMALL STEP'}</p><h2>${next?esc(next.title):`${gradeName(c.target)} foundation badge earned`}</h2><p>${next?`${gradeName(next.grade)} · ${next.entries.length} meanings · learn, practice, and check`:'You completed every lesson from kindergarten through your selected grade.'}</p>${next?button(c.resume===next.id?'Resume my lesson →':'Teach me this lesson →','course-open','primary',`data-id="${next.id}"`):button('Review my meanings →','nav','primary','data-route="repair"')} ${button('Change course goal','profiles','text-btn')}</div><div class="course-achievement">${plan.complete?'🏆':'🌱'}<strong>${plan.done} / ${plan.total}</strong><span>lessons completed</span></div></section><div class="session-track" aria-label="Course completion ${Math.round(plan.done/plan.total*100)} percent"><i style="width:${plan.done/plan.total*100}%"></i></div><p class="local-note">${completedGrades.length} of ${c.target+1} grade stages completed · ${plan.total-plan.done} lessons to your finish line. Each lesson requires teaching, guided practice, and two correct independent checks for every meaning.</p><div class="grade-path">${Array.from({length:c.target+1},(_,g)=>{let ls=plan.lessons.filter(l=>l.grade===g),done=ls.filter(l=>c.passed[l.id]).length,isNext=next?.grade===g;return `<details class="grade-stage" ${isNext||plan.complete&&g===c.target?'open':''}><summary><span class="grade-icon">${done===ls.length?'🏅':isNext?'🐾':'○'}</span><span><b>${gradeName(g)}</b><small>${GRADE_TITLES[g]}</small></span><strong>${done}/${ls.length}</strong></summary><div class="grade-lessons">${ls.map((l,i)=>`<button class="course-lesson ${c.passed[l.id]?'passed':''}" data-action="course-open" data-id="${l.id}" ${unlocked(p(),l.id)?'':'disabled'}><span>${c.passed[l.id]?'✓':i+1}</span><div><b>${esc(l.title)}</b><small>${c.passed[l.id]?'Completed · revisit any time':unlocked(p(),l.id)?'Ready to learn':'Finish the previous lesson to open'}</small></div><span>${unlocked(p(),l.id)?'→':'🔒'}</span></button>`).join('')}</div></details>`;}).join('')}</div><div class="bottom-note"><span>📚</span><div><b>A clear finish line for this course</b><p>These are the game’s vocabulary and symbol foundations, not every subject or word taught in a school grade. Course completion and long-term retention are tracked separately.</p></div></div>`);
 }
 function renderLesson(){const c=getCourse(p()),l=LESSONS.find(l=>l.id===active&&unlocked(p(),l.id));if(!l){api.setRoute('home');renderHome();return;}const w=workFor(p(),l.id);if(w.item>=l.entries.length){const before=Boolean(c.passed[l.id]);completeLesson(p(),l.id);c.resume=null;persist();const plan=coursePlan(p()),gradeDone=LESSONS.filter(x=>x.grade===l.grade).every(x=>c.passed[x.id]);shell(`${heading(gradeDone?`${gradeName(l.grade).toUpperCase()} COMPLETE`:'LESSON COMPLETE',gradeDone?'A foundation built.':'You learned these meanings.',l.title)}<section class="results"><div class="result-medal">${gradeDone?'🏅':'✦'}</div><h2>${gradeDone?`${gradeName(l.grade)} foundation badge`:'Explanation + guided practice + independent checks'}</h2><p>${before?'This was a review. Your completion is preserved.':'Every meaning in this lesson passed both independent checks.'}</p><p>${plan.done} of ${plan.total} lessons completed toward ${gradeName(c.target)}.</p><div class="actions">${plan.next?button('Teach me the next lesson →','course-open','primary',`data-id="${plan.next.id}"`):button('See my completed path →','nav','primary','data-route="home"')}${button('Back to my path','nav','secondary','data-route="home"')}</div></section>`);return;}
 const e=BY_ID[l.entries[w.item]],t=teachingFor(e),q=courseQuestion(e,w.phase,w.checks),feedback=w.feedback;
 const top=`<div class="session-top">${button('← Save & return to my path','nav','text-btn','data-route="home"')}<b>${gradeName(l.grade)} · Meaning ${w.item+1}/${l.entries.length}</b></div><ol class="learning-steps"><li class="${w.phase==='teach'?'current':''}">1. Learn</li><li class="${w.phase==='guided'?'current':''}">2. Together</li><li class="${w.phase==='check'?'current':''}">3. On my own</li></ol>`;
 let body='';if(w.phase==='teach'){
 const pages=[`<div class="teaching-picture" role="img" aria-label="Meaning illustration">${esc(t.picture)}</div><h1>Let’s learn “${esc(e.term)}”.</h1><p class="teaching-meaning">${esc(t.simple)}</p><div class="worked-example"><h3>What this means</h3><p>${esc(t.why)}</p></div>`,`<h1>See how it works.</h1><blockquote>${esc(t.example)}</blockquote><div class="worked-example"><h3>Think it through</h3><p>${esc(t.why)}</p></div><div class="trap"><b>Compare the meanings</b><p>${esc(t.contrast)}</p></div>`,`<h1>Make the meaning your own.</h1><div class="worked-example"><h3>Try this with your voice or hands</h3><p>${esc(t.activity)}</p></div><p>Say or show your idea. A grown-up can help. This activity is practice; the game checks understanding next.</p><blockquote>${esc(t.second)}</blockquote>`];
 body=`${w.reason?`<div class="notice"><b>Let’s learn that part again.</b><p>${esc(w.reason)}</p></div>`:''}${pages[w.step]}<div class="actions">${button('🔊 Read this to me','course-listen','secondary')}${w.step?button('← Back','course-back','secondary'):''}${button(w.step<2?'Show me more →':'Let’s try it together →','course-teach-next','primary')}</div><p class="small">Teaching page ${w.step+1} of 3. No guessing and no timer.</p>`;
 }else{
 body=`<p class="eyebrow">${w.phase==='guided'?'PRACTICE WITH HELP':'YOUR INDEPENDENT CHECK · '+(w.checks+1)+' OF 2'}</p><h1>${esc(q.prompt)}</h1><blockquote class="context-example">${esc(q.example)}</blockquote>${w.phase==='guided'?`<div class="worked-example"><b>Think with me</b><p>${esc(t.why)}</p><p>The idea we are looking for is: <strong>${esc(t.simple)}</strong></p></div>`:''}<div class="answers">${q.choices.map((v,i)=>`<button class="answer ${feedback&&v===q.answer?'correct':''}" data-action="course-answer" data-value="${esc(v)}" ${feedback?'disabled':''}><span>${String.fromCharCode(65+i)}</span><div>${esc(v)}</div></button>`).join('')}</div>${feedback?`<div class="feedback ${feedback.correct?'good':'needs-work'}" role="status"><b>${feedback.correct?(w.phase==='guided'?'We found the meaning together.':'You explained this meaning correctly.'):'Let’s work through the meaning again.'}</b><p>${esc(t.simple)}</p><p>${esc(feedback.correct?t.why:t.contrast)}</p></div>${button(feedback.correct?'Continue →':'Teach me again →','course-feedback-next','primary')}`:`<div class="actions">${button('🔊 Read this to me','course-listen','secondary')}${button('Teach me again','course-reteach','text-btn')}</div>`}`;
 }
 shell(`${top}<section class="teaching-card">${body}</section><p class="local-note">Your place is saved after each step. Independent checks feed your review record; reading a teaching page or guided answer does not count as mastery.</p>`);
 }
 function open(id){if(!unlocked(p(),id)){toast('Finish the earlier lessons first.');return;}active=id;getCourse(p()).resume=id;workFor(p(),id);persist();api.setRoute('course');renderLesson();window.scrollTo({top:0});}
 function action(a,b){if(!a.startsWith('course-'))return false;if(a==='course-open'){if(api.hasQuiz()){toast('Leave the current quiz before opening a lesson.');return true;}open(b.dataset.id);return true;}
 const l=LESSONS.find(l=>l.id===active);if(!l||!unlocked(p(),active))return true;const w=workFor(p(),active),e=BY_ID[l.entries[w.item]];if(!e)return true;const t=teachingFor(e);
 if(a==='course-listen'){const q=courseQuestion(e,w.phase,w.checks);speak(w.phase==='teach'?[t.simple+' '+t.why,t.example+' '+t.why+' Compare: '+t.contrast,t.activity+' '+t.second][w.step]:q.prompt+' '+q.example+'. '+(w.phase==='guided'?t.why+' '+t.simple+'. ':'')+q.choices.map((v,i)=>String.fromCharCode(65+i)+'. '+v).join('. '));return true;}
 if(a==='course-teach-next'&&w.phase==='teach'){if(w.step<2)w.step++;else{w.phase='guided';w.reason=null;}}
 else if(a==='course-back'&&w.phase==='teach')w.step=Math.max(0,w.step-1);
 else if(a==='course-reteach'&&!w.feedback){w.phase='teach';w.step=0;w.checks=0;w.reason='You asked for another explanation. Take your time.';}
 else if(a==='course-answer'&&['guided','check'].includes(w.phase)&&!w.feedback){const q=courseQuestion(e,w.phase,w.checks),correct=b.dataset.value===q.answer;w.feedback={correct};if(w.phase==='check'){p().records[e.id]=recordAnswer(p().records[e.id],{correct,form:w.checks?'context':'meaning'});if(correct)p().xp+=10;}}
 else if(a==='course-feedback-next'&&w.feedback){const correct=w.feedback.correct;w.feedback=null;if(!correct){w.phase='teach';w.step=0;w.checks=0;w.reason=t.contrast;}else if(w.phase==='guided'){w.phase='check';w.checks=0;}else if(w.checks===0){w.checks=1;}else{w.item++;w.phase='teach';w.step=0;w.checks=0;w.reason=null;}}
 persist();renderLesson();window.scrollTo({top:0});return true;
 }
 function submit(f,data){if(f.id!=='course-enroll')return false;const name=String(data.get('name')||'').trim();if(!name)return true;p().name=name.slice(0,30);configure(p(),String(data.get('targetGrade')));persist();renderHome();return true;}
 return {renderHome,renderLesson,action,fields,configure,submit,open};
}
