import test from 'node:test';
import assert from 'node:assert/strict';
import {CHAPTERS,STORIES} from '../trail-content.js';
import {wordCount,newTrail,unlocked,readingResult,saveReading,winner} from '../trail-engine.js';
import {newSave,validateSave} from '../engine.js';
test('Twelve chapters have two distinct, answerable rescues with supported evidence',()=>{assert.equal(CHAPTERS.length,12);assert.equal(STORIES.length,24);assert.equal(new Set(STORIES.map(s=>s.id)).size,24);for(const c of CHAPTERS){assert.equal(STORIES.filter(s=>s.grade===c.grade).length,2);}for(const s of STORIES){assert.ok(s.text.length>100);assert.equal(s.questions.length,5);for(const q of s.questions){assert.equal(new Set(q.options).size,3);assert.ok(q.options[q.answer]);assert.ok(q.why);assert.ok(s.text.toLowerCase().includes(q.evidence.toLowerCase()),s.id+': '+q.evidence);}}});
test('WPM counts passage words only, and comprehension qualifies the race',()=>{assert.equal(wordCount("The dog's red-blue bed. It's dry!"),6);const s=STORIES[0],a=s.questions.map(q=>q.answer);let r=readingResult(s,a,60000);assert.equal(r.wpm,wordCount(s.text));assert.ok(r.eligible);assert.equal(readingResult(s,a,0).eligible,false);assert.equal(readingResult(s,a,60000,true).eligible,false);assert.equal(readingResult(s,[1,1,0,0,0],1000).eligible,false);assert.equal(readingResult(s,[1,0,0,0,0],1000).eligible,true);});
test('Adventure unlocks by independent comprehension without a speed requirement, and progress survives import',()=>{let save=newSave(),p=save.profiles[0],t=p.trail=newTrail();assert.ok(unlocked(t,1));assert.equal(unlocked(t,2),false);for(const s of STORIES.slice(0,2)){const a=s.questions.map(q=>q.answer);saveReading(p,s,readingResult(s,a,600000,true),'adventure');}assert.equal(t.rescued.length,2);assert.equal(unlocked(t,2),false);for(const s of STORIES.slice(0,2))saveReading(p,s,readingResult(s,s.questions.map(q=>q.answer),6000000),'adventure');assert.ok(unlocked(t,2));assert.equal(unlocked(t,3),false);assert.equal(p.xp,60);assert.deepEqual(validateSave(save).profiles[0].trail,t);t.passed.push('fake');assert.throws(()=>validateSave(save));});
test('Duel awards accuracy eligibility before speed, supports ties and no winner',()=>{assert.match(winner([{eligible:false,wpm:400},{eligible:true,wpm:50}]),/Player 2/);assert.match(winner([{eligible:true,wpm:50},{eligible:true,wpm:50}]),/tie/);assert.match(winner([{eligible:false,wpm:400},{eligible:false,wpm:300}]),/No winner/);});
