import {createSyncSession} from '../src/sync-session.js';import {reconcileCloud} from '../src/sync-merge.js';import {openStore,loadSave,getEvents,replaceSaveWithEvents} from '../src/storage.js';
const $=s=>document.querySelector(s),session=createSyncSession(localStorage),status=s=>$('#status').textContent=s;let busy=false;
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await openStore();await fn();}catch(e){status(e.message);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function download(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#connect').onsubmit=e=>{e.preventDefault();action(()=>{session.connect($('#url').value,$('#key').value.trim()||undefined);$('#key').value='';status('Connected locally. Use Save or Bring cloud discoveries to transfer data.');});};
$('#show-key').onclick=()=>action(()=>{$('#private-key').textContent=session.privateKey();});
$('#upload').onclick=()=>action(async()=>{const snapshot=await loadSave();if(!snapshot)throw Error('Create an explorer in the game first.');if(!session.status()?.pending)session.queue(snapshot,await getEvents());const result=await session.upload();status(result.conflict?'The cloud contains another revision. Merge the conflicting save to preserve both.':'Upload saved. Cloud revision '+result.revision+'.');});
$('#download').onclick=()=>action(async()=>{if(session.status()?.pending||session.status()?.conflict)throw Error('Finish or merge the pending upload first.');const remote=await session.inspect();if(!remote.snapshot)throw Error('No cloud discoveries yet. Save from the first device.');const local=await loadSave();if(!local)throw Error('Open the game and create an explorer before importing.');const {merged,events}=reconcileCloud(local,remote);await replaceSaveWithEvents(merged,events);status('Cloud discoveries imported. Return to the game to see the preserved explorers.');});
$('#resolve').onclick=()=>action(async()=>{const remote=session.conflict();if(!remote?.snapshot)throw Error('No saved snapshot conflict to merge.');const local=await loadSave(),{merged,events}=reconcileCloud(local,remote);await replaceSaveWithEvents(merged,events);session.resolveWithMerged(merged,await getEvents());const result=await session.upload();status(result.conflict?'Another device changed the cloud again. Both versions remain available; merge again.':'Merged copies saved locally and in the cloud.');});
$('#recovery').onclick=()=>action(()=>{download({conflict:session.conflict(),recovery:session.recovery()},'science-quest-sync-recovery.json');status('Recovery exported without the private key.');});
$('#disconnect').onclick=()=>action(()=>{session.disconnect();$('#private-key').textContent='';status('Disconnected. Game progress and the cloud copy remain.');});
$('#delete').onclick=()=>action(async()=>{if(!confirm('Delete the cloud copy for this private key? Local game progress stays on this device.'))return;await session.deleteCloud();$('#private-key').textContent='';status('Cloud copy deleted. Local game progress remains.');});
status(session.status()?'A sync connection is saved on this device.':'Not connected. A deployed service address is required.');
