import {climateRecords,climateSource} from './climate-records.js';
export {climateRecords,climateSource};
export const climateSteps=['Read the source','Compare two decades','Test a short-window claim','Critique uncertainty and the model'];
export const climateQuestions={
 0:{meaning:{label:'What does an anomaly of +1 °C mean?',options:[['absolute','The global average temperature was exactly 1 °C.'],['relative','It was 1 °C above this dataset’s 1951–1980 reference.'],['freezing','Every location was 1 °C above freezing.']],correct:'relative'},scope:{label:'What does each annual value represent?',options:[['local','Tomorrow’s weather at one island.'],['global','An analyzed global land–ocean temperature-change estimate.'],['raw','One unprocessed thermometer measurement.']],correct:'global'}},
 2:{pattern:{label:'How should the 2016–2018 change be interpreted alongside the decade comparison?',options:[['ended','Any drop over three years proves the long-term warming ended.'],['coexist','A short-interval decline can coexist with a warmer recent decade.'],['invalid','Any annual decline makes every measurement invalid.']],correct:'coexist'}},
 3:{uncertainty:{label:'The source reports hundredths of a degree. What does that establish?',options:[['zero','The estimates have no uncertainty.'],['resolution','It specifies reported precision; uncertainty needs a separate analysis.'],['interval','Every estimate has a 95% confidence interval of exactly ±0.01 °C.']],correct:'resolution'},inference:{label:'What is needed to investigate the physical causes of the observed change?',options:[['cause','The temperature graph alone uniquely identifies every cause.'],['color','Compare only the colors used in two graphs.'],['evidence','Combine observations, physical mechanisms, forcing evidence and model comparisons.']],correct:'evidence'},model:{label:'Can the game’s fixed-albedo blackbody balance reproduce this temperature history by itself?',options:[['limits','No. It omits atmospheric effects and changing forcings; its equilibrium emission temperature is not this surface record.'],['same','Yes. An equilibrium emission temperature is the same as every annual surface anomaly.'],['discard','No model can ever help explain measured climate change.']],correct:'limits'}}
};
export function climateWindow(start,end){const rows=climateRecords.filter(([y])=>y>=start&&y<=end);if(!Number.isInteger(start)||!Number.isInteger(end)||end<start||rows.length!==end-start+1)throw Error('Choose a complete archived year range.');return rows;}
export function climateMean(start,end){const rows=climateWindow(start,end);return rows.reduce((sum,[,v])=>sum+v,0)/rows.length;}
export function climateExpected(step){if(step===1){const early=climateMean(1980,1989),recent=climateMean(2010,2019);return {early,recent,difference:recent-early};}if(step===2){const rows=climateWindow(2016,2018);return {shortChange:rows.at(-1)[1]-rows[0][1]};}return {};}
export const climateFields=step=>[...Object.keys(climateExpected(step)),...Object.keys(climateQuestions[step]||{}),'notes'];
export function createClimateData(){return{version:1,sourceId:climateSource.id,sourceHash:climateSource.sha256,step:0,drafts:{},attempts:[],helped:[],complete:false};}
const number=s=>typeof s==='string'&&s.trim()!==''&&Number.isFinite(Number(s))?Number(s):null;
export function assessClimateData(step,draft){if(!climateSteps[step])throw Error('Unknown climate-data step.');const bad=[];for(const [key,value]of Object.entries(climateExpected(step)))if(number(draft[key])===null||Math.abs(number(draft[key])-value)>.00500001)bad.push(key);for(const [key,q]of Object.entries(climateQuestions[step]||{}))if(draft[key]!==q.correct)bad.push(key);return{correct:bad.length===0,feedback:bad.length?'Revisit '+bad.join(', ')+'. Check the source, the selected years, signed subtraction and the limits of the evidence.':'Your response matches the archived record and the stated scope. Keep the dataset baseline and analysis limits attached to your conclusion.'};}
export function editClimateData(s,key,value){if(s.complete)throw Error('This investigation is already recorded.');if(!climateFields(s.step).includes(key)||typeof value!=='string'||value.length>(key==='notes'?1500:60))throw Error('Invalid climate response.');s.drafts[s.step]??={};s.drafts[s.step][key]=value;s.feedback=null;}
export function checkClimateData(s,now=Date.now()){if(s.complete)throw Error('This investigation is already recorded.');if(s.attempts.length>=200)throw Error('This notebook holds 200 checked attempts. Export it for review.');const draft={...(s.drafts[s.step]||{})},result=assessClimateData(s.step,draft);const record={step:s.step,at:now,draft,correct:result.correct,assisted:s.helped.includes(s.step),sourceId:climateSource.id,sourceHash:climateSource.sha256};s.attempts.push(record);s.feedback=result;return record;}
export function climateReady(s){const last=s.attempts.at(-1);return !!last?.correct&&last.step===s.step&&JSON.stringify(last.draft)===JSON.stringify(s.drafts[s.step]||{});}
export function advanceClimateData(s){if(s.complete||!climateReady(s))throw Error('Check your current response before continuing.');if(s.step===3)s.complete=true;else s.step++;s.feedback=null;}
export function climateWorkedAnswer(step){return [...Object.entries(climateExpected(step)).map(([key,value])=>`${key}: ${Number(value.toFixed(3))} °C`),...Object.values(climateQuestions[step]||{}).map(q=>q.options.find(([v])=>v===q.correct)[1])].join(' ');}
export function helpClimateData(s){if(s.complete)throw Error('This investigation is already recorded.');if(!s.helped.includes(s.step))s.helped.push(s.step);s.feedback=null;return climateWorkedAnswer(s.step);}
export function climateIndependent(s){return s.complete&&s.helped.length===0&&[0,1,2,3].every(step=>s.attempts.some(a=>a.step===step&&a.correct&&!a.assisted));}
export function validateClimateData(s){
 if(!s||s.version!==1||s.sourceId!==climateSource.id||s.sourceHash!==climateSource.sha256||!Number.isInteger(s.step)||s.step<0||s.step>3||typeof s.complete!=='boolean'||!s.drafts||typeof s.drafts!=='object'||Array.isArray(s.drafts)||!Array.isArray(s.attempts)||s.attempts.length>200||!Array.isArray(s.helped)||new Set(s.helped).size!==s.helped.length||s.helped.some(x=>!Number.isInteger(x)||x<0||x>s.step))throw Error('Invalid climate-data checkpoint or source version.');
 const validDraft=(step,d)=>{if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Invalid climate draft.');for(const [key,value]of Object.entries(d))if(!climateFields(step).includes(key)||typeof value!=='string'||value.length>(key==='notes'?1500:60))throw Error('Invalid climate response.');};
 for(const [key,d]of Object.entries(s.drafts)){if(!/^[0-3]$/.test(key)||Number(key)>s.step)throw Error('Invalid climate step.');validDraft(Number(key),d);}
 let prior=-1;for(const a of s.attempts){if(!a||!Number.isInteger(a.step)||a.step<prior||a.step>s.step||a.step<0||!Number.isFinite(a.at)||typeof a.correct!=='boolean'||typeof a.assisted!=='boolean'||(a.assisted&&!s.helped.includes(a.step))||a.sourceId!==s.sourceId||a.sourceHash!==s.sourceHash)throw Error('Invalid climate attempt.');prior=a.step;validDraft(a.step,a.draft);if(assessClimateData(a.step,a.draft).correct!==a.correct)throw Error('Inconsistent climate answer.');}
 for(let step=0;step<(s.complete?4:s.step);step++){const last=s.attempts.filter(a=>a.step===step).at(-1);if(!last?.correct||JSON.stringify(last.draft)!==JSON.stringify(s.drafts[step]||{}))throw Error('Missing checked climate evidence.');}if(s.complete&&s.step!==3)throw Error('Invalid climate completion.');return s;
}
