import {plantTraitMissions} from './plant-traits-content.js';
import {earthSpaceMissions} from './earth-space-content.js';
import {biologyMissions} from './biology-content.js';
import {chemistryMissions} from './chemistry-content.js';
import {energyMissions} from './energy-content.js';
import {preparation} from './curriculum.js';
import {foundationMissions,foundationGlossary} from './foundation-content.js';
import {adapters} from './models.js';
export const regions=[
{id:'motion',name:'Motion Harbor',short:'Motion',icon:'⚙',color:'#eeb947',x:24,y:69,description:'Build a route. Set things in motion.',reward:'Cargo route restored'},
{id:'matter',name:'Matter Workshop',short:'Matter',icon:'⚗',color:'#b794e7',x:23,y:36,description:'Choose materials. Follow the matter.',reward:'Workshop reopened'},
{id:'living',name:'Living Valley',short:'Living',icon:'♧',color:'#85cda2',x:77,y:71,description:'Grow a biodome. Support a habitat.',reward:'Biodome flourishing'},
{id:'earth',name:'Earthwatch Ridge',short:'Earth',icon:'△',color:'#df9c75',x:16,y:16,description:'Track water. Protect the islands.',reward:'Rain gardens restored'},
{id:'signal',name:'Signal Coast',short:'Signal',icon:'ϟ',color:'#72ceda',x:81,y:29,description:'Send a signal. Power the night.',reward:'Night laboratory online'},
{id:'orbit',name:'Orbital Station',short:'Space',icon:'✦',color:'#93a9ed',x:51,y:13,description:'Find patterns beyond the horizon.',reward:'Observatory reopened'}
];
export const Q=(prompt,correct,...wrong)=>({prompt,options:[correct,...wrong],correct:0});
const questionSets={
 push:{predict:Q('What will a stronger push do to the same cart over the same one second?','Move it farther from its start.','Move it a shorter distance.','Have no effect on its motion.'),explain:Q('Why did the stronger push move the same cart farther?','The larger net force changed its motion more during the same time.','The stronger push made the cart lighter.','A push only matters after the cart stops.'),t1:Q('A toy wagon replaces the cart. To compare two pushes fairly, what should stay the same?','The wagon, surface, direction and push duration.','Only the color of the wagon.','Change the wagon and push duration together.'),t2:Q('A supply sled starts at rest. Two equal pushes act for the same time, but one sled has twice the mass. In this ideal model, which changes speed more?','The lower-mass sled.','The higher-mass sled.','Mass never affects the change in motion.')},
 direction:{predict:Q('What happens if we reverse a contact push on the resting cart?','The cart moves toward the other side.','The cart always moves right.','The cart cannot move left.'),explain:Q('What explains the signed positions in your two trials?','Push direction changes the direction of motion from rest.','A negative position means the cart vanished.','Both pushes acted in the same direction.'),t1:Q('A toy boat is at rest. Which contact push sends it toward a dock on its left?','A push toward the left.','A push toward the right.','Direction makes no difference.'),t2:Q('A crate needs to move east instead of west. What should you change in a direction test?','Reverse the push while keeping its strength and duration the same.','Change both its mass and the strength.','Push in the same direction for less time.')},
 force:{predict:Q('The resting cart is pulled left with 4 N. What happens with an equal 4 N pull right?','The cart remains at rest: the net force is zero.','It accelerates to the right.','It accelerates to the left.'),explain:Q('What determines the change in motion in this tug model?','The difference between the opposing forces.','The sum of the force sizes always moves it right.','Any two forces must cancel.'),t1:Q('Two robots pull a resting crate: 6 N east and 2 N west. What is the net force?','4 N east.','8 N east.','4 N west.'),t2:Q('A cart is already moving on an ideal frictionless lane. Equal opposing forces act on it. What happens?','Its velocity stays the same.','It immediately stops.','It must reverse direction.')},
 resistance:{predict:Q('At the same starting speed, how does larger rolling resistance affect stopping distance?','The rover stops in a shorter distance.','The rover travels farther.','The resistance creates extra motion.'),explain:Q('What does the shorter stopping distance tell us?','Stronger resistance slows the same rover more quickly.','The rover’s energy disappears from the universe.','The surface changed the rover’s mass.'),t1:Q('A trolley enters two lanes at equal speed. Which lane is better for a short stopping area?','The lane with greater modeled rolling resistance.','The lane with smaller modeled rolling resistance.','They must always stop in the same place.'),t2:Q('To test a new stopping surface fairly, which comparison is valid?','Use the same trolley and entry speed on both surfaces.','Use a different mass and speed on each surface.','Change both the surface and the ramp height.')},
 ramp:{predict:Q('What do you predict when the same rover starts from a higher ramp?','It exits faster and stops farther along the same lane.','It exits slower and stops sooner.','It always stops at the same place.'),explain:Q('Which claim explains your ramp trials?','A greater starting height transfers more gravitational energy into motion; on the same lane it travels farther.','The higher ramp makes the rover’s mass increase.','The delivery bay pulls the rover toward it.'),t1:Q('A new trolley must stop 2.00 m beyond the exit. With the same resistance ratio of 0.20, which height should you choose?','0.40 m — a higher start for a farther bay.','0.20 m — a lower start for a farther bay.','0.50 m — every bay needs the tallest ramp.'),t2:Q('A sorting ramp has a closer tray, 1.00 m beyond the exit. Which setting works with the same model?','0.20 m — a lower start for the nearer tray.','0.40 m — a higher start for the nearer tray.','0.30 m — height never changes stopping distance.')},
 collision:{predict:Q('For identical carts, which carries more kinetic energy into the same barrier?','The faster cart.','The slower cart.','Speed cannot affect kinetic energy.'),explain:Q('Where does the cart’s kinetic energy go when the soft barrier stops it?','It transfers to the barrier and surroundings through deformation, heating and sound.','It is destroyed.','It becomes extra mass in the cart.'),t1:Q('A parcel cart must deliver gently. With the same mass and barrier, what lowers the energy to be absorbed?','Reduce its entry speed.','Increase its entry speed.','Paint the barrier blue.'),t2:Q('A second cart has twice the mass at the same speed. What does this model predict?','Twice the kinetic energy must be transferred to stop it.','The same kinetic energy.','Half the kinetic energy.')},
 thermal:{predict:Q('For equal thickness, area and temperatures, what does a lower conductivity do?','Reduces heat transfer per second.','Makes more heat flow per second.','Makes the temperatures identical instantly.'),explain:Q('Why does the low-conductivity sample transfer less heat each second?','The material resists heat transfer more under the same conditions.','Cold moves into it as a substance.','It creates extra energy.'),t1:Q('Two lunch-box walls have the same thickness. Which material better slows heat transfer?','The lower-conductivity material.','The higher-conductivity material.','Conductivity is unrelated to heat transfer.'),t2:Q('Keep the same material and temperature difference, but double the wall thickness. What does this slab model predict?','Half the heat-transfer rate.','Twice the heat-transfer rate.','Exactly the same rate.')},
 matter:{predict:Q('Sample A is 10 g. Adding more sample B in a closed container will…','Increase the combined mass by the mass added.','Make sample A disappear.','Always leave the combined mass at 10 g.'),explain:Q('Why can we add the two sample masses?','All of the matter stays inside the system.','Mixing creates matter.','The samples have the same color.'),t1:Q('A sealed bag contains 12 g of sand and 8 g of pebbles. Ignoring the bag, what is the total?','20 g.','12 g.','4 g.'),t2:Q('A sealed 30 g ice-and-water sample melts completely. What is the mass of its contents after melting?','30 g — the matter stayed inside.','Less than 30 g because ice disappeared.','More than 30 g because liquid is heavier.')},
 plant:{predict:Q('For this fictional plant, will increasing light always increase growth?','No. The model has a best light level; too much reduces growth.','Yes. More light must always mean more growth.','No light gives the most growth.'),explain:Q('What can the matched biodome trials support?','Light level affects growth in this modeled species when other conditions are held constant.','All real plants grow best at this exact light level.','Light is the only influence on every plant.'),t1:Q('A different plant species arrives. What is the best next investigation?','Repeat controlled light trials for that species; its optimum may differ.','Assume it has exactly the same optimum.','Change its light, water and soil together.'),t2:Q('One plant grows less than two others under the same light. What should you do?','Use replicates and compare the groups; one plant may vary.','Conclude that light has no effect from one plant.','Discard every result that differs.')},
 habitat:{predict:Q('If each animal needs the same food amount, what does more food supply do in this model?','Supports more animals, if water and shelter remain adequate.','Guarantees the real population instantly grows.','Eliminates the need for water.'),explain:Q('What does the food-budget result actually tell us?','How many animals the specified food could support, not a complete population prediction.','The exact future population of a real ecosystem.','Food has no relationship to survival.'),t1:Q('A pond has 40 daily food units. Each fish requires 5. How many can that food support?','8 fish.','40 fish.','5 fish.'),t2:Q('The pond has enough food but loses clean water. What is a reasonable conclusion?','The food-only model is insufficient; water may limit survival.','Food guarantees every fish survives.','Water cannot affect an ecosystem.')},
 runoff:{predict:Q('For the same rain and soil, what does more vegetation cover do in our model?','Reduces runoff by increasing retained water.','Creates extra rainfall.','Has no effect on runoff.'),explain:Q('Which conclusion is supported by the modeled trials?','Greater cover reduces modeled runoff under the conditions kept fixed.','Every real storm will follow these exact values.','Plants make water disappear.'),t1:Q('A new hillside has different soil. Can you apply the exact runoff numbers without testing?','No. Soil and saturation can change runoff.','Yes. Soil never affects water.','Yes. The same number fits every place.'),t2:Q('Which is a fair test of vegetation cover on two trays?','Use equal rainfall, slope and soil; change cover only.','Change rainfall and slope too.','Compare a dry tray with a flooded tray and change cover.')},
 wave:{predict:Q('With wave speed fixed, increasing frequency will…','Shorten the wavelength.','Lengthen the wavelength.','Increase the wave speed automatically.'),explain:Q('What explains the wave pattern you observed?','More cycles fit each second; at fixed speed their spacing becomes shorter.','Larger frequency always means larger amplitude.','The wave stops moving at higher frequency.'),t1:Q('A wave travels at 10 m/s with frequency 5 Hz. What is its wavelength?','2 m.','50 m.','5 m.'),t2:Q('Frequency stays at 2 Hz but the medium gives a speed of 20 m/s. What is the wavelength?','10 m.','2 m.','40 m.')},
 energy:{predict:Q('The night lab has 800 Wh stored and 80% delivery efficiency. Can it supply 60 W for 10 hours?','Yes: 640 Wh can be delivered and 600 Wh is needed.','No: 60 W always needs more than 800 Wh.','Yes, because solar panels produce energy all night.'),explain:Q('How should the night energy budget be accounted for?','Compare delivered Wh with load × hours; conversion loss transfers to surroundings.','Compare watts directly with watt-hours as if they are identical.','Ignore the conversion loss.'),t1:Q('A weather station needs 90 W for 10 h. Can the same 640 Wh delivered supply cover it?','No: it needs 900 Wh, leaving a 260 Wh shortfall.','Yes: 90 is less than 640.','Yes: the battery makes more energy when needed.'),t2:Q('A new store holds 1,000 Wh at 80% efficiency. A 70 W lab runs for 10 h. What is the margin?','100 Wh: 800 Wh delivered minus 700 Wh demand.','300 Wh: efficiency can be ignored.','700 W: power and energy are identical.')},
 orbit:{predict:Q('Around the same Sun-like star, a larger circular orbit has…','A longer orbital period.','A shorter orbital period.','Exactly the same period.'),explain:Q('What relationship do the modeled orbits show?','Orbital period increases with radius for the same central star.','Every planet has the same orbital speed and period.','A planet needs no gravity to remain in orbit.'),t1:Q('At 4 AU, what period does our Sun-like-star model predict?','8 Earth years.','4 Earth years.','16 Earth years.'),t2:Q('A new star has a different mass. Can you reuse the exact Sun-like-star formula unchanged?','No. The central mass affects the relationship.','Yes. Star mass never matters.','Yes. All stars have the same gravity.')}
};
const specs=[
['first-move','motion','First Move','push','K–2','The supply cart is stuck at the workshop. Compare gentle and stronger contact pushes.',[1,3],null,'Pushes and pulls'],
['which-way','motion','Which Way?','direction','K–2','The dock is on the other side of the cart. Find out how push direction changes its path.',[-1,1],null,'Direction'],
['keep-it-fair','motion','Keep It Fair','push','3–5','Pip changed the cart AND the push. Help the robot make a test that answers one question.',[2,4],null,'Controlled variables'],
['tug-together','motion','Tug Together','force','3–5','Two dock robots are pulling a cart in opposite directions. Investigate when a resting cart stays still.',[4,6],null,'Balanced forces'],
['stronger-side','motion','Stronger Side','force','3–5','The cargo needs to go right. Investigate what happens when one pull is stronger.',[2,6],null,'Unbalanced forces'],
['stopping-zone','motion','Stopping Zone','resistance','3–5','The rover rolls past the loading crew. Compare stopping lanes at the same starting speed.',[.1,.4],null,'Rolling resistance'],
['rover-rescue','motion','Rover Rescue','ramp','3–5','The supply rover cannot reach its delivery bay. Change the ramp height and restore the route.',[.1,.3],[1.45,1.55],'Ramp height & energy'],
['gentle-delivery','motion','Gentle Delivery','collision','3–5','Fragile seed trays need a gentle arrival. Compare equal-mass carts meeting the same soft barrier.',[1,2],null,'Motion & energy transfer'],
['choose-a-brake','motion','Choose a Brake','resistance','3–5','Choose a stopping lane for a short dock. Keep entry speed the same while comparing resistance.',[.2,.4],[.48,.55],'Evidence-based design'],
['cargo-budget','motion','Cargo Budget','ramp','3–5','You have one rover, one surface and three approved ramp parts. Deliver with a 0.30 m ramp or lower.',[.1,.3],[1.45,1.55],'Design constraints'],
['new-trolley','motion','New Trolley','ramp','3–5','A new trolley route has its bay 2 metres beyond the exit. Apply the ramp idea to this new job.',[.2,.4],[1.95,2.05],'Transfer to a new vehicle'],
['restore-route','motion','Restore the Route','ramp','3–5','Reconnect the island supply route: choose the ramp, then explain how the stopping lane and a gentle arrival work together.',[.15,.3],[1.45,1.55],'Harbor capstone'],
['material-scout','matter','Material Scout','thermal','3–5','The seed shelter loses heat. Compare equal-thickness materials to slow the transfer.',[.1,.4],null,'Material properties'],
['nothing-lost','matter','Nothing Lost','matter','3–5','Track two samples inside a sealed mixing container. Account for every gram.',[5,20],null,'Conservation of matter'],
['shelter-designer','matter','Shelter Designer','thermal','9–12','Choose a shelter wall that transfers no more than 20 watts under our test conditions.',[.2,.5],[0,20.01],'Conduction model'],
['biodome-balance','living','Biodome Balance','plant','6–8','Three matched seedlings need a light plan. Compare seven simulated days in controlled chambers.',[25,75],null,'Environmental growth factors'],
['habitat-supply','living','Habitat Supply','habitat','3–5','Restore the research habitat’s daily food supply. Find out how many animals it could support.',[20,40],null,'Organism needs'],
['growth-detective','living','Growth Detective','plant','6–8','A very bright chamber grew less than expected. Investigate an optimum and explain the model’s limits.',[75,100],null,'Variation & model limits'],
['rain-garden','earth','Rain Garden','runoff','3–5','Rain is washing across the settlement. Compare planted and less-planted ground.',[0,75],null,'Water & ground cover'],
['catch-the-water','earth','Catch the Water','runoff','6–8','Reduce modeled runoff to 42.5 litres or less without changing the rain or hillside.',[25,75],[0,42.51],'Systems & water budgets'],
['ridge-research','earth','Ridge Research','runoff','9–12','Test a simple runoff model and identify the evidence needed before applying it to a new hillside.',[50,100],null,'Assumptions & transfer'],
['signal-sprint','signal','Signal Across the Bay','wave','6–8','The islands need a matching beacon pattern. Explore frequency and the spacing between wave peaks.',[1,4],null,'Wave patterns'],
['tune-the-link','signal','Tune the Link','wave','6–8','The receiver expects a 2-metre wavelength. Tune the transmitter in our fixed-speed wave model.',[2,5],[1.99,2.01],'Frequency & wavelength'],
['night-lab','signal','Power the Night Lab','energy','9–12','Keep the lab running until dawn. Compare demand, delivered energy and conversion loss.',[60,90],[0,1000],'Power, energy & storage'],
['orbital-patterns','orbit','Orbital Patterns','orbit','6–8','Reopen the observatory. Compare how long modeled planets take to orbit the same star.',[1,3],null,'Patterns in orbital motion'],
['outer-outpost','orbit','Outer Outpost','orbit','9–12','The remote observatory needs a modeled orbital period of 8 Earth years. Find its circular orbit.',[2,4],[7.99,8.01],'Kepler model'],
['mission-planner','orbit','Mission Planner','energy','9–12','Plan a remote station’s ten-hour dark period. Use a transparent energy model to defend the design.',[50,90],[0,1000],'Space-system energy budget']
];
export const missions=specs.map(([id,region,title,adapter,band,story,compare,target,skill],index)=>({id,region,title,adapter,band,story,compare,target,skill,index,version:1,initial:adapters[adapter].initial,questions:structuredClone(questionSets[adapter]),minutes:adapter==='plant'||adapter==='energy'?'12–20':'5–12',prerequisites:id==='rover-rescue'?['keep-it-fair']:id==='restore-route'?['rover-rescue','stopping-zone','gentle-delivery']:[],review:'Early access · educator review pending'}));
const cap=missions.find(m=>m.id==='restore-route');
cap.questions.t1=Q('The first ramp reaches the handoff bay, but the next lane must stop the cart sooner at the same entry speed. Which design change helps?','Use a lane with larger rolling resistance, then test it.','Raise the first ramp and ignore the entry speed.','Use a lower-resistance stopping lane.');
cap.questions.t2=Q('The final cart reaches a soft barrier too fast. Which revision reduces energy transferred at arrival while keeping the mass the same?','Reduce its entry speed, then check that it still reaches the destination.','Increase its speed to make the contact shorter.','Remove the barrier and assume energy vanishes.');
for(const entry of foundationMissions)missions.push({...entry,index:missions.length,version:1,initial:adapters[entry.adapter].initial,target:null,minutes:'8–15',prerequisites:[],review:'Early access · educator review pending'});
for(const entry of energyMissions)missions.push({...entry,band:'9–12',index:missions.length,version:1,initial:adapters[entry.adapter].initial,minutes:'15–25',prerequisites:['night-lab'],review:'Early access · educator review pending'});
for(const entry of chemistryMissions)missions.push({...entry,region:'matter',index:missions.length,version:1,initial:adapters[entry.adapter].initial,target:null,minutes:'10–20',prerequisites:[],review:'Early access · educator review pending'});
for(const entry of [...biologyMissions,...plantTraitMissions])missions.push({...entry,region:'living',index:missions.length,version:1,initial:adapters[entry.adapter].initial,target:null,minutes:'10–20',prerequisites:[],review:'Early access · educator review pending'});
for(const entry of earthSpaceMissions)missions.push({...entry,index:missions.length,version:1,initial:adapters[entry.adapter].initial,target:null,minutes:'10–20',prerequisites:[],review:'Early access · educator review pending'});
export const byId=Object.fromEntries(missions.map(m=>[m.id,m]));
export const glossary={trial:'One run of an experiment with the settings and results recorded.',variable:'Something that can change in an investigation.',force:'A push or pull from an interaction.',ramp:'A sloping surface that connects two heights.',distance:'How far apart two positions are. Here, stopping distance starts at the ramp exit.',energy:'A quantity we track as systems change. Energy can transfer between objects and their surroundings.',power:'How fast energy is transferred or used. A watt is one joule per second.',frequency:'The number of repeated cycles each second. Its unit is hertz (Hz).',replicate:'Another sample tested under the same conditions.',model:'A simplified representation used to explain or predict. Every model has limits.',conductivity:'A property describing how readily a material transfers heat.',orbit:'A path around another object under gravity.',fair:'A comparison that changes one chosen variable while keeping the relevant others the same.'};

Object.assign(glossary,foundationGlossary);
for(const m of missions)m.prerequisites=preparation[m.id]||m.prerequisites;
