const q=(prompt,answers)=>({prompt,options:answers.map(a=>a[0]),correct:0,pictures:answers.map(a=>({kind:a[1],label:a[0]}))});
export const earlyNatureEdits={
 'light-window':{version:2,lesson:'Light can pass through some materials. Other materials block more light. Try different panels with the same lamp and distance. Look at the screen.',questions:{
 predict:q('Which panel lets the most light reach the screen?',[['The panel that lets light through.','light-pass'],['The panel that blocks the light.','light-block'],['Every panel lets the same light through.','same-amount']]),
 explain:q('Why is the screen darker behind one panel?',[['That panel blocks more light.','light-block'],['The screen eats the lamp.','lamp-gone'],['We moved the lamp farther away.','lamp-far']]),
 t1:q('Choose a window so a friend can see a lamp through it. What should you test?',[['Does light pass through it?','light-pass'],['Is its name nice?','name-tag'],['Is it heavy?','weight']]),
 t2:q('Make a dark puppet shadow. Which material helps?',[['One that blocks most light.','light-block'],['One that lets almost all light through.','light-pass'],['Every material makes the same shadow.','same-amount']])}},
 'vibration-detective':{version:2,lesson:'A vibration is a back-and-forth motion. Its size and how often it repeats are different things. Here you change the size while the repeats stay the same.',questions:{
 predict:q('Make the vibration bigger. What changes?',[['It moves farther from the middle.','vibration-wide'],['It repeats more often.','vibration-fast'],['It stops moving.','vibration-still']]),
 explain:q('What changed in our bigger-motion test?',[['The movement got bigger; the repeats stayed the same.','vibration-wide'],['It repeated more often.','vibration-fast'],['Nothing moved.','vibration-still']]),
 t1:q('Two strings repeat equally often. One moves farther from its middle. What is different?',[['The size of the movement.','vibration-wide'],['How often it repeats.','vibration-fast'],['Neither string moves.','vibration-still']]),
 t2:q('A machine needs more wiggles each second. Keep the wiggles the same size. What should change?',[['How often it wiggles.','vibration-fast'],['Only the size of each wiggle.','vibration-wide'],['Only the paint color.','paint']])}},
 'float-materials':{version:2,lesson:'Try blocks of the same size in the same water. A block less heavy than the same amount of water can float with its top above water. A heavier block sinks in this model. Water still pushes upward on a sinking block.',questions:{
 predict:q('Which same-size block can float with its top above the water?',[['One less heavy than the same amount of water.','float'],['One heavier than the same amount of water.','sink'],['Every block must float.','all-float']]),
 explain:q('Why does our heavier block sink even though water pushes up?',[['Its downward weight is greater than the upward water push.','weight-down'],['Water never pushes up on sinking blocks.','no-up'],['Its paint color makes it sink.','paint']]),
 t1:q('A toy floats with its top above water. What can you observe?',[['Only part of the toy is underwater.','submerged-less'],['The whole toy is below the surface.','sink'],['None of the toy touches water.','above-water']]),
 t2:q('Try the same block in a different liquid. What should you keep track of?',[['Which block and which liquid we use.','block-liquid'],['Only the block’s paint color.','paint'],['Only the container’s name.','name-tag']])}},
 'shadow-patterns':{version:2,lesson:'A pole blocks sunlight and makes a shadow. In this model, a higher Sun makes a shorter shadow. Keep the pole and ground the same. Never look directly at the real Sun.',questions:{
 predict:q('Keep the pole the same. Move the model Sun higher. What happens to the shadow?',[['It gets shorter.','shadow-short'],['It gets longer.','shadow-long'],['It must stay the same length.','same-amount']]),
 explain:q('The pole stayed the same. Why did its shadow change?',[['The sunlight came from a different direction.','sun-direction'],['The pole secretly grew taller.','tall-pole'],['Shadows always have one fixed length.','same-amount']]),
 t1:q('Use the same model Sun position. Which pole makes a longer shadow?',[['The taller pole.','tall-pole'],['The shorter pole.','short-pole'],['All poles make the same shadow.','same-amount']]),
 t2:q('Watch one pole’s shadow at different times. What should stay the same?',[['The pole and its place on the ground.','same-pole'],['Only the pole’s paint color.','paint'],['Move the pole to a new place each time.','move-pole']])}}
};
export const earlyBuild={
 push:['Change only how strong the push is.','one-change','Change the push and the cart.','different'],direction:['Change only the push direction.','one-change','Change the push and the cart.','different'],
 light:['Change the panel. Keep the lamp and distance the same.','light-pass','Change the panel and move the lamp.','lamp-far'],vibration:['Change only the movement size.','vibration-wide','Change the movement size and repeats together.','vibration-both'],density:['Change the block. Keep its size and the water the same.','block-liquid','Change the block and the liquid together.','many-tools'],shadow:['Change the model Sun height. Keep the pole the same.','sun-direction','Change both the Sun height and the pole.','tall-pole']
};
export const earlyComparisons={push:['far','near','equal','Farther','Less far','Same distance'],direction:['right','left','equal','Farther right','Farther left','Same position'],light:['light-pass','light-block','same-amount','More light','Less light','Same light amount'],vibration:['vibration-wide','vibration-narrow','same-amount','Bigger movement','Smaller movement','Same movement size'],density:['submerged-more','submerged-less','same-amount','More underwater','Less underwater','Same fraction underwater'],shadow:['shadow-long','shadow-short','same-amount','Longer shadow','Shorter shadow','Same shadow length']};
export function natureDiagram(kind){const ink='#244b55';
 if(['light-pass','light-block','lamp-far','lamp-gone'].includes(kind)){const pass=kind==='light-pass';return `<circle cx="20" cy="45" r="12" fill="#e8bc5f" stroke="${ink}"/><path d="M35 35H80M35 45H80M35 55H80${pass?'M95 35H175M95 45H175M95 55H175':''}" stroke="${ink}" stroke-width="3"/><rect x="80" y="15" width="15" height="60" fill="${pass?'#c3e0e0':ink}" stroke="${ink}"/><path d="M180 15V75" stroke="${ink}" stroke-width="4"/>${kind==='lamp-gone'?`<path d="M5 28L35 60M5 60L35 28" stroke="${ink}" stroke-width="3"/>`:''}${kind==='lamp-far'?`<path d="M10 82H175" stroke="${ink}" stroke-dasharray="4 3"/>`:''}`;}
 if(kind.startsWith('vibration-')){const a=['vibration-wide','vibration-both'].includes(kind)?25:kind==='vibration-still'?0:9,cycles=['vibration-fast','vibration-both'].includes(kind)?4:2;return `<path d="M10 45H190" stroke="#90a5a8" stroke-dasharray="3 3"/><polyline points="${Array.from({length:81},(_,i)=>`${10+i*2.25},${45+a*Math.sin(i/80*2*Math.PI*cycles)}`).join(' ')}" fill="none" stroke="${ink}" stroke-width="4"/>`;}
 if(['float','sink','all-float','submerged-more','submerged-less','above-water','block-liquid','weight-down','no-up'].includes(kind)){const y=['sink','weight-down','no-up'].includes(kind)?50:kind==='above-water'?5:kind==='submerged-more'?35:20;return `<path d="M20 10V85H180V10" fill="#e1f0f2" stroke="${ink}" stroke-width="2"/><path d="M22 45H178" stroke="${ink}" stroke-width="2"/><rect x="82" y="${y}" width="35" height="32" fill="#e8bc5f" stroke="${ink}" stroke-width="2"/>${kind==='all-float'?`<rect x="30" y="25" width="30" height="30" fill="#e8bc5f" stroke="${ink}"/><rect x="140" y="25" width="30" height="30" fill="#e8bc5f" stroke="${ink}"/>`:''}${kind==='weight-down'||kind==='no-up'?`<path d="M140 35V75l-7 -9m7 9l7 -9M60 72V50l-7 9m7 -9l7 9" fill="none" stroke="${ink}" stroke-width="3"/>`:''}${kind==='no-up'?`<path d="M48 45L72 73M48 73L72 45" stroke="${ink}" stroke-width="3"/>`:''}`;}
 if(['shadow-short','shadow-long','sun-direction','tall-pole','short-pole','same-pole','move-pole'].includes(kind)){const short=kind==='shadow-short',top=kind==='short-pole'?50:25,end=kind==='short-pole'?90:short?65:140,sunX=short?30:10,sunY=short?5:10;return `<path d="M15 75H190" stroke="${ink}" stroke-width="2"/><path d="M40 75V${top}" stroke="${ink}" stroke-width="6"/><path d="M40 77H${end}" stroke="${ink}" stroke-width="5"/>${kind.startsWith('shadow-')?`<circle cx="${sunX}" cy="${sunY}" r="5" fill="#e8bc5f"/><path d="M${sunX} ${sunY}L${end} 75" stroke="${ink}"/>`:''}${kind==='sun-direction'?`<path d="M12 10L100 65M80 10L110 65" stroke="${ink}" stroke-width="3"/>`:''}${kind==='move-pole'?`<path d="M160 75V25" stroke="${ink}" stroke-dasharray="4 3"/>`:''}`;}
 if(kind==='same-amount')return `<rect x="20" y="25" width="45" height="40" fill="#e8bc5f" stroke="${ink}"/><rect x="135" y="25" width="45" height="40" fill="#e8bc5f" stroke="${ink}"/><path d="M85 37H115M85 52H115" stroke="${ink}" stroke-width="4"/>`;
 if(kind==='paint')return `<rect x="45" y="25" width="40" height="40" fill="#e8bc5f" stroke="${ink}"/><rect x="115" y="25" width="40" height="40" fill="#83bdb6" stroke="${ink}"/><path d="M120 30L145 55M120 40L135 55" stroke="${ink}"/>`;
 if(kind==='name-tag')return `<path d="M30 20H155L180 45 155 70H30Z" fill="#f4ecd2" stroke="${ink}"/><text x="90" y="55" text-anchor="middle" font-size="28" fill="${ink}">ABC</text>`;
 if(kind==='weight')return `<path d="M75 30Q75 5 100 5Q125 5 125 30L145 75H55Z" fill="#b4c9cd" stroke="${ink}" stroke-width="3"/>`;
 if(kind==='many-tools')return `<circle cx="35" cy="45" r="20" fill="#e8bc5f" stroke="${ink}"/><rect x="80" y="20" width="35" height="50" fill="#83bdb6" stroke="${ink}"/><path d="M140 70L160 20 185 70Z" fill="#b4c9cd" stroke="${ink}"/>`;
 return null;
}

export function earlyControl(mission,input){if(mission?.band!=='K–2')return null;const configs={push:['Push strength',1,1,['Gentlest','Gentle','Medium','Strong','Strongest']],direction:['Push direction',-1,2,['Left','Right']],light:['How much light the panel blocks',0,25,['None','A little','Half','Most','All']],vibration:['Movement size',1,1,['Smallest','Small','Medium','Big','Biggest']],density:['Same-size block compared with water',200,200,['Much lighter','Lighter','Somewhat lighter','A little lighter','Same weight','A little heavier','Heavier']],shadow:['Model Sun position',15,15,['Low','Partway up','Middle','Higher','High']]};const c=configs[mission.adapter];if(!c)return null;const index=(input-c[1])/c[2];return{label:c[0],value:c[3][index]??String(input),low:c[3][0],high:c[3].at(-1)};}
