import {carbonPools,initialCarbon} from './ecosystem-models.js';
const n=x=>Number(x.toFixed(3)),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const box=(x,y,label,value,color)=>`<rect x="${x}" y="${y}" width="175" height="75" rx="12" fill="${color}" stroke="#436b62"/><text x="${x+87.5}" y="${y+25}" text-anchor="middle" font-size="16" fill="#163e43">${label}</text><text x="${x+87.5}" y="${y+55}" text-anchor="middle" font-size="20" fill="#163e43">${value}</text>`;
export function ecosystemScene(adapter,input,result){
 const bg='<rect width="800" height="410" fill="#e5f1df"/>',arrow='<defs><marker id="ecosystem-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#396d65"/></marker></defs>';
 if(adapter==='ecosystem-energy'){
  if(!result)return bg+`<text x="35" y="55" font-size="24" fill="#163e43">Start: ${input} J chemical energy in plants</text><text x="35" y="105" font-size="20">Run the allocation test to record the energy pathways.</text><text x="35" y="155" font-size="18">Energy remaining in organisms and waste is still chemical energy.</text><text x="35" y="190" font-size="18">Thermal transfer does not return to plants as food energy.</text>`;
  const s=result.stores,parts=[['Plants',s.plants,'#81b774'],['Herbivores',s.grazers,'#e4bd72'],['Predators',s.predators,'#b09bd1'],['Detritus',s.detritus,'#b8a07d'],['Thermal',s.thermal,'#df9273']];let start=45;
  return bg+`<text x="35" y="40" font-size="22">Final energy account · initial plant energy ${result.producer} J</text>`+box(20,75,'Plant chemical',n(s.plants)+' J','#bfdbac')+box(310,75,'Herbivore chemical',n(s.grazers)+' J','#eddaa7')+box(600,75,'Predator chemical',n(s.predators)+' J','#d1bfdf')+box(160,205,'Detritus chemical',n(s.detritus)+' J','#d2bea0')+box(460,205,'Thermal transfer',n(s.thermal)+' J','#ecc3aa')+parts.map(([label,value,color])=>{const width=value/result.producer*710,rect=`<rect x="${start}" y="315" width="${width}" height="30" fill="${color}" stroke="white"><title>${label}: ${n(value)} J</title></rect>`;start+=width;return rect;}).join('')+`<text x="35" y="380" font-size="18">All five destinations sum to ${n(result.total)} J. No energy is destroyed.</text>`;
 }
 const pools=result?.pools||initialCarbon;
 return bg+arrow+`<text x="30" y="32" font-size="20">Carbon account · ${result?'after six steps':'untested starting pools'}</text><text x="30" y="55" font-size="16">Light supplies energy; it adds no carbon to this account.</text>`+
 box(20,80,'Air CO₂ carbon',n(pools.air),'#c0deed')+box(310,80,'Plants',n(pools.plants),'#bfdbac')+box(600,80,'Herbivores',n(pools.grazers),'#eddaa7')+box(600,265,'Predators',n(pools.predators),'#d1bfdf')+box(310,265,'Dead matter / waste',n(pools.detritus),'#d2bea0')+box(20,265,'Decomposers',n(pools.decomposers),'#bdd3b0')+
 '<g fill="none" stroke="#396d65" stroke-width="2.5" marker-end="url(#ecosystem-arrow)"><path d="M198 118H305"/><path d="M488 118H595"/><path d="M685 158V259"/><path d="M595 300H490"/><path d="M305 300H198"/><path d="M100 260V161"/><path d="M400 160V260"/><path d="M625 160L450 260"/></g><g font-size="13" fill="#163e43"><text x="202" y="103">Photosynthesis</text><text x="505" y="103">Feeding</text><text x="698" y="214">Feeding</text><text x="495" y="287">Death / waste</text><text x="219" y="287">Decay</text><text x="12" y="218">Respiration</text><text x="409" y="213">Litter</text><text x="525" y="222">Waste</text></g>'+`<text x="25" y="371" font-size="17">Total: ${n(result?.total??200)} carbon units. Arrows show selected pathways.</text><text x="25" y="394" font-size="15">All living pools return carbon to air by respiration. Every route is recorded below.</text>`;
}
export function ecosystemRecord(result,adapter){if(!result)return '';
 if(adapter==='ecosystem-energy'){return `<details class="model-card" open><summary>Food-web energy record</summary><table><caption>Final destinations of ${result.producer} J initial plant chemical energy</caption><thead><tr><th scope="col">Destination</th><th scope="col">Energy (J)</th></tr></thead><tbody>${Object.entries(result.stores).map(([key,value])=>`<tr><th scope="row">${({plants:'Retained in plants',grazers:'Retained in herbivores',predators:'Retained in predators',detritus:'Chemical energy in dead matter / waste',thermal:'Thermal transfer to surroundings'})[key]}</th><td>${n(value)}</td></tr>`).join('')}<tr><th scope="row">Total</th><td>${n(result.total)}</td></tr></tbody></table><details><summary>Intermediate feeding and allocation amounts</summary><table><tbody>${result.flows.map(([label,value])=>`<tr><th scope="row">${label}</th><td>${n(value)} J</td></tr>`).join('')}</tbody></table><p>Intermediate amounts overlap: do not add them as independent final destinations. Only the five final accounts form the conserved total.</p></details><p>Detritus retains chemical energy for possible later decomposition. Those later processes are outside this one-pass calculation. Thermal energy is not converted back into food energy here. Transfer fractions are fictional, not a universal “10% rule.”</p></details>`;}
 return `<details class="model-card" open><summary>Food-web carbon record</summary><div class="table-scroll"><table><caption>All saved carbon pools · arbitrary carbon units, not energy or organism counts</caption><thead><tr><th scope="col">Step</th>${Object.values(carbonPools).map(label=>`<th scope="col">${label}</th>`).join('')}<th scope="col">Total</th></tr></thead><tbody>${result.records.map(row=>`<tr><th scope="row">${row.step}</th>${Object.keys(carbonPools).map(key=>`<td>${n(row.pools[key])}</td>`).join('')}<td>${n(row.total)}</td></tr>`).join('')}</tbody></table></div><p>The total stays 200 carbon units. Displayed values are rounded; calculations retain full precision. Carbon in air remains matter. Carbon returned by respiration can later enter plants through photosynthesis; sunlight supplies the needed energy.</p><details><summary>All step-by-step carbon transfers and assumptions</summary><p>All fractions use the start-of-step pools. Photosynthesis moves 10% of air carbon to plants. Grazing consumes ${n(result.grazing*100)}% of plant carbon; predation consumes 20% of herbivore carbon. Each feeding amount splits into 30% consumer growth, 40% carbon returned to air by the feeding consumer’s respiration, and 30% waste. These combined routes do not imply the source plant is doing the herbivore’s respiration.</p><p>Separate respiration/death fractions from stored body carbon: plants 5%/2%, herbivores 10%/3%, predators 10%/3%, decomposers 10%/2%. Decomposers process ${n(result.decay*100)}% of detritus, sending 40% to their growth and 60% to air through respiration. Every fraction is an invented teaching parameter.</p>${result.records.slice(1).map(row=>`<h3>Step ${row.step}</h3><table><thead><tr><th>Process</th><th>From</th><th>To</th><th>Carbon units</th></tr></thead><tbody>${row.flows.map(f=>`<tr><th scope="row">${esc(f.process)}</th><td>${carbonPools[f.from]}</td><td>${carbonPools[f.to]}</td><td>${n(f.amount)}</td></tr>`).join('')}</tbody></table>`).join('')}</details></details>`;
}
