import {byId} from './content.js';
import {adapters,simulate} from './models.js';
import {esc} from './visuals.js';
export const supportsFairSetup=m=>m.adapter==='ramp'||!!adapters[m.adapter]?.rampVariant;
const lane=id=>id==='library-ramp'?.1:id==='greenhouse-ramp'?.4:.2;
export function fairSetupFor(m,r){r.fairSetups??={};const key=String(r.attempts?.build||0);return r.fairSetups[key]??={adapter:m.adapter,mode:'interactive',variable:'height',first:m.compare[0],second:m.compare[1],mass:2,resistance:lane(m.adapter)};}
export function validateFairSetup(s){if(!s||!supportsFairSetup({adapter:s.adapter})||!['interactive','text'].includes(s.mode)||!['height','height-and-surface'].includes(s.variable)||s.mass!==2||s.resistance!==lane(s.adapter))throw Error('Invalid fair-test setup.');simulate(s.adapter,s.first);simulate(s.adapter,s.second);return s;}
export function fairSetupReady(s){validateFairSetup(s);return s.mode==='text'||s.variable==='height'&&s.first!==s.second;}
export function changeFairSetup(m,r,key,value){const s=fairSetupFor(m,r);if(!['mode','variable','first','second'].includes(key))throw Error('Fixed conditions stay locked.');const next={...s,[key]:value};validateFairSetup(next);Object.assign(s,next);return s;}
export function validateFairSetups(records,mission=null){if(!records||typeof records!=='object'||Array.isArray(records))throw Error('Invalid fair-test configurations.');for(const [k,s]of Object.entries(records)){if(!/^\d+$/.test(k))throw Error('Invalid fair-test attempt.');validateFairSetup(s);if(mission&&s.adapter!==byId[mission]?.adapter)throw Error('Fair setup belongs to another mission model.');}}
export function fairSetupView(m,r){const s=fairSetupFor(m,r),model=adapters[m.adapter];return `<fieldset class="model-card fair-setup"><legend>Build two fair ramp tests</legend>${s.mode==='text'?`<p>Use the written fair-test question below. You can switch back to the interactive setup at any time.</p><button class="secondary" data-action="fair-mode" data-mode="interactive">Use interactive setup</button>`:`<p>Pip: “Choose two starting heights. Keep the cart and lane the same so height is the one change.”</p><label class="field">Variable to change<select data-fair-setting="variable"><option value="height" ${s.variable==='height'?'selected':''}>Ramp height only</option><option value="height-and-surface" ${s.variable==='height-and-surface'?'selected':''}>Height and lane surface together</option></select></label>${['first','second'].map((k,i)=>`<label class="field">Test ${i===0?'A':'B'} height<input type="range" data-fair-setting="${k}" min="${model.min}" max="${model.max}" step="${model.step}" value="${s[k]}"><output>${s[k].toFixed(2)} m</output></label>`).join('')}<div class="locked-conditions"><span>🔒 Same 2 kg cart</span><span>🔒 Same resistance ${s.resistance.toFixed(2)}</span><span>🔒 Start from rest</span></div><p role="status">${fairSetupReady(s)?'One difference: ramp height. These settings are ready for your fair-test check.':'Setup blocked: choose different heights and keep the lane surface fixed.'}</p><button class="text-button" data-action="fair-mode" data-mode="text">Use the written checklist</button>`}</fieldset>`;}
export function plannedTrialButtons(m,r){const s=r.fairSetups?.[String(r.attempts?.build||0)];if(!s||s.mode!=='interactive'||!fairSetupReady(s))return '';return `<div class="planned-trials"><p>Your saved fair-test setup</p>${[s.first,s.second].map((x,i)=>`<button class="secondary" data-action="planned-trial" data-input="${x}">Run test ${i===0?'A':'B'} · ${x.toFixed(2)} m</button>`).join('')}</div>`;}
