/** Additional foundation models. Every display is generated from these authoritative outputs. */
export const foundationAdapters={
 light:{label:'Light-path bench',input:'Blocked light',unit:'%',min:0,max:100,step:25,initial:0,output:'Light reaching the screen',outUnit:'%',control:'material transmission',fixed:'Same light source · same distance · no scattered light collected',limits:'A simple transmission budget. Blocked light is absorbed or redirected; it is not destroyed. Real materials can reflect, scatter and absorb different amounts. This model does not calculate those separate channels.',law:'Transmitted fraction = 100% − blocked fraction.',run:x=>({value:100-x,duration:1,series:[{t:0,x:100},{t:1,x:100-x}]})},
 vibration:{label:'Vibration viewer',input:'Vibration amplitude',unit:'mm',min:1,max:5,step:1,initial:2,output:'Peak-to-peak displacement',outUnit:'mm',control:'amplitude',fixed:'Frequency = 2 Hz · same ideal vibrating surface',limits:'A slowed visual vibration model. Amplitude measures displacement; frequency measures cycles per second. Sound loudness depends on more than displacement, and this model does not predict decibels or audible pitch.',law:'Displacement = A sin(2πft); peak-to-peak displacement = 2A.',run:a=>({value:2*a,duration:2,series:Array.from({length:121},(_,i)=>({t:i/60,x:a*Math.sin(4*Math.PI*i/60)}))})},
 density:{label:'Float-or-sink tank',input:'Object density',unit:'kg/m³',min:200,max:1400,step:200,initial:600,output:'Submerged volume fraction',outUnit:'%',control:'object density',fixed:'Water density = 1000 kg/m³ · equal object volume · ignore surface tension',limits:'Objects less dense than water can float with a fraction submerged equal to their density ratio. At equal density the ideal object is neutrally buoyant. Denser objects sink: a reported 100% means fully submerged, not successful floating.',law:'Floating fraction = object density / water density; cap display at 100% for full submersion.',run:d=>({value:Math.min(100,d/10),state:d<1000?'floats':d===1000?'neutral':'sinks',duration:2,series:[{t:0,x:0},{t:2,x:Math.min(100,d/10)}]})},
 heat:{label:'Warming-water bench',input:'Energy transferred',unit:'kJ',min:0,max:40,step:10,initial:10,output:'Final water temperature',outUnit:'°C',control:'transferred energy',fixed:'Water mass = 1 kg · initial temperature = 20°C · specific heat = 4.2 kJ/(kg·°C)',limits:'Liquid water stays far below boiling. Constant heat capacity, uniform temperature, no energy transferred to the cup or air. Temperature is not the same quantity as energy; changing mass changes the temperature response.',law:'ΔT = Q/(mc); final temperature = 20 + Q/4.2.',run:q=>({value:20+q/4.2,duration:2,series:Array.from({length:11},(_,i)=>({t:i/5,x:20+(q*i/10)/4.2}))})},
 circuit:{label:'Circuit bench',input:'Resistance',unit:'Ω',min:2,max:10,step:2,initial:4,output:'Steady current',outUnit:'A',control:'resistance',fixed:'Ideal 6 V source · one closed path · ohmic resistor',limits:'Ideal low-voltage circuit model, not instructions for connecting real equipment. The source holds voltage constant and the resistor follows Ohm’s law. An open circuit has no steady current; this bench displays a closed circuit only.',law:'I = V/R, with V = 6 V. Power transferred to resistor = VI.',run:r=>({value:6/r,power:36/r,duration:1,series:[{t:0,x:6/r},{t:1,x:6/r}]})},
 heredity:{label:'Pea-trait nursery',input:'Second parent A-gamete chance',unit:'%',min:0,max:100,step:50,initial:50,output:'Expected offspring with dominant trait',outUnit:'%',control:'second parent genotype',fixed:'First parent Aa · complete dominance · one fictional pea trait · independent gametes',limits:'A one-gene Mendelian probability model, not a model for all traits. Expected percentages do not guarantee the outcomes of a small family. Dominant does not mean stronger, better or more common.',law:'P(aa) = 0.5 × P(second parent contributes a); P(dominant trait) = 1 − P(aa).',run:p=>({value:50+p/2,genotypes:{AA:p/2,Aa:50,aa:50-p/2},duration:1,series:[{t:0,x:50+p/2}]})},
 diffusion:{label:'Cell membrane model',input:'Starting inside concentration',unit:'units/L',min:0,max:10,step:2,initial:8,output:'Equilibrium dye concentration',outUnit:'units/L',control:'inside concentration',fixed:'Two equal 1 L compartments · outside starts at 2 units/L · membrane passes dye · no water flow',limits:'Ideal diffusion between equal well-mixed volumes. The dye moves both ways; net transfer follows the concentration difference. Real cells have selective membranes, active transport and many other solutes, which are not included.',law:'Equilibrium concentration = (initial inside + initial outside)/2; total dye is conserved.',run:c=>({value:(c+2)/2,total:c+2,duration:5,series:Array.from({length:51},(_,i)=>({t:i/10,x:(c+2)/2+(c-2)/2*Math.exp(-i/5),outside:(c+2)/2-(c-2)/2*Math.exp(-i/5)}))})},
 shadow:{label:'Sun-and-shadow station',input:'Sun elevation',unit:'degrees',min:15,max:75,step:15,initial:30,output:'Shadow length',outUnit:'m',control:'Sun elevation',fixed:'Vertical 1 m pole · flat ground · Sun rays treated as parallel',limits:'Local shadow geometry at a chosen Sun elevation. This is not a complete seasons model: Earth’s axial tilt and the observer’s latitude determine seasonal patterns. Never look directly at the real Sun.',law:'Shadow length = pole height / tan(Sun elevation).',run:a=>({value:1/Math.tan(a*Math.PI/180),duration:1,series:[{t:0,x:1/Math.tan(a*Math.PI/180)}]})}
};
