const fields=[
 {key:'vary',label:'What will you change?',options:['Cart mass','Cart mass and net force together','Track direction only'],correct:0},
 {key:'measure',label:'What evidence will you record?',options:['Cart color after each test','Change in speed over the same time interval','Only the final mass'],correct:1},
 {key:'hold',label:'What must stay the same?',options:['Only the cart color','Nothing: change everything','Net force, starting speed, track and force duration'],correct:2}
];
export function needsPlan(m){return m.id==='same-force-more-mass';}
export function planKey(r){return String(r.attempts?.build||0);}
export function currentPlan(r){return r.investigationPlans?.[planKey(r)]||{};}
export function choosePlan(r,key,value){const field=fields.find(f=>f.key===key);if(value===null&&field){if(r.investigationPlans?.[planKey(r)])delete r.investigationPlans[planKey(r)][key];return;}if(!field||!Number.isInteger(value)||value<0||value>=field.options.length)throw Error('Invalid investigation choice');r.investigationPlans??={};r.investigationPlans[planKey(r)]??={};r.investigationPlans[planKey(r)][key]=value;}
export function evaluatePlan(r){const p=currentPlan(r),missing=fields.filter(f=>!Number.isInteger(p[f.key])),wrong=fields.filter(f=>Number.isInteger(p[f.key])&&p[f.key]!==f.correct);return {complete:!missing.length,correct:!missing.length&&!wrong.length,feedback:missing.length?'Choose a variable, a measurement and the conditions to hold fixed.':wrong.length?'Revisit '+wrong.map(f=>f.key==='vary'?'the variable you change':f.key==='measure'?'the evidence you measure':'the conditions you hold fixed').join(', ')+'. A useful test separates mass from force and compares changes in motion.':'Your plan separates mass from force and measures the resulting change in motion.'};}
export function planMarkup(r){const p=currentPlan(r);return `<fieldset class="model-card"><legend>Plan the mass investigation</legend><p>Find out how mass affects a cart’s change in motion under the same net force. Choose your plan before testing.</p>${fields.map(f=>`<label class="field">${f.label}<select data-investigation="${f.key}"><option value="">Choose…</option>${f.options.map((s,i)=>`<option value="${i}" ${p[f.key]===i?'selected':''}>${s}</option>`).join('')}</select></label>`).join('')}</fieldset>`;}
export function planSnapshot(r){const p=currentPlan(r);return {attempt:Number(planKey(r)),choices:{...p},decisions:fields.map(f=>({question:f.label,answer:f.options[p[f.key]]??null})),...evaluatePlan(r)};}
export function validatePlans(plans){if(!plans||typeof plans!=='object'||Array.isArray(plans))throw Error('Invalid investigation plans');for(const [attempt,p]of Object.entries(plans)){if(!/^\d+$/.test(attempt)||!p||typeof p!=='object'||Array.isArray(p))throw Error('Invalid investigation plan');for(const [key,value]of Object.entries(p)){const f=fields.find(f=>f.key===key);if(!f||!Number.isInteger(value)||value<0||value>=f.options.length)throw Error('Invalid investigation choice');}}}

export function planNarration(){return 'Plan the mass investigation. '+fields.map(f=>f.label+' '+f.options.join('. ')).join('. ');}
export function validatePlanHistory(history){if(!Array.isArray(history))throw Error('Invalid plan history');for(const p of history){if(!p||!Number.isInteger(p.attempt)||p.attempt<0||!Number.isFinite(p.at)||typeof p.correct!=='boolean'||typeof p.complete!=='boolean'||typeof p.assisted!=='boolean'||typeof p.feedback!=='string'||!Array.isArray(p.decisions)||p.decisions.length!==3)throw Error('Invalid plan history');validatePlans({[p.attempt]:p.choices});for(const d of p.decisions)if(!d||typeof d.question!=='string'||(d.answer!==null&&typeof d.answer!=='string'))throw Error('Invalid plan decision');}}
