import {validatePlacement} from './placement.js';
import {validateBuildOffRecord} from './build-off.js';
import {validateRouteCapstone} from './route-capstone.js';
export const CATEGORIES=['predict','fair','interpret','explain','transfer1','transfer2'];
export function skillState(run,now=Date.now()) {if(!run)return 'Unseen';if(run.reviewFailed)return 'Needs review';if(!CATEGORIES.every(k=>run.evidence?.[k]))return 'Learning';if(run.retainedAt)return 'Retained';return 'Demonstrated';}
export function recordCheck(run,category,correct,assisted=false){if(!CATEGORIES.includes(category))throw Error('Unknown evidence category');run.evidence??={};if(correct&&!assisted)run.evidence[category]=true;return correct&&!assisted;}
export function fairPair(trials){return trials.length>=2&&trials.some((a,i)=>trials.some((b,j)=>i!==j&&a.model===b.model&&a.input!==b.input&&JSON.stringify(a.options)===JSON.stringify(b.options)));}
export function createRun(mission){return{mission:mission.id,version:1,stage:'notice',input:mission.initial,trialIds:[],trials:[],evidence:{},assistance:{},attempts:{},answers:{},notes:'',completed:false};}
export function makeProfile(name='Explorer',avatar='🧑🏽‍🚀'){return{id:crypto.randomUUID(),name,avatar,runs:{},inventions:[],arcade:{},createdAt:Date.now()};}
export function validateSave(data){if(!data||data.version!==1||!Array.isArray(data.profiles)||!data.profiles.length||data.profiles.length>12)throw Error('This is not a supported Science Quest save.');const ids=new Set();for(const p of data.profiles){if(typeof p.id!=='string'||ids.has(p.id)||typeof p.name!=='string'||p.name.length>30||!p.runs||typeof p.runs!=='object'||!Array.isArray(p.inventions))throw Error('Invalid explorer data.');ids.add(p.id);if(p.placement!==undefined)validatePlacement(p.placement);if(p.buildOffRecords!==undefined){if(!Array.isArray(p.buildOffRecords))throw Error('Invalid Build-Off history');p.buildOffRecords.forEach(validateBuildOffRecord);}for(const r of Object.values(p.runs)){if(!r||typeof r.mission!=='string'||!Array.isArray(r.trials)||!r.evidence||!['notice','predict','build','test','compare','explain','transfer1','transfer2','done'].includes(r.stage))throw Error('Invalid mission checkpoint.');if(r.capstone)validateRouteCapstone(r.capstone);for(const t of r.trials){if(!t||typeof t.model!=='string'||!Number.isFinite(t.input)||!Number.isFinite(t.value))throw Error('Invalid trial data.');}}}if(!ids.has(data.active))throw Error('Missing active explorer.');return data;}
