import {earthSpaceAdapters} from './earth-space-models.js';
import {biologyAdapters} from './biology-models.js';
import {chemistryAdapters} from './chemistry-models.js';
import {planningAdapters} from './energy-planning.js';
import {foundationAdapters} from './foundation-models.js';
/** Deterministic teaching models. All physical quantities use SI unless the key names a different unit. */
export const MODEL_VERSION = 1;
export const clamp = (x,a,b)=>Math.max(a,Math.min(b,x));
export const round = (n,d=2)=>Number(n.toFixed(d));
export const adapters={
 ...foundationAdapters,...planningAdapters,...chemistryAdapters,...biologyAdapters,...earthSpaceAdapters,
 ramp:{label:'Rover ramp',input:'Ramp height',unit:'m',min:.1,max:.5,step:.05,initial:.2,output:'Stopping distance',outUnit:'m',control:'height',fixed:'Same 2 kg rover · same surface · 2 m ramp run',limits:'Ideal lossless ramp, starting at rest. Wheels are visual; rotational inertia is omitted. The flat lane has constant rolling resistance of 0.20 × weight. This is rolling resistance, not sliding friction.',law:'v = √(2gh); d = h / c. g = 9.8 m/s², c = 0.20.',run:(h,o={})=>{const c=o.resistance??.2,g=9.8,v=Math.sqrt(2*g*h),d=h/c,run=2,angle=Math.atan(h/run),a=g*Math.sin(angle),tr=Math.sqrt(2*Math.hypot(run,h)/a),ts=v/(c*g); const series=[];for(let t=0;t<=ts+.0001;t+=1/60)series.push({t,x:v*t-.5*c*g*t*t,v:Math.max(0,v-c*g*t)});series.push({t:ts,x:d,v:0});return{value:d,speed:v,duration:tr+ts,rampDuration:tr,series,energy:2*g*h,loss:2*g*h};}},
 push:{label:'Push laboratory',input:'Contact force',unit:'N',min:1,max:5,step:1,initial:2,output:'Distance after 1 second',outUnit:'m',control:'push',fixed:'Same 2 kg cart · force acts for 1 s · starts at rest',limits:'One-dimensional motion on an ideal level lane with no resistance. A constant contact force acts for one second. After release, this ideal cart would keep moving.',law:'a = F / m; x = ½at²; t = 1 s, m = 2 kg.',run:f=>({value:f/4,speed:f/2,duration:1,series:Array.from({length:61},(_,i)=>({t:i/60,x:.25*f*(i/60)**2,v:.5*f*i/60}))})},
 direction:{label:'Direction lane',input:'Push direction',unit:'',min:-1,max:1,step:2,initial:1,output:'Position after 1 second',outUnit:'m',control:'direction',fixed:'Same 2 N push · same 2 kg cart · starts at rest',limits:'Left is negative, right is positive. Ideal horizontal lane, no resistance. Position is measured from the starting marker.',law:'x = ½(F/m)t² with signed force, t = 1 s.',run:d=>({value:d*.5,speed:1,duration:1,series:Array.from({length:61},(_,i)=>({t:i/60,x:d*.5*(i/60)**2,v:d*i/60}))})},
 force:{label:'Tug test',input:'Right-hand pull',unit:'N',min:0,max:8,step:1,initial:4,output:'Position after 1 second',outUnit:'m',control:'right force',fixed:'Left pull = 4 N · mass = 2 kg · starts at rest',limits:'Forces act along one line on a cart initially at rest, without resistance. Balanced forces keep this resting cart at rest; balanced forces do not stop an already moving cart.',law:'Net force = F right − 4 N; a = F net / 2 kg; x = ½at².',run:f=>({value:(f-4)/4,net:f-4,speed:Math.abs((f-4)/2),duration:1,series:Array.from({length:61},(_,i)=>({t:i/60,x:(f-4)/4*(i/60)**2,v:(f-4)/2*i/60}))})},
 resistance:{label:'Stopping lane',input:'Rolling resistance ratio',unit:'',min:.1,max:.5,step:.05,initial:.2,output:'Stopping distance',outUnit:'m',control:'surface resistance',fixed:'Same rover · same entry speed of 2 m/s · level lane',limits:'A constant resistance ratio is an invented teaching parameter, not a measured property of a real named material. Resistance transfers the rover’s kinetic energy to the surroundings.',law:'d = v² / (2cg); v = 2 m/s, g = 9.8 m/s².',run:c=>{let t=2/(c*9.8);return{value:4/(2*c*9.8),speed:2,duration:t,series:Array.from({length:61},(_,i)=>({t:t*i/60,x:2*t*i/60-.5*c*9.8*(t*i/60)**2,v:2*(1-i/60)}))};}},
 collision:{label:'Soft barrier',input:'Entry speed',unit:'m/s',min:.5,max:3,step:.5,initial:1,output:'Energy transferred to barrier',outUnit:'J',control:'speed',fixed:'Same 2 kg cart · identical stopping barrier',limits:'The barrier brings the cart to rest without rebound. All initial kinetic energy is transferred to the barrier and surroundings. Energy is not destroyed. Peak force and injury are not predicted.',law:'Energy transferred = ½mv², m = 2 kg.',run:v=>({value:v*v,speed:v,duration:1,series:Array.from({length:61},(_,i)=>({t:i/60,x:v*(i/60-(i/60)**2/2),v:v*(1-i/60)}))})},
 thermal:{label:'Material test',input:'Conductivity',unit:'W/(m·K)',min:.1,max:.5,step:.1,initial:.2,output:'Heat transfer rate',outUnit:'W',control:'material conductivity',fixed:'Area = 1 m² · thickness = 0.1 m · temperature difference = 10 K',limits:'Steady-state conduction through a uniform slab. Temperatures are held fixed. The values are illustrative, not a guide for constructing a real shelter.',law:'Heat transfer rate = kAΔT / L.',run:k=>({value:k*100,duration:2,series:Array.from({length:8},(_,i)=>({t:i,x:k*100}))})},
 matter:{label:'Closed-system bench',input:'Mass of sample B',unit:'g',min:5,max:25,step:5,initial:10,output:'Total mass in closed container',outUnit:'g',control:'sample B mass',fixed:'Sample A = 10 g · closed container · no material enters or leaves',limits:'Total contents only; container mass is excluded. Mixing has no mass loss in this model. No recipe or chemical reaction is being simulated.',law:'Total mass = mass A + mass B.',run:m=>({value:10+m,duration:2,series:[{t:0,x:10},{t:1,x:10+m}]})},
 plant:{label:'Biodome',input:'Light level',unit:'%',min:0,max:100,step:25,initial:25,output:'Mean height after 7 simulated days',outUnit:'cm',control:'light',fixed:'Three matched starting plants · same water, soil, temperature and species',limits:'A fictional species with optimum light at 75%. Growth slows above that level. Three fixed replicate differences illustrate variation, not real statistical uncertainty. Genetics, nutrients, disease and competition are not modeled.',law:'Daily modeled growth = max(0, 1 − ((light − 75)/75)²) cm/day. Starting height = 2 cm.',run:l=>{const rate=Math.max(0,1-((l-75)/75)**2);return{value:2+7*rate,duration:7,replicates:[.9,1,1.1].map(k=>2+7*rate*k),series:Array.from({length:8},(_,i)=>({t:i,x:2+i*rate})),timeUnit:'simulated day'};}},
 habitat:{label:'Habitat resources',input:'Food supply',unit:'units/day',min:10,max:50,step:10,initial:20,output:'Animals supported by food',outUnit:'animals',control:'food supply',fixed:'Each animal needs 5 food units/day · water and shelter adequate',limits:'A resource-budget model, not a population forecast. Food alone does not describe an ecosystem; predation, disease, reproduction and species interactions are omitted.',law:'Supported animals = floor(food supply / 5).',run:f=>({value:Math.floor(f/5),duration:1,series:[{t:0,x:Math.floor(f/5)}]})},
 runoff:{label:'Rain catchment',input:'Vegetation cover',unit:'%',min:0,max:100,step:25,initial:25,output:'Modeled runoff',outUnit:'L',control:'cover',fixed:'Rainfall volume = 100 L · same slope and soil',limits:'Illustrative linear runoff model. More cover increases modeled retention. Actual runoff also depends on soil, saturation, rainfall intensity and slope. Not a flood forecast.',law:'Runoff = 100 × (0.8 − 0.005 × cover).',run:c=>({value:80-.5*c,duration:2,series:Array.from({length:6},(_,i)=>({t:i,x:(80-.5*c)*i/5}))})},
 wave:{label:'Signal scope',input:'Frequency',unit:'Hz',min:1,max:5,step:1,initial:2,output:'Wavelength',outUnit:'m',control:'frequency',fixed:'Wave speed = 10 m/s · amplitude stays fixed',limits:'A simplified wave with a constant speed in a uniform medium. This is a visual wave model, not an audible pitch scale. Frequency changes wavelength, not wave speed in this model.',law:'Wavelength = wave speed / frequency.',run:f=>({value:10/f,frequency:f,duration:2,series:Array.from({length:101},(_,i)=>({t:i/100,x:Math.sin(2*Math.PI*f*i/100)}))})},
 energy:{label:'Night power lab',input:'Required load',unit:'W',min:30,max:100,step:10,initial:60,output:'Delivered-energy margin',outUnit:'Wh',control:'load',fixed:'Night = 10 h · storage = 800 Wh · delivery efficiency = 80% · solar = 0',limits:'Constant load, no battery power limit or reserve. Capacity and efficiency are invented teaching inputs. Conversion loss transfers energy to the surroundings. This is not real electrical installation guidance.',law:'Delivered energy = storage × efficiency. Demand = power × hours. Margin = delivered − demand.',run:(w,o={})=>{const storage=o.storage??800,eff=o.efficiency??.8,hours=o.hours??10;return{value:storage*eff-w*hours,demand:w*hours,delivered:storage*eff,loss:storage-storage*eff,duration:hours,series:Array.from({length:hours+1},(_,i)=>({t:i,x:storage*eff-w*i})),timeUnit:'simulated hour'};}},
 orbit:{label:'Observatory model',input:'Orbit radius',unit:'AU',min:1,max:4,step:1,initial:1,output:'Orbital period',outUnit:'Earth years',control:'orbit radius',fixed:'Same Sun-like star · circular orbit approximation · negligible planet mass',limits:'Kepler’s relationship for a small body around a Sun-mass star. AU is Earth’s mean orbital distance. The model omits other bodies and orbital eccentricity. Diagram sizes are not to scale.',law:'Period in Earth years = √(radius in AU³).',run:r=>({value:Math.sqrt(r**3),duration:Math.sqrt(r**3),series:Array.from({length:61},(_,i)=>({t:i/60*Math.sqrt(r**3),x:Math.sin(i/60*2*Math.PI)*r,y:Math.cos(i/60*2*Math.PI)*r}))})}
};
export function simulate(adapter,input,options={}) {const m=adapters[adapter];if(!m||!Number.isFinite(input)||input<m.min-1e-9||input>m.max+1e-9)throw new Error('Input outside model range');if(Math.abs((input-m.min)/m.step-Math.round((input-m.min)/m.step))>1e-7)throw new Error('Input is not an allowed step');return{...m.run(input,options),model:adapter,modelVersion:MODEL_VERSION,input,options:{...options}};}
export function insideBay(distance,low=1.45,high=1.55){return distance>=low&&distance<=high;}

export function validEnergyConstruction(draft){return !!draft&&draft.supply==='*'&&draft.demand==='*'&&draft.margin==='-';}
