/** Authored synthetic records, independent of the interactive track simulator. */
export const motionDataCases=[
 {id:'harbor',title:'Harbor instrument cart',mass:2,points:[[0,.5],[1,1.49],[2,2.51],[3,3.48],[4,4.5]],brief:'Estimate the nearly constant acceleration and net force. Predict velocity at 5 s if the same pattern continues.'},
 {id:'cargo',title:'Heavier cargo cart',mass:4,points:[[0,.25],[1,.76],[2,1.24],[3,1.76],[4,2.25]],brief:'Analyze a heavier cart. Does its lower acceleration require a lower net force? Compare your result with the previous record.'},
 {id:'return',title:'Returning supply cart',mass:3,points:[[0,3],[1,2.51],[2,1.99],[3,1.5],[4,1]],brief:'Right is positive. This cart is still moving right but slowing down. Keep the signs of acceleration and net force in your answer.'}
];
export const changingRecord={mass:2,points:[[0,0],[1,1],[2,3],[3,6],[4,10]]};
export const critiqueOptions={claim:['One constant net force fits the whole record.','Net force changes over the record.','Any moving cart has zero net force.'],evidence:['Velocity is positive in every moving interval.','The cart has the same mass throughout.','Equal-time velocity changes grow from 1 to 4 m/s.'],next:['Record velocity at shorter equal time intervals and check force over time.','Measure only the paint color.','Discard every point that does not fit a constant force.']};
export const DATA_VERSION=1;
export function createMotionData(){return {version:DATA_VERSION,step:0,drafts:{},attempts:[],helped:[],complete:false};}
export function motionAnswer(c){const first=c.points[0],last=c.points.at(-1),acceleration=(last[1]-first[1])/(last[0]-first[0]);return {acceleration,force:c.mass*acceleration,prediction:first[1]+5*acceleration};}
const number=s=>typeof s==='string'&&s.trim()!==''&&Number.isFinite(Number(s))?Number(s):null;
export function assessMotionData(step,draft){if(step===3){const correct=draft.claim==='1'&&draft.evidence==='2'&&draft.next==='0';return {correct,feedback:correct?'The changing velocity increments support a changing net force. More time-resolved measurements can test that explanation.':'Check equal-time velocity changes, connect them to acceleration, and choose a follow-up that tests the model.'};}const c=motionDataCases[step];if(!c)throw Error('Unknown motion record');const expected=motionAnswer(c),bad=Object.keys(expected).filter(k=>number(draft[k])===null||Math.abs(number(draft[k])-expected[k])>({acceleration:.03,force:.06,prediction:.06}[k])+1e-9);return {correct:!bad.length,feedback:bad.length?'Revisit '+bad.join(', ')+'. Use velocity change over elapsed time, retain direction signs, and check the units.':'Your estimates fit the record within the stated tolerances. A close fit supports this model for this interval; it does not prove every force is constant.'};}
export function editMotionData(s,key,value){if(s.complete)throw Error('This investigation is already recorded');const keys=s.step===3?Object.keys(critiqueOptions):['acceleration','force','prediction'];if(!keys.includes(key)||typeof value!=='string'||value.length>40)throw Error('Invalid data response');s.drafts[s.step]??={};s.drafts[s.step][key]=value;s.feedback=null;}
export function checkMotionData(s,now=Date.now()){if(s.complete)throw Error('This investigation is already recorded');const draft=s.drafts[s.step]||{},result=assessMotionData(s.step,draft);const record={step:s.step,draft:{...draft},correct:result.correct,assisted:s.helped.includes(s.step),at:now};s.attempts.push(record);s.feedback=result;return record;}
export function advanceMotionData(s){const latest=s.attempts.at(-1);if(!latest?.correct||latest.step!==s.step||JSON.stringify(latest.draft)!==JSON.stringify(s.drafts[s.step]||{}))throw Error('Check this record before continuing');if(s.step===3)s.complete=true;else s.step++;s.feedback=null;}
export function helpMotionData(s){if(s.complete)throw Error('This investigation is already recorded');if(!s.helped.includes(s.step))s.helped.push(s.step);s.feedback=null;return s.step===3?'The equal-time velocity changes are 1, 2, 3 and 4 m/s. With fixed mass, changing acceleration means changing net force. Collect finer time measurements.':Object.entries(motionAnswer(motionDataCases[s.step])).map(([k,v])=>`${k}: ${v}`).join(' · ');}
export function motionDataIndependent(s){return s.complete&&s.helped.length===0&&[0,1,2,3].every(step=>s.attempts.some(a=>a.step===step&&a.correct&&!a.assisted));}
export function validateMotionData(s){if(!s||s.version!==DATA_VERSION||!Number.isInteger(s.step)||s.step<0||s.step>3||typeof s.complete!=='boolean'||!s.drafts||typeof s.drafts!=='object'||Array.isArray(s.drafts)||!Array.isArray(s.attempts)||!Array.isArray(s.helped)||s.helped.some(x=>!Number.isInteger(x)||x<0||x>3))throw Error('Invalid motion-data investigation');const validDraft=(step,d)=>{if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Invalid motion-data draft');for(const [k,v]of Object.entries(d))if(!(step===3?Object.keys(critiqueOptions):['acceleration','force','prediction']).includes(k)||typeof v!=='string'||v.length>40)throw Error('Invalid motion-data response');};for(const [key,d]of Object.entries(s.drafts)){if(!/^[0-3]$/.test(key))throw Error('Invalid motion-data step');validDraft(Number(key),d);}for(const a of s.attempts){if(!a||!Number.isInteger(a.step)||a.step<0||a.step>3||!Number.isFinite(a.at)||typeof a.assisted!=='boolean'||typeof a.correct!=='boolean')throw Error('Invalid motion-data attempt');validDraft(a.step,a.draft);if(assessMotionData(a.step,a.draft).correct!==a.correct)throw Error('Inconsistent motion-data result');}for(let i=0;i<(s.complete?4:s.step);i++){const last=s.attempts.filter(a=>a.step===i).at(-1);if(!last?.correct||JSON.stringify(last.draft)!==JSON.stringify(s.drafts[i]||{}))throw Error('Missing motion-data evidence');}if(s.complete&&s.step!==3)throw Error('Invalid motion-data completion');return s;}
