/** Optional starting-point suggestions. These responses never award independent skill evidence. */
export const placementItems=[
 {id:'push',prompt:'The same cart starts at rest each time. Which push moves it farther during the same short time?',options:['A stronger push.','A weaker push.','No push.'],bridge:'first-move',reason:'Start by exploring how a push changes motion.'},
 {id:'fair',prompt:'You want to compare two ramp heights. Which plan makes the comparison fair?',options:['Use the same cart and surface; change only height.','Change height, cart and surface together.','Use a new cart for every height.'],bridge:'keep-it-fair',reason:'Practice changing one variable while holding the others fixed.'},
 {id:'data',prompt:'The same rover stops 1 metre from the exit in Trial A and 2 metres in Trial B. What do these measurements show?',options:['Trial B went farther.','Trial A went farther.','The distances are equal.'],bridge:'rover-rescue',reason:'Use the rover investigation to connect measurements with a design.'},
 {id:'energy',prompt:'A device uses 20 watts for 3 hours. How much energy does it use?',options:['60 watt-hours.','23 watt-hours.','60 watts per hour.'],bridge:'night-lab',reason:'Explore the difference between power and energy in Night Lab.'}
];
export function createPlacement(){return{version:1,status:'active',responses:[],choice:null};}
export function validatePlacement(p){if(!p||p.version!==1||!['active','complete','skipped'].includes(p.status)||!Array.isArray(p.responses)||p.responses.length>placementItems.length||p.responses.some(x=>!Number.isInteger(x)||x<0||x>2)||(p.choice!==null&&(!Number.isInteger(p.choice)||p.choice<0||p.choice>2))||(p.status==='complete'&&p.responses.length!==placementItems.length)||(p.status==='active'&&p.responses.length===placementItems.length))throw Error('Invalid starting-point activity');return p;}
export function choosePlacement(p,choice){validatePlacement(p);if(p.status!=='active'||!Number.isInteger(choice)||choice<0||choice>2)throw Error('Choose an available response');p.choice=choice;}
export function advancePlacement(p){validatePlacement(p);if(p.status!=='active'||p.choice===null)throw Error('Choose a response or skip the activity');p.responses.push(p.choice);p.choice=null;if(p.responses.length===placementItems.length)p.status='complete';return p;}
export function skipPlacement(p){validatePlacement(p);p.status='skipped';p.choice=null;return p;}
export function placementSuggestion(p){validatePlacement(p);if(p.status!=='complete')return null;const first=placementItems.find((item,i)=>p.responses[i]!==0);return first?{mission:first.bridge,reason:first.reason}:{mission:'night-reserve',reason:'Your responses suggest trying a guided energy-planning investigation. These four choices do not demonstrate all of its prerequisite skills.'};}
