/** Fictional heritable plant types; these parameters are teaching assumptions, not fitted data. */
export function growthGroup(type,light){
 if(!['A','B'].includes(type)||![25,50,75,100].includes(light))throw Error('Unknown plant type or light setting');
 const optimum=type==='A'?50:100,rate=Math.max(0,1-((light-optimum)/75)**2);
 return {type,light,mean:2+7*rate,replicates:[.9,1,1.1].map(k=>2+7*rate*k),series:Array.from({length:8},(_,day)=>({t:day,x:2+day*rate}))};
}
const shared={unit:'%',min:25,max:100,step:25,initial:25,outUnit:'cm',limits:'Two fictional heritable types with assumed different light responses. Starting height is 2 cm. Three fixed replicate multipliers illustrate variation, not independent random samples or confidence bounds. Light is a model index, not a calibrated real growing recommendation. No DNA mechanism, adaptation within an individual, or universal ranking of types is implied.',law:'Height = 2 + day × max(0, 1 − ((light − optimum)/75)²). Assumed optima: A = 50, B = 100. Replicates multiply daily growth by 0.9, 1 and 1.1.'};
export const plantTraitAdapters={
 'trait-light':{...shared,label:'Two types, changing light',input:'Shared light level',output:'Type A mean height after day 7',control:'light level',fixed:'Both heritable types A and B · 3 plants per type · same starting height, water, soil and temperature',run:light=>{const groups=['A','B'].map(t=>growthGroup(t,light));return{value:groups[0].mean,duration:7,series:groups[0].series,groups,timeUnit:'simulated day'};}},
 'trait-type':{...shared,label:'Inherited differences in one environment',input:'Heritable type (0 = A, 1 = B)',unit:'index',min:0,max:1,step:1,initial:0,output:'Mean height after day 7',control:'heritable type',fixed:'Light fixed at 50% · 3 plants · same starting height, water, soil and temperature',run:type=>{const group=growthGroup(type===0?'A':'B',50);return{value:group.mean,duration:7,series:group.series,groups:[group],timeUnit:'simulated day'};}}
};
const n=x=>Number(x.toFixed(2));
export function traitScene(r){return `<rect width="800" height="410" fill="#e5f1df"/><text x="40" y="40" font-size="22" fill="#163e43">Fictional plant types · day 7 comparison</text>${r.groups.map((g,i)=>{const x=100+i*350;return `<text x="${x}" y="85" font-size="20" fill="#163e43">Type ${g.type} · ${g.light}% light</text>${g.replicates.map((h,j)=>`<path d="M${x+35+j*65} 285V${285-h*17}" stroke="#386f42" stroke-width="7"/><ellipse cx="${x+47+j*65}" cy="${295-h*17}" rx="18" ry="9" fill="#579358"/><rect x="${x+18+j*65}" y="285" width="35" height="24" fill="#ab744f"/>`).join('')}<text x="${x}" y="340" font-size="20" fill="#163e43">Mean: ${n(g.mean)} cm</text>`;}).join('')}<text x="40" y="390" font-size="18" fill="#163e43">Equal starting heights; schematic plants, measured values above.</text>`;}
export function traitEvidence(trials){return `<section class="model-card"><h3>Environment and inherited-type record</h3><div class="table-scroll"><table><caption>Saved day 7 heights (cm) for every tested group</caption><thead><tr><th>Trial</th><th>Type</th><th>Light (%)</th><th>Plant 1</th><th>Plant 2</th><th>Plant 3</th><th>Mean</th></tr></thead><tbody>${trials.flatMap((t,i)=>(t.groups||[]).map(g=>`<tr><th>${i+1}</th><td>${g.type==='A'?'A':'B'}</td><td>${n(g.light)}</td>${g.replicates.map(h=>`<td>${n(h)}</td>`).join('')}<td>${n(g.mean)}</td></tr>`)).join('')}</tbody></table></div><p>Compare one type across light settings to investigate environment. Compare types at the same light to investigate inherited differences in that environment. A comparison changing both cannot separate the two effects.</p><p>These are fixed simulated replicates, not independent samples from a real population. Different modeled responses do not prove any type is best in every environment.</p></section>`;}
