import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import fs from 'node:fs';import {createRequire} from 'node:module';
import * as engine from '../engine.js';import * as content from '../academy/content.js';import * as art from '../academy/art.js';
const {USES,OBJECTS,TOTAL,sceneAt,stateFor,checkpoint,canOpen,complete,nextIndex}=content;
test('academy has exactly 3,000 unique illustrated scenes, all paired contrasts and accessible descriptions',()=>{
 assert.equal(USES.length,60);assert.equal(OBJECTS.length,50);assert.equal(art.ART_IDS.length,50);const sentences=new Set(),images=new Set(),pairs=new Set();
 for(let i=0;i<TOTAL;i++){let s=sceneAt(i);assert.ok(s.use.incorrect&&s.use.incorrect!==s.use.use);assert.ok(art.ART_IDS.includes(s.object.art));assert.ok(!/\{[a-z]+\}/.test(s.sentence));let svg=art.illustration(s),other=art.illustration(s,s.use.wrong);assert.notEqual(svg,other);assert.ok(svg.includes('role="img"'));assert.ok(!/NaN|undefined|<script|https?:\/\//.test(svg.replace('http://www.w3.org/2000/svg','')));assert.notEqual(art.describe(s),art.describe(s,s.use.wrong));sentences.add(s.sentence);images.add(createHash('sha256').update(svg).digest('hex'));pairs.add(s.use.id+':'+s.object.id);}
 assert.equal(sentences.size,3000);assert.equal(images.size,3000);assert.equal(pairs.size,3000);assert.throws(()=>sceneAt(-1));assert.throws(()=>sceneAt(3000));
});
test('academy completion requires passed checkpoints; saves preserve all 3,000 and reject malformed data',()=>{
 let p=engine.newProfile('Learner'),a=stateFor(p);assert.ok(canOpen(p,0));assert.ok(!canOpen(p,1));assert.ok(!complete(p,0));a.checkpoint=checkpoint(0);assert.ok(!complete(p,0));
 for(let i=0;i<3000;i++){a.checkpoint={index:i,phase:'done',feedback:null};assert.ok(complete(p,i,100+i));}assert.equal(p.xp,30000);assert.equal(nextIndex(a.completed),null);a.checkpoint={index:0,phase:'done',feedback:null};complete(p,0);assert.equal(p.xp,30000);
 const s={version:1,active:p.id,profiles:[p]};assert.deepEqual(engine.validateSave(s),s);a.completed.a3000=100;assert.throws(()=>engine.validateSave(s));delete a.completed.a3000;a.checkpoint={index:0,phase:'bad',feedback:null};assert.throws(()=>engine.validateSave(s));
});
const require=createRequire(import.meta.url),{JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
function setup(existing){const root=new URL('../academy/',import.meta.url);const d=new JSDOM(fs.readFileSync(new URL('index.html',root),'utf8'),{url:'https://example.test/linguistics-quest/academy/',runScripts:'outside-only'}),w=d.window;w.__engine=engine;w.__content=content;w.__art=art;w.scrollTo=()=>{};if(existing)w.localStorage.setItem(engine.SAVE_KEY,JSON.stringify(existing));let src=fs.readFileSync(new URL('app.js',root),'utf8').replace(/^import \{([^}]+)\} from '\.\.\/engine.js';/m,'const {$1}=window.__engine;').replace(/^import \{([^}]+)\} from '\.\/content.js';/m,'const {$1}=window.__content;').replace(/^import \{([^}]+)\} from '\.\/art.js';/m,'const {illustration,describe,escape:esc}=window.__art;');w.eval(src);const click=s=>{let b=w.document.querySelector(s);assert.ok(b,s);b.click();};const save=()=>JSON.parse(w.localStorage.getItem(engine.SAVE_KEY)),p=()=>{let s=save();return s.profiles.find(x=>x.id===s.active);};return {w,click,save,p,close:()=>w.close()};}
test('academy UI teaches, corrects a mistake, resumes across reload, completes, and isolates family profiles',()=>{
 let a=setup();try{a.click('[data-action="open"]');assert.ok(a.w.document.querySelector('.explanation'));a.click('[data-action="compare"]');assert.match(a.w.document.querySelector('.caption').textContent,/outside/);a.click('[data-action="teach-next"]');a.click('[data-kind="in"]');assert.equal(Object.keys(a.p().records).length,0);a.click('[data-action="continue"]');a.click('[data-kind="beside"]');assert.ok(a.w.document.querySelector('.feedback.wrong'));assert.equal(Object.keys(a.p().academy.completed).length,0);a.click('[data-action="continue"]');assert.ok(a.w.document.querySelector('.explanation'));a.click('[data-action="teach-next"]');a.click('[data-kind="in"]');a.click('[data-action="continue"]');a.click('[data-kind="in"]');a.click('[data-action="continue"]');let backup=a.save();a.close();a=setup(backup);a.click('[data-action="open"]');assert.match(a.w.document.querySelector('h1').textContent,/What does/);a.click('[data-action="answer-meaning"][data-id="in"]');const attempts=a.p().records['academy.in'].attempts;a.click('[data-action="answer-meaning"][data-id="in"]');assert.equal(a.p().records['academy.in'].attempts,attempts);a.click('[data-action="continue"]');assert.ok(a.w.document.querySelector('.celebration'));assert.equal(a.p().xp,10);assert.equal(Object.keys(a.p().academy.completed).length,1);a.click('[data-action="open"]');assert.equal(a.p().academy.checkpoint.index,1);
 a.click('[data-action="library"]');assert.equal(a.w.document.querySelectorAll('#use option').length,60);assert.equal(a.w.document.querySelectorAll('#object option').length,50);a.w.document.querySelector('#use').value='59';a.w.document.querySelector('#object').value='49';a.w.document.querySelector('#object').dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.match(a.w.document.querySelector('#library-scene').textContent,/3,000|3000/);assert.equal(Object.keys(a.p().academy.completed).length,1);
 backup=a.save();const sibling=engine.newProfile('Sibling');backup.profiles.push(sibling);a.close();a=setup(backup);const select=a.w.document.querySelector('#profile');select.value=sibling.id;select.dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.equal(Object.keys(a.p().academy.completed).length,0);assert.ok(engine.validateSave(a.save()));
 }finally{a.close();}
});
