import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import zlib from 'node:zlib';
import {ENTRIES,WORLDS} from '../content.js';
import {newProfile,recordAnswer,mastery,DAY,buildQuestion,correctAnswer,pickEntries,validateSave,loadSave} from '../engine.js';
const now=Date.UTC(2026,8,16);
test('every guided meaning has valid content, unique ID, and a known world',()=>{
 assert.equal(ENTRIES.length,294);assert.equal(new Set(ENTRIES.map(e=>e.id)).size,ENTRIES.length);
 for(const e of ENTRIES){assert.ok(WORLDS.some(w=>w.id===e.world));assert.ok(e.meaning&&e.trap&&e.term);assert.equal(e.examples.length,2);assert.ok(e.examples.every(x=>typeof x==='string'&&x.length>5));assert.ok(e.level>=1&&e.level<=4);for(const form of ['meaning','context','recall']){const q=buildQuestion(e,ENTRIES,form);assert.ok(correctAnswer(q,q.answer));if(q.choices){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);assert.equal(q.choices.filter(c=>correctAnswer(q,c)).length,1);}if(form!=='recall')assert.ok(q.example);}}
});
test('repeated same-day recognition cannot qualify as retained mastery',()=>{let e=ENTRIES[0],r;for(let i=0;i<20;i++)r=recordAnswer(r,{correct:true,form:'meaning',now:now+i});assert.equal(mastery(r,e,now).retained,false);assert.equal(r.days.length,1);});
test('three dates and varied forms qualify; due reviews and lapses change status',()=>{const e=ENTRIES[0];let r;for(const [i,form] of ['meaning','context','recall','context'].entries())r=recordAnswer(r,{correct:true,form,now:now+Math.floor(i*.8)*DAY});assert.equal(mastery(r,e,now+3*DAY).retained,true);assert.equal(mastery(r,e,r.due+1).label,'Review due');r=recordAnswer(r,{correct:false,form:'context',confidence:'sure',now:now+4*DAY});assert.equal(r.repair,true);assert.equal(r.overconfident,true);assert.equal(mastery(r,e).retained,false);assert.equal(r.days.length,0);});
test('hint-assisted answers do not count as independent understanding',()=>{const r=recordAnswer(undefined,{correct:true,form:'recall',hint:true,now});assert.equal(r.correct,0);assert.equal(r.repair,true);assert.equal(r.streak,0);});
test('symbols can demonstrate retention without impossible symbol typing',()=>{let r;const e=ENTRIES.find(e=>e.term==='=');for(let i=0;i<4;i++)r=recordAnswer(r,{correct:true,form:i%2?'context':'meaning',now:now+Math.floor(i*.8)*DAY});assert.equal(mastery(r,e,now+3*DAY).retained,true);});
test('beginner queues exclude advanced content; repairs have priority',()=>{let p=newProfile('Test',1);assert.ok(pickEntries(ENTRIES,p,{limit:999}).every(e=>e.level===1));p.records['little.1']=recordAnswer(undefined,{correct:false,form:'meaning',now});assert.equal(pickEntries(ENTRIES,p,{limit:8,now})[0].id,'little.1');assert.equal(pickEntries(ENTRIES,p,{review:true,now}).length,1);});
test('family save validation rejects malformed records and duplicates; corruption is preserved',()=>{let a=newProfile('One',1),b=newProfile('Two',3);a.records['little.1']=recordAnswer(undefined,{correct:true,form:'meaning',now});let s=validateSave({version:1,active:a.id,profiles:[a,b]});assert.equal(s.profiles[1].xp,0);assert.equal(Object.keys(s.profiles[1].records).length,0);assert.throws(()=>validateSave({...s,profiles:[a,a]}));assert.throws(()=>validateSave({...s,active:'missing'}));const r=loadSave({getItem(){return '{invalid';},setItem(){throw Error('must not overwrite');}});assert.ok(r.error);});
test('retrieval accepts harmless capitalization but not wrong words; math normalization preserves distinctions',()=>{let q=buildQuestion(ENTRIES.find(e=>e.term==='because'),ENTRIES,'recall');assert.ok(correctAnswer(q,' Because '));assert.ok(!correctAnswer(q,'although'));q=buildQuestion(ENTRIES.find(e=>e.term==='−'),ENTRIES,'recall');assert.ok(correctAnswer(q,'-'));assert.ok(!correctAnswer(q,'+'));});
test('full reference manifest matches actual shards and includes license',()=>{let total=0,senses=0;for(const bucket of 'abcdefghijklmnopqrstuvwxyz_'){let x=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL(`../data/${bucket}.json.gz`,import.meta.url))));total+=Object.keys(x).length;senses+=Object.values(x).reduce((a,v)=>a+v.length,0);for(const arr of Object.values(x))for(const r of arr)assert.ok(r[2]&&Array.isArray(r[3]));}let m=JSON.parse(fs.readFileSync(new URL('../data/manifest.json',import.meta.url)));assert.equal(total,m.headwords);assert.equal(senses,m.senses);assert.ok(fs.readFileSync(new URL('../data/WORDNET-LICENSE.txt',import.meta.url),'utf8').includes('Princeton'));assert.equal(JSON.parse(fs.readFileSync(new URL('../data/symbols.json',import.meta.url))).length,m.symbols);});
