import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
import * as engine from '../engine.js';import * as content from '../content.js';
const require=createRequire(import.meta.url);const {JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
const root=new URL('../',import.meta.url);
function setup(){const dom=new JSDOM(fs.readFileSync(new URL('index.html',root),'utf8'),{url:'https://example.test/engineering-quest/linguistics-quest/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 Object.assign(w,{__content:content,__engine:engine,Response,DecompressionStream,confirm:()=>true});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.scrollTo=()=>{};w.fetch=async url=>{try{let f=new URL(String(url).replace(/^\.\//,''),root);return new Response(fs.readFileSync(f),{status:200});}catch{return new Response('',{status:404});}};
 let source=fs.readFileSync(new URL('app.js',root),'utf8').replace(/^import \{([^}]+)\} from '\.\/content.js';/m,'const {$1}=window.__content;').replace(/^import \{([^}]+)\} from '\.\/engine.js';/m,'const {$1}=window.__engine;');w.eval(source);
 const click=(sel)=>{let e=w.document.querySelector(sel);assert.ok(e,sel);e.click();};const saved=()=>JSON.parse(w.localStorage.getItem(engine.SAVE_KEY));const active=()=>{let s=saved();return s.profiles.find(p=>p.id===s.active);};const form=(id,values)=>{const f=w.document.querySelector(id);for(const [k,v] of Object.entries(values))f.elements.namedItem(k).value=v;f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};const solve=(wrong=false)=>{let id=w.document.querySelector('.quiz-card').dataset.qid,e=content.BY_ID[id]||active().custom.find(e=>e.id===id);if(w.document.querySelector('#recall-form'))form('#recall-form',{answer:wrong?'wrong':e.term});else {let opts=[...w.document.querySelectorAll('[data-action="answer"]')];(wrong?opts.find(x=>x.dataset.value!==e.meaning):opts.find(x=>x.dataset.value===e.meaning)).click();}return id;};return {w,click,saved,active,form,solve,close:()=>w.close()};}
test('UI mission, repair, retrieval, independent profiles, reload, and reference collection',async()=>{const a=setup();try{
 const {w,click,form,solve,active,saved}=a;assert.equal(w.document.querySelectorAll('.world-card').length,12);
 click('[data-action="world"][data-id="little"]');click('[data-action="start"]');click('[data-action="confidence"][data-value="sure"]');const missed=solve(true);assert.ok(active().records[missed].overconfident);assert.ok(w.document.querySelector('.feedback.needs-work'));click('[data-action="next"]');for(let i=1;i<8;i++){solve();click('[data-action="next"]');}assert.ok(w.document.querySelector('.results'));assert.equal(Object.keys(active().records).length,8);assert.equal(active().xp,72);assert.ok(active().completed.includes('little'));click('[data-action="finish-home"]');
 click('[data-route="repair"]');assert.ok(w.document.querySelectorAll('.entry-card').length>=1);click('[data-action="start"]');solve();click('[data-action="next"]');assert.ok(w.document.querySelector('.results'));click('[data-action="finish-home"]');
 click('[data-route="library"]');const search=w.document.querySelector('#search');search.value='because';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok(w.document.querySelector('.empty'));search.value='the';search.dispatchEvent(new w.Event('input',{bubbles:true}));click('[data-action="detail"][data-id="little.1"]');click('[data-action="single"]');for(let i=0;i<3;i++){solve();click('[data-action="next"]');}assert.ok(w.document.querySelector('.results'));click('[data-action="finish-home"]');
 const first=saved().active,firstXP=active().xp;click('[data-action="profiles"]');form('#new-profile',{name:'Parent test',level:'5'});assert.equal(active().xp,0);assert.equal(saved().profiles.length,2);click('[data-route="library"]');click('[data-route="reference"]');form('#reference-form',{query:'photosynthesis'});await new Promise(r=>setTimeout(r,300));assert.ok(w.document.querySelector('.reference-card'));click('[data-action="add-word"]');assert.ok(active().custom.length===1);click('[data-route="arcade"]');click('[data-mode="collection"]');solve();click('[data-action="next"]');assert.ok(w.document.querySelector('.results'));click('[data-action="finish-home"]');
 click('[data-route="library"]');click('[data-route="reference"]');click('[data-action="ref-mode"][data-value="symbols"]');form('#reference-form',{query:'U+003D'});await new Promise(r=>setTimeout(r,200));assert.ok(w.document.querySelector('.unicode-card').textContent.includes('EQUALS SIGN'));
 click('[data-action="profiles"]');click(`[data-action="switch-profile"][data-id="${first}"]`);assert.equal(active().xp,firstXP);assert.equal(w.document.querySelectorAll('.world-card').length,12);assert.ok(engine.validateSave(saved()));
 }finally{a.close();}});
test('UI hint, diagnostic, timed pause and double-submission safeguards',()=>{const a=setup();try{const {w,click,solve,active}=a;click('[data-action="diagnostic"]');for(let i=0;i<12;i++){solve();click('[data-action="next"]');}assert.ok(w.document.querySelector('.results'));assert.equal(w.localStorage.getItem(engine.SAVE_KEY),null);click('[data-action="finish-home"]');click('[data-route="arcade"]');click('[data-mode="practice"]');click('[data-action="hint"]');let id=solve();assert.equal(active().records[id].correct,0);assert.equal(active().records[id].repair,true);const attempts=active().records[id].attempts;const disabled=w.document.querySelector('[data-action="answer"]');if(disabled)disabled.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));assert.equal(active().records[id].attempts,attempts);click('[data-action="exit"]');click('[data-route="arcade"]');click('[data-mode="blitz"]');click('[data-action="pause"]');assert.ok(w.document.querySelector('.pause-cover'));click('.pause-cover [data-action="pause"]');assert.equal(w.document.querySelector('.pause-cover'),null);click('[data-action="exit"]');}finally{a.close();}});
