import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import * as model from '../visual-library/model.js';
import * as engine from '../engine.js';
const require=createRequire(import.meta.url),{JSDOM}=require(process.env.JSDOM_MODULE||'jsdom'),{IDBFactory}=require(process.env.IDB_MODULE||'fake-indexeddb');
const sample={format:'visual-library-pack',version:1,id:'fixture',title:'Test book',pages:[{id:'p1',number:1,title:'Plants',chapter:'Plants and plantlike organisms',image:'data:image/png;base64,aGVsbG8=',ocr:'A leaf and root.'}],cards:[{id:'leaf',pageId:'p1',term:'leaf',meaning:'A part that captures light.',example:'A leaf receives sunlight.',notice:'Look at the flat part.',chapter:'Plants and plantlike organisms'},{id:'root',pageId:'p1',term:'root',meaning:'A part that takes in water.',example:'A root absorbs water.',notice:'Look underground.',chapter:'Plants and plantlike organisms'}]};
test('pack validation rejects dangling references, duplicate IDs and active image content',()=>{
 assert.equal(model.validatePack(structuredClone(sample)).cards.length,2);
 for(const change of [p=>p.cards[0].pageId='missing',p=>p.pages.push(p.pages[0]),p=>p.cards.push(p.cards[0]),p=>p.pages[0].image='data:image/svg+xml;base64,PHN2Zz4=',p=>p.cards[0].meaning='',p=>p.cards[0].parentId='leaf']){let p=structuredClone(sample);change(p);assert.throws(()=>model.validatePack(p));}
});
test('answer scheduling and progress merge preserve newer answers and isolate failed checks',()=>{
 const a=model.recordAttempt(null,true,1000);assert.equal(a.due,1000+model.DAY);const b=model.recordAttempt(a,false,2000);assert.equal(b.correct,1);assert.equal(b.stage,0);assert.equal(b.due,2000);assert.equal(model.mergeProgress(b,a),b);assert.throws(()=>model.validateProgress({format:'visual-library-progress',version:1,records:[{id:'bad',value:{attempts:1,correct:2}}]}));
});
async function wait(fn){for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('UI did not reach expected state');}
async function setup(idb=new IDBFactory(),save){const d=new JSDOM(fs.readFileSync(new URL('../visual-library/index.html',import.meta.url),'utf8'),{url:'https://test.invalid/linguistics-quest/visual-library/',runScripts:'outside-only'}),w=d.window;Object.defineProperty(w,'indexedDB',{value:idb});w.__engine=engine;w.__model=model;w.scrollTo=()=>{};if(save)w.localStorage.setItem(engine.SAVE_KEY,JSON.stringify(save));let src=fs.readFileSync(new URL('../visual-library/app.js',import.meta.url),'utf8').replace(/^import \{loadSave\} from '..\/engine.js';/m,'const {loadSave}=window.__engine;').replace(/^import \{([^}]+)\} from '.\/model.js';/m,'const {$1}=window.__model;');w.eval(src);await wait(()=>w.document.querySelector('[data-action="import"]'));const click=s=>{const b=w.document.querySelector(s);assert.ok(b,s);b.click();};const input=async(p,selector='#pack-file')=>{const el=w.document.querySelector(selector),text=JSON.stringify(p);Object.defineProperty(el,'files',{configurable:true,value:[{size:text.length,text:async()=>text}]});el.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>!w.document.querySelector('#status').textContent.includes('Importing'));};return{w,idb,click,input,close:()=>w.close()};}
test('imports, wrong-answer teaching, persisted answers, repeat imports and sibling isolation',async()=>{
 const p=engine.newProfile('Reader'),s=engine.newProfile('Sibling'),save={version:1,active:p.id,profiles:[p,s]};let a=await setup(undefined,save);
 try{await a.input(sample);assert.match(a.w.document.querySelector('main').textContent,/2 meaning cards/);a.click('[data-action="study"]');assert.equal(a.w.document.querySelector('h1').textContent,'leaf');a.click('[data-action="reveal"]');assert.match(a.w.document.querySelector('main').textContent,/A leaf receives sunlight/);a.click('[data-action="quiz"]');let wrong=[...a.w.document.querySelectorAll('[data-action="answer"]')].find(b=>b.textContent.includes('water'));wrong.click();await wait(()=>a.w.document.querySelector('.feedback.wrong'));a.click('[data-action="retry"]');a.click('[data-action="quiz"]');let correct=[...a.w.document.querySelectorAll('[data-action="answer"]')].find(b=>b.textContent.includes('light'));correct.click();await wait(()=>a.w.document.querySelector('[data-action="next-card"]'));correct.click();a.click('[data-action="next-card"]');assert.equal(a.w.document.querySelector('h1').textContent,'root');const idb=a.idb;a.close();a=await setup(idb,save);assert.match(a.w.document.querySelector('.metrics').textContent,/1 \/ 2/);await a.input(sample);assert.match(a.w.document.querySelector('.metrics').textContent,/1 \/ 2/);const sel=a.w.document.querySelector('#profile');sel.value=s.id;sel.dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.match(a.w.document.querySelector('.metrics').textContent,/0 \/ 2/);a.click('[data-action="browse"]');a.w.document.querySelector('#search').value='root';a.click('[data-action="search"]');a.click('[data-action="page"]');assert.match(a.w.document.querySelector('h1').textContent,/Plants/);assert.equal(a.w.document.querySelectorAll('[data-action="card"]').length,2);
 }finally{a.close();}
});
test('invalid import leaves existing library intact',async()=>{const a=await setup();try{await a.input(sample);const bad=structuredClone(sample);bad.cards[0].pageId='missing';await a.input(bad);assert.match(a.w.document.querySelector('#status').textContent,/invalid/);a.click('[data-action="home"]');assert.match(a.w.document.querySelector('.metrics').textContent,/2prepared meaning cards/);}finally{a.close();}});
test('prepared upload has complete page coverage and well-formed teaching cards',{skip:!process.env.STUDY_PACK},()=>{const p=model.validatePack(JSON.parse(fs.readFileSync(process.env.STUDY_PACK,'utf8')));assert.equal(p.pages.length,126);assert.ok(p.cards.length>2000);assert.deepEqual(p.pages.map(x=>x.number),Array.from({length:126},(_,i)=>i+1));for(const n of Array.from({length:113},(_,i)=>i+14).filter(n=>![40,41,100,101].includes(n)))assert.ok(p.cards.some(c=>c.pageId===`pdf-${String(n).padStart(3,'0')}`),`page ${n}`);assert.equal(p.cards.filter(c=>c.pageId==='pdf-122').length,29);const buckwheat=p.cards.find(c=>c.id==='buckwheat');assert.equal(buckwheat.parentId,'grain-plants');assert.ok(buckwheat.image.startsWith('data:image/jpeg;base64,'));assert.ok(buckwheat.sourceDefinition.includes('flour'));});
test('real pack supports grain industry to grain plants to buckwheat and exact-item pictures',{skip:!process.env.STUDY_PACK},async()=>{const a=await setup();try{const pack=JSON.parse(fs.readFileSync(process.env.STUDY_PACK,'utf8'));await a.input(pack);a.click('[data-action="lookup"]');a.w.document.querySelector('#word-search').value='grain industry';a.click('[data-action="word-search"]');a.click('[data-action="card"][data-key$="::grain-industry"]');a.click('[data-action="card"][data-key$="::grain-plants"]');a.click('[data-action="card"][data-key$="::buckwheat"]');assert.equal(a.w.document.querySelector('h1').textContent,'buckwheat');a.click('[data-action="reveal"]');assert.match(a.w.document.querySelector('main').textContent,/Cereal cultivated for its grain/);assert.equal(a.w.document.querySelector('.item-image').getAttribute('src'),pack.cards.find(c=>c.id==='buckwheat').image);a.click('[data-action="quiz"]');assert.match(a.w.document.querySelector('h1').textContent,/buckwheat/);}finally{a.close();}});

test('scan cards reveal source definitions and preserve answer progress',async()=>{const a=await setup();try{const p=structuredClone(sample);p.pages[0].layout=[500,600];p.cards[0]={id:'leaf',pageId:'p1',term:'leaf',chapter:p.cards[0].chapter,sourceMode:'scan',crop:[0,0,500,600],labelBox:[20,20,70,40],definitionCrop:[20,50,250,100],needsReview:true};await a.input(p);a.click('[data-action="study"]');assert.ok(a.w.document.querySelector('svg rect'));a.click('[data-action="reveal"]');assert.ok(a.w.document.querySelector('.definition-clip'));a.click('[data-action="quiz"]');assert.match(a.w.document.querySelector('h1').textContent,/Which word/);[...a.w.document.querySelectorAll('[data-action="answer"]')].find(b=>b.textContent==='leaf').click();await wait(()=>a.w.document.querySelector('[data-action="next-card"]'));a.click('[data-action="next-card"]');assert.equal(a.w.document.querySelector('h1').textContent,'root');}finally{a.close();}});
