// Guided picture practice is kept separate from independent comprehension scores.
export const LITTLE=[
 {id:'buddy',name:'Buddy',steps:[['dog','dog','cat'],['bed','bed-red','ball-red'],['red','ball-red','ball-blue'],['a red bed','bed-red','bed-blue'],['The dog is on the bed.','dog-on','dog-by'],['The dog can nap.','dog-nap','dog-ball']]},
 {id:'dot',name:'Dot',steps:[['dog','dog','cat'],['ball','ball-red','bed-red'],['blue','ball-blue','ball-red'],['a blue ball','ball-blue','ball-red'],['The ball is by the bed.','ball-by','ball-on'],['The dog has a ball.','dog-ball','dog-nap']]}
];
const labels={'dog':'A dog','cat':'A cat','bed-red':'A red bed','bed-blue':'A blue bed','ball-red':'A red ball','ball-blue':'A blue ball','dog-on':'A dog on a bed','dog-by':'A dog beside a bed','dog-nap':'A dog asleep','dog-ball':'A dog with a ball','ball-by':'A ball beside a bed','ball-on':'A ball on a bed'};
const pup=(x=70,y=65,scale=1,asleep=false)=>`<g transform="translate(${x} ${y}) scale(${scale})"><ellipse cx="40" cy="51" rx="35" ry="26" fill="#d89954"/><path d="M15 19Q-12-8 1 48L20 41M61 19Q91-8 79 48L61 41" fill="#895234"/><ellipse cx="40" cy="30" rx="32" ry="28" fill="#eab673"/><ellipse cx="40" cy="42" rx="20" ry="14" fill="#fff3db"/>${asleep?'<path d="M20 27l12 1m16 0 12-1" stroke="#273e35" stroke-width="3"/>':'<circle cx="26" cy="27" r="3" fill="#273e35"/><circle cx="54" cy="27" r="3" fill="#273e35"/>'}<path d="M34 36h12l-6 7z" fill="#273e35"/><path d="M31 47q9 9 18 0" fill="none" stroke="#273e35" stroke-width="2"/></g>`;
const bed=(color='#cf4e4c',x=35,y=113,w=150)=>`<ellipse cx="${x+w/2}" cy="${y+18}" rx="${w/2}" ry="27" fill="${color}"/><ellipse cx="${x+w/2}" cy="${y+11}" rx="${w*.39}" ry="15" fill="#fff2df"/><path d="M${x+8} ${y+17}q${w/2-8} 35 ${w-16} 0" fill="none" stroke="${color}" stroke-width="18"/>`;
const ball=(color='#cc4547',x=110,y=96,r=40)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${color}"/><path d="M${x-r*.6} ${y-r*.7}q${r} ${r*.6} ${r*1.2} ${r*1.4}" stroke="#fff7df" stroke-width="6" fill="none"/>`;
export function picture(type){let art='';if(type==='dog')art=pup();else if(type==='cat')art='<path d="M72 62L64 28L95 45H126L156 28L148 68Q161 134 110 137Q59 134 72 62" fill="#899fa9"/><circle cx="92" cy="81" r="5"/><circle cx="128" cy="81" r="5"/><path d="M104 97h12l-6 7zM65 105l27 3m36 0 27-3M66 117l26-3m36 0 26 3" stroke="#273e35" fill="#273e35" stroke-width="3"/>';else if(type.startsWith('bed-'))art=bed(type.endsWith('blue')?'#387eaf':'#cf4e4c',35,92);else if(type.startsWith('ball-')&&['ball-red','ball-blue'].includes(type))art=ball(type.endsWith('blue')?'#387eaf':'#cc4547');else if(type==='dog-on')art=bed()+pup(70,51);else if(type==='dog-by')art=bed('#cf4e4c',16,112,100)+pup(137,65,.8);else if(type==='dog-nap')art=bed()+pup(70,68,1,true)+'<text x="161" y="55" font-size="25" fill="#426654">z</text>';else if(type==='dog-ball')art=pup(50,62)+ball('#387eaf',155,135,25);else if(type==='ball-by')art=bed('#cf4e4c',18,111,115)+ball('#387eaf',170,136,24);else if(type==='ball-on')art=bed()+ball('#387eaf',110,93,25);return`<svg viewBox="0 0 220 185" role="img" aria-label="${labels[type]}"><rect x="1" y="1" width="218" height="183" rx="20" fill="#f2f6e8"/>${art}</svg>`;}
const speaker='<svg class="little-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9h4l5-4v14l-5-4H3z" fill="currentColor"/><path d="M16 8q5 4 0 8m3-11q8 7 0 14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
const btn=(label,action,extra='')=>`<button class="btn" data-little="${action}" ${extra}>${label}</button>`;
let api,state=null;
export function setupLittle(config){api=config;document.querySelector('#app').addEventListener('click',e=>{const el=e.target.closest('[data-little]');if(!el||el.disabled)return;const action=el.dataset.little;e.preventDefault();if(action==='start'){const quest=LITTLE.find(q=>q.id===el.dataset.id)||LITTLE[0];state={quest,index:0,correct:false,feedback:'',options:[]};setStep();api.render();tell('Let’s help '+quest.name+'. '+instruction());}else if(action==='home'){resetLittle();api.render();}else if(action==='hear'){tell(instruction());}else if(action==='word'){tell(state.quest.steps[state.index][0]);}else if(action==='choose'&&state&&!state.correct){if(el.dataset.picture===state.quest.steps[state.index][1]){state.correct=true;state.feedback='You got it!';api.render();tell('You got it! Tap the arrow to go on.');}else{state.feedback='Try the other picture.';api.render();tell('Let’s try again. Look at the words. You can tap the speaker to hear it.');}}else if(action==='next'&&state?.correct){state.index++;state.correct=false;state.feedback='';if(state.index===state.quest.steps.length){const t=api.progress();t.little??=[];if(!t.little.includes(state.quest.id))t.little.push(state.quest.id);api.save();api.render();tell('You helped '+state.quest.name+'! Great work.');}else{setStep();api.render();tell(instruction());}}window.scrollTo(0,0);});}
function tell(text){api.speak(text);}
function instruction(){return state.index<3?'Look at the word. Tap the matching picture.':'Read these words. Tap the matching picture.';}
function setStep(){state.options=state.quest.steps[state.index].slice(1);if(Math.random()<.5)state.options.reverse();}
export function resetLittle(){state=null;document.body.classList.remove('little-playing');window.speechSynthesis?.cancel();}
export function littleView(){if(!state)return'';document.body.classList.add('little-playing');const q=state.quest;if(state.index===q.steps.length)return`<section class="trail little-play"><div class="little-stars" aria-label="Six steps finished">★ ★ ★</div>${picture(q.id==='buddy'?'dog-nap':'dog-ball')}<h1>You helped ${q.name}!</h1>${btn('⌂ Home','home')}</section>`;return`<section class="trail little-play"><div class="little-top">${btn('⌂','home','aria-label="Back home"')}<span>Help ${q.name}</span><span>${state.index+1} / ${q.steps.length}</span></div><div class="little-dots" aria-label="${state.index} of ${q.steps.length} steps finished">${q.steps.map((_,i)=>`<i class="${i<state.index?'done':''}"></i>`).join('')}</div><h1>Tap the picture.</h1>${btn(speaker+' Help','hear','aria-label="Hear what to do"')}<div class="little-word"><p>${q.steps[state.index][0]}</p>${btn(speaker,'word','aria-label="Hear these words"')}</div><div class="little-pictures">${state.options.map(type=>btn(picture(type),'choose',`data-picture="${type}" aria-label="${labels[type]}" ${state.correct?'disabled':''}`)).join('')}</div><p class="little-feedback" role="status">${state.feedback||' '}</p>${state.correct?btn('Next →','next'):''}</section>`;}
export function littleHome(progress){return`<section class="trail little-home"><small>PAWPRINT TRAIL · START HERE</small><h1>Let’s help a dog!</h1><p>Tap a dog to play.</p><div class="little-pictures">${LITTLE.map(q=>btn(`${picture(q.id==='buddy'?'dog-nap':'dog-ball')}<span>${q.name} ${progress.little?.includes(q.id)?'★':''}</span>`,'start',`data-id="${q.id}"`)).join('')}</div><details><summary>For grown-ups</summary><p>This guided starting path uses one word or a short sentence, spoken directions, and two pictures. Tap the speaker to hear the words. Help and retries are welcome. Finished rescues earn a star, separate from independent reading passes. Device voices may need internet; a grown-up can read the directions if audio is unavailable.</p><p>When she is ready, open the chapter map below to try the longer stories.</p></details></section>`;}
