import {STORIES,STORY_BY_ID} from './trail-content.js';
export const wordCount=text=>(text.match(/[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*/gu)||[]).length;
export const newTrail=()=>({rescued:[],passed:[],bests:{},attempts:{}});
export function validateTrail(t){if(!t||typeof t!=='object')throw Error('Invalid reading progress.');const clean=newTrail();if(t.little!==undefined){if(!Array.isArray(t.little)||t.little.some(id=>!['buddy','dot'].includes(id)))throw Error('Invalid beginner progress.');clean.little=[...new Set(t.little)];}for(const key of ['rescued','passed']){if(!Array.isArray(t[key])||t[key].some(id=>!STORY_BY_ID[id]))throw Error('Invalid rescue record.');clean[key]=[...new Set(t[key])];}for(const key of ['bests','attempts']){for(const [id,n]of Object.entries(t[key]||{})){if(!STORY_BY_ID[id]||!Number.isFinite(n)||n<0)throw Error('Invalid reading record.');clean[key][id]=n;}}return clean;}
export const trailOf=p=>p.trail??=newTrail();
export const unlocked=(t,grade)=>grade===1||STORIES.filter(s=>s.grade<grade).every(s=>t.passed.includes(s.id));
export function readingResult(story,answers,ms,assisted=false){const correct=story.questions.filter((q,i)=>answers[i]===q.answer).length;const words=wordCount(story.text);return{correct,total:story.questions.length,words,ms,wpm:ms>=1000?Math.round(words*60000/ms):0,passed:correct/story.questions.length>=.8,eligible:!assisted&&ms>=1000&&correct/story.questions.length>=.8,assisted};}
export function saveReading(p,story,result,mode){const t=trailOf(p);t.attempts[story.id]=(t.attempts[story.id]||0)+1;if(mode==='adventure'&&result.passed){if(!t.rescued.includes(story.id)){t.rescued.push(story.id);p.xp+=30;p.gears+=5;}if(!result.assisted&&!t.passed.includes(story.id))t.passed.push(story.id);}if(mode==='reading'&&result.eligible)t.bests[story.id]=Math.max(t.bests[story.id]||0,result.wpm);}
export function winner(results){const eligible=results.map((r,i)=>({...r,i})).filter(r=>r.eligible);if(!eligible.length)return'No winner yet — try again for at least 4 of 5 correct.';if(eligible.length===1)return`Player ${eligible[0].i+1} wins!`;if(eligible[0].wpm===eligible[1].wpm)return'It’s a tie!';return`Player ${eligible.sort((a,b)=>b.wpm-a.wpm)[0].i+1} wins!`;}
